### ISSUE TITLE
Lost ability to edit image ALT tag in RTE

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1000]
Hey Ryan,

Am I missing something obvious?

Looks like this is no longer possible to edit without going into HTML view.

**Comment by teppokoivula** [comment]
@adrianbj, unless *I'm* the one missing something obvious, the "quote" icon in the image select/edit modal is exactly for this purpose? :)

**Comment by adrianbj** [comment]
Of course, you're right. I actually noticed and tested that button, then apparently forgot about what it was for when looking for a way to edit the ALT tag :)

I am not sure how obvious this will be to clients - I am not a big user of images in RTE fields, but when there is a need, I do like proper ALT tags to be entered.

Anyway, you can ignore this for now!

**Comment by ryancramerdesign** [comment]
I deemphasized the alt tag here since the module now pulls it from the
image description. So we actually kind of prefer that people don't enter
the alt tag here (unless that's the intent), because we can now keep it up
to date dynamically with their image descriptions (when left blank).

**Comment by adrianbj** [comment]
Hey Ryan,

I think that is a good approach, but I think the issue is that if you upload an image, add the description and then insert the image into RTE before saving the page, the description text is not copied into the ALT tag. Could you add some JS to take care of this?

Actually, I am just testing this at even if the image is uploaded, description entered, page saved and then inserted into the RTE, it still doesn't seem to work. When I save the page, the ALT tag is being populated with the image filename, but not the description field. Is there a bug somewhere?

**Comment by adrianbj** [comment]
I am going to reopen this because of the bug (previous post) that I am seeing with the description not populating the ALT tag.

**Comment by ryancramerdesign** [comment]
The description isn't supposed to be copied to the alt text until runtime (front-end with output formatting on). That way it can be populated according to the current image value, and even the current language. Keeping the description blank essentially declares it as dynamically tied to the image description, whatever that may be at runtime. That's one of the primary purposes of the "Markup/HTML with image management" content type, should you choose it for your Textarea field. 

The issue with the alt tag being populated with the filename was interfering with that though. It turned out that HTML Purifier was inserting the alt tag with the filename for some reason. It wasn't doing that before, but enabling some HTML5 features for it recently must have triggered it to start doing that. I was able to get around it by explicitly inserting a blank alt tag with the image, so this will appear in the next commit. Thanks!

**Comment by adrianbj** [comment]
Thanks for the explanation of it being used at runtime - makes sense. Also, thanks for overriding the insertion of the filename - was thinking that must have not been intentional :)
