### ISSUE TITLE
Roles as field visibility on user pages can't use role name

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1004]
I have some fields that only apply to a user when he has a role set. Right now you can only do:
- roles=1029

But you can't do:
- roles=member

AFAIK the second one is a valid selector, but for some reason it doesn't work.

**Comment by Renobird** [comment]
I believe roles.name=member works.

On mobile, will verify when back at desktop.

**Comment by LostKobrakai** [comment]
I struggeld with this last year, too. It's not the most userfriendly thing.

**Comment by plauclair** [comment]
@Renobird I think I tried this too but I don't think it worked. Either way I think it's the only one for which the selector won't accept the name field.

**Comment by ryancramerdesign** [comment]
The 'roles' field is just a Page field like any other, so you have to select from it the same way you would any other Page field. That means you select from it by either providing a page ID or path. What Renobird mentioned also works, since you are specifying you want to query the "name" property of the page. But in Page fields the name is not guaranteed to be unique (since items in a Page field may or may not all have the same parent). All roles pages have the same parent, so it's okay to do here, but keep this in mind if you use the "name" subfield on other Page fields. What I would suggest is this:
`````
$member = $roles->get('member');
$users->find("roles=$member"); 
`````
