### ISSUE TITLE
Please use @since for phpdocs

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1015]
Hi @ryancramerdesign,

As you might have seen on the forums, some of us want to start working on the docs. It would be very helpful to us if, when you make changes that modify the behavior of classes/methods/functions, if you could give us hints of the changes made.

```php
/**
  * Example of @since usage.
  *
  * @since 2.5.20 Added the $b argument.
  * @since 2.5.8 Added the $a argument.
  * @since 2.4.0
  */
```

Also, I'm thinking of going through previous code bases for different versions and add @since tags. Is that something you're ok with?

Thanks!

**Comment by ryancramerdesign** [comment]
Good idea, makes `@since` to me. I think especially as new methods are added – I will make a point to use `@since`. When it comes to existing methods, I never make changes that break backwards compatibility, though may add an argument or sometimes enable an existing argument to optionally serve as an $options array, so these would all be good uses for `@since` as well.

**Comment by owzim** [comment]
> makes @since to me
:+1:

**Comment by plauclair** [comment]
> Good idea, makes @since to me
LOL !

Thanks a lot! Do you have archived versions of each major release somewhere?

**Comment by adrianbj** [comment]
Some of them are available here: https://github.com/ryancramerdesign/ProcessWire/releases
2.5 is not however!

**Comment by plauclair** [comment]
Thanks @adrianbj ! I guess 2.5.3 can be considered our "master" for 2.5, what do you think?

**Comment by adrianbj** [comment]
Yup 2.5.3 it is.

**Comment by plauclair** [comment]
Closing this conversation, since @ryancramerdesign is doing it.
