### ISSUE TITLE
404 when page is called "page1" or "page2"...

### ISSUE THREAD

**Issue by BernhardBaumrock** [ryancramerdesign/ProcessWire#1030]
reproduce:
fresh installation 2.5.22
blank profile
create page called "page1"  with template "basic-page" or "home" under root
view it -> get 404 not found

url segments and pagination are of course switched off

**Comment by ryancramerdesign** [comment]
This is for the config option, pageNumPrefix, which defines "page" (at end
of url) followed by any number, as being reserved for pagination. If you
need urls that end with page[0-9]+ you may need to change your
pageNumPrefix.

**Comment by BernhardBaumrock** [comment]
yes i know, but i think that should not happen when "allow page numbers" is switched off.
not a big problem though.

**Comment by ryancramerdesign** [comment]
At this stage, PW doesn't know if page numbers are on or off, because it doesn't know the page or the template. In the interest of speed/optimization the code here is built around trying to avoid any unnecessary PageFinder queries. If it were to attempt to see if the URL resolves to a page in the tree before a pagination, then it would have to perform extra $page->find() for every paginated page, which is specifically what its trying to avoid. I think for the majority of cases this is preferable.

**Comment by BernhardBaumrock** [comment]
i think you are right. thanks for clarifying this!
