### ISSUE TITLE
Inputfield default focus issues - dev 2.5.23

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1044]
Hi Ryan

The functionality whereby the page focuses the first text field in a form in this file: /wire/templates-admin/scripts/inputfields.js is undesirable in several scenarios. For example, I have built admin forms that start after several paragraphs of text or some long-ish and when you load pages like that it skips the window down to the first field which is unexpected.

Granted, custom admin forms are pretty niche but the same happens with 0.2.5c of Formbuilder on the frontend of a website since it uses the same inputfields.js file - if you have a form quite far down a page it jumps to the first field which is pretty undesirable also.

Can you remove this functionality please? It is helpful in many situations, but really unhelpful in others and is confusing unless you know why it's happening (I was scratching my head for a long time with this one!).

**Comment by adrianbj** [comment]
Hey Pete - I believe the issue has been fixed for formbuiler:
https://github.com/ryancramerdesign/ProcessWire/commit/0a5597708068d3b3563d5fc54cdee0072571b0f1

but I guess it might need to be made configurable in general.

**Comment by Notanotherdotcom** [comment]
Nope, that last block of code seems to have been where it was introduced actually, though I think it has been present before that and removed and made it back in again since that block of code also existed somewhere earlier than 3 days ago.

I was just discussing with someone that a nice way to work around this for the PW admin is via the addition of a class called something like "autofocus" to the default PW admin forms (though that's probably a reserved word) and that way custom forms can be built to either use it or not.

It could even be a form attribute, so in Process pages you could set $form->autofocus = true or false. It would be a bit of work to go through all the forms and add that, or simply make autofocus = true the default unless otherwise specified.

**Comment by Notanotherdotcom** [comment]
Oh sorry, I see that code has changed and I'm being an idiot. Let me check if that new code works.

**Comment by Notanotherdotcom** [comment]
Hmm... new code makes no difference though maybe I need the complete updated package.

I've commented out that code for now on my current project and will test again on the next dev release and see what happens.

**Comment by ryancramerdesign** [comment]
It shouldn't jump "below the fold" on a page, because we've got code in there that looks at the position of the input it plans to jump to, and if it's not in the visible region of the page, it should skip over it. If you are finding that's not the case, then the code I've got there must not be working right, so I'd want to take a closer look at that.

Beyond the condition above, there are a few other conditions that it requires before it'll focus an input. First, it will only focus a blank input. If the first text input in the form is populated, then it's not going t focus anything. Secondly, it has to be a literal `input[text]` field, and it won't attempt to focus anything other than those. It also should not exhibit this behavior unless your `form.InputfieldForm` is within a literal `<div id='content'></div>`, which is what all the PW admin themes use. But that's of course a pretty common div name, so… that's probably not much help.

Here's what I think you are looking for though: if you add the class `InputfieldNoFocus` to your `InputfieldForm` then it will not attempt to focus any inputs in the form. I think this is most likely what you want in your case? Programmatically, you can do it like this:
````````
$form = $modules->get('InputfieldForm');
$form->addClass('InputfieldNoFocus'); 
````````
I've debated whether it should be a class toggle to turn the feature on rather than turn it off. But in the end, most PW admin forms (whether core or 3rd party) benefit form this feature, so opted to go with the "turn off" toggle rather than a "turn on" toggle. I can imagine even myself forgetting about it unless I'm trying to stop the behavior for whatever reason. Probably what I should do though is go ahead and limit the behavior further so that it is either configurable (via $config) and/or requires the presence of an admin theme, as the `#content` div it currently looks for is too general purpose in name. PW 3.0 admin themes will likely go with a  prefix for all of this stuff, like `#pw-content`.

**Comment by Notanotherdotcom** [comment]
Sorry Ryan - I'd intended to say this worked afterwards so something must have got cached or something but it's all good now.

Thanks for the detail in the last comment there though - very useful to know.
