### ISSUE TITLE
Add a unified way of notifying installed modules of version changes

### ISSUE THREAD

**Issue by netcarver** [ryancramerdesign/ProcessWire#1061]
Having now seen a couple of methods that module authors have adopted to detect changes to module versions so they can change the DB schema their module uses when going from one version to another I'd like to suggest that the mechanism to detect and inform modules of version changes be made a responsibility of the core system.

Here's just one idea that might allow module authors to easily apply changes (I'm sure there are other ways to skin this cat)...

Add a ```onVersionChange(last_version, this_version)``` method to the ```module``` class and have PW call this method when it detects a change in version from the previous load of the module to the current load. Module authors can then fairly simply make and schema changes needed by overriding this in their derived class.

I'm hoping that this would be a pretty lightweight change to the core in terms of adding complexity to the existing DB queries needed to get a module loaded.

**Comment by LostKobrakai** [comment]
I'm certainly voting for such a solution, too. Simple and effective. Additionally it would be nice to be able to have update notifications if there's really something the user needs to know when doing a update, maybe as part of the module informations.

**Comment by NicoKnoll** [comment]
+1

**Comment by NicoKnoll** [comment]
But maybe with a more Processwire like name. "___upgrade" or "___installUpgrade" or something like this

**Comment by mike-anthony** [comment]
+1

**Comment by ryancramerdesign** [comment]
It sounds useful to me, but not a good way to do that at present as far as I know. PW doesn't know about version changes in modules until the modules cache is cleared or refreshed. It's too much overhead for it to locate and load module info separately for each module for every request (which is why it uses a cache). That might still be okay for an onVersionChange in many cases, but it probably wouldn't be in just as many. For instance, the vast majority of instances where I would use such a feature would be to apply DB schema changes. This would not be okay with an onVersionChange because it wouldn't run until PW knew about the version change. So a module could be executing new code that assumes some new schema before an onVersionChange, likely leading to a fatal error. That's why it's better for a module to keep track of that of these things at present. I will look into a way to handle it once we get past 2.6 though. An idea would be for PW to check all module file modification times on every request and compare them to the cache... if it finds a difference, pull module info the slow way, and clear the cache. That's still a lot of extra overhead, but probably okay if the check is limited to /site/modules/ and core modules left out of this fun.
