### ISSUE TITLE
Additional page list buttons after clicking move on an untitled item

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1063]
We've seen this before in the Children tab, which you fixed, but this is in the Content tab for untitled pages.

![screen shot 2015-04-03 at 4 47 14 pm](https://cloud.githubusercontent.com/assets/871211/6990485/c43511ea-da21-11e4-8a15-686665152415.png)

**Comment by ryancramerdesign** [comment]
Not sure I understand– what steps do I take to see that?

**Comment by adrianbj** [comment]
You just need an untitled item (automatic page naming, but cancelled before it was fully created). Then click on move - it will show an additional move button - click on that and you'll get an entire new set of action buttons.

**Comment by adrianbj** [comment]
Here is the other bug report. Looks like you didn't actually fix it - we couldn't figure out how to reproduce it: https://github.com/ryancramerdesign/ProcessWire/issues/742

In that other issue it wasn't just untitled pages, so who knows :)

**Comment by ryancramerdesign** [comment]
I still can't duplicate it here. I created a page (where the parent has a defined name format, so that it gets created in 1 step), then exited out of it while it was still untitled. I went to the PageList and tried "Move" on that "Untitled" page, but it behaves as expected. I also tried going to the parent page and doing the same within its Children tab, but no issues. 

You mentioned you saw the issue in the Content tab, but I'm not clear how you are seeing a PageList on the Content tab? Are you possibly talking about a Page field?  I'm thinking not since you haven't mentioned anything about that, but just double checking.

**Comment by teppokoivula** [comment]
@adrianbj Just tried to reproduce this, no success here either. Any chance you could create a simple test profile where this happens?

Which browser does this happen, by the way? If it turns out to be a JS issue, that would likely be a factor here too.

**Comment by mike-anthony** [comment]
I'm just looking at that screenshot and asking myself where that is. What's that small button that's been trimmed out at the bottom? What I'm guessing is that this is actually the Page Tree, and that you're a few levels deep... But that's just a guess, especially considering I can't reproduce.

**Comment by adrianbj** [comment]
Guys - I am an idiot!

Sorry for the wild goose chase - it was a rogue "!important" in my code for making page list action buttons appear on hover. I had used this previously, then switched to Reno where the behavior is built in. Then for various reasons have gone back to the default theme and then spending three months with horrendously slow internet made me really need the hover links again so I added the CSS through AdminCustomFiles (make a huge difference not having to ajax load all child pages just to get the action buttons to show up).

Anyway, for some reason I put "!important" after display:inline

Using just the following works fine:
```
.content .PageList .PageListItemOpen .PageListActions{display:none}
.content .PageList .PageListItem:hover .PageListActions{display:inline;-webkit-transition-delay:.25s;transition-delay:.25s}
```

Sorry again!

**Comment by teppokoivula** [comment]
Glad to hear that it was solved :)

**Comment by adrianbj** [comment]
And it had nothing to do with the Children tab, and definitely nothing to do with the Content tab - I did mean the main Page List view when I said Content - not my smartest day all around I'd say :)

**Comment by adrianbj** [comment]
PS I really do think the hover behavior is superior - PW is all about efficiency, so it really does seem wrong to me to make an ajax call for child pages (plus loading the children into the DOM) just to get those action buttons to show - what do you think Ryan?

**Comment by eladnova** [comment]
+1 for hover by default

**Comment by NicoKnoll** [comment]
I think i already told you guys that I think it should be hover by default in a forum topic. So +1 for this :)

**Comment by eladnova** [comment]
@NicoKnoll Yep - Strong support for this as well a having 'View' links trigger a new window/tab

**Comment by teppokoivula** [comment]
The feature suggestion is valid, but this (a loosely related, closed issue) might not be the best place to discuss it. How 'bout opening a new issue? :)

**Comment by ryancramerdesign** [comment]
I like the hover by default in AdminThemeReno, but not so much in AdminThemeDefault. The action links are light enough in AdminThemeReno that I think it works without being too distracting. Whereas if I copy the same effect to AdminThemeDefault, it's really distracting and annoying. That got me thinking that may it just needed a little delay and fade/smoothness to it so that it didn't feel so abrasive. If you guys check the latest commit, it contains an update that enables it. But you'll have to paste this into your /site/config.php file and do a Modules > Refresh. 
`````````````````
/**
 * PageList default settings
 * 
 * Note that 'limit' and 'speed' can also be overridden in the ProcessPageList module settings.
 * The 'useHoverActions' are currently only known compatible with AdminThemeDefault.
 * 
 * #property int limit Number of items to show per pagination (default=50)
 * #property int speed Animation speed in ms for opening/closing lists (default=200)
 * #property int useHoverActions Show page actions when page is hovered? 1=Yes, 0=No (default)
 * #property int hoverActionDelay Delay in ms between hovering a page and showing the actions (default=250)
 * #property int hoverActionFade Time in ms to spend fading in or out the actions (default=150)
 *      
 * @var array
 *      
 */
$config->pageList = array(
        'limit' => 50,
        'speed' => 200,
        'useHoverActions' => true,
        'hoverActionDelay' => 250,
        'hoverActionFade' => 150
);
`````````````
The key property above is 'useHoverActions'. If most prefer how this works, I'd be fine with making it the default behavior. However, note that this doesn't work with AdminThemeReno, since that is already using a css-only method to enable this behavior.

**Comment by ryancramerdesign** [comment]
You can also configure the above in Setup > Config, if you've got the ProcessWireConfig module installed. The new pageList property will appear there automatically.

**Comment by adrianbj** [comment]
Thanks Ryan - just my two cents, but I think the hover links need to be triggered on the entire line, not just over the title of the page. The way you have it, I need to hover the title, wait for the links to show, then move the mouse over the links. When it's triggered on the entire line, you can hover right where the edit button will be which makes it substantially quicker.

Also, I use the same functionality on ListerPro with this:
```
tr.open .actions{display:none !important}
td:hover .actions{display:inline !important;-webkit-transition-delay:.25s;transition-delay:.25s}
```

Not sure if you'd be willing to include the functionality there also?

**Comment by ryancramerdesign** [comment]
Adrian, that gets to at least part of what I'm trying to solve here: the distraction of things appearing when I'm not intending to hover anything. For instance in AdminThemeReno, I might just be scrolling down the page, and links appear even though my mouse is in nothing but whitespace. This is distracting/annoying because it's making me look at it, even though it's got nothing to do with what I'm trying to do. It's not too bad in AdminThemeReno because the links are on the light end of the scale, but it's also something that needs to be resolved. 

I do understand what you mean about wanting to approximate your mouse position where the edit link will appear though. Perhaps the hover area could be extended out 50 pixels or so to the right to at least include some of the whitespace where the actions might appear. I'll test that out.

**Comment by ryancramerdesign** [comment]
Btw, I would take whatever those pageList settings are there and make Lister inherit them too. That's why they are in $config now rather than in the ProcessPageList module config. The transition-delay options don't in this instance, at least not on my computer. I get the same result regardless of how long of a delay I specify. I'm guessing it's because its an inline element. In Lister the hover-actions are more problematic in PageList because they change the width of the column when they appear, and then change it back when they disappear, so I might have to force them to go underneath the title. It's also a problem with the click actions, but somehow seems more expected with a click.

**Comment by ryancramerdesign** [comment]
I tried out enlarging the width of the hover area to include the links, but just not happy with that. It's still too ambiguous for me, hovering whitespace and having stuff appear. If others like that though, maybe it's just a matter of more config options. On the whole I'm just not a fan of any hover-to-show-actions behavior, so just trying to accommodate the request while also finding something I can live with. I'll come back to this a little later, but if I can't find something I'm totally happy with, I don't mind just making it configurable enough to the point where people can tweak it to however they like it best.

**Comment by adrianbj** [comment]
Thanks for testing out - I think making the hover area width configurable might be nice.

I understand your dislike with the hover actions in general. As I mentioned above - I am not necessarily a huge fan of it myself, but it seems like the only solution to prevent the need for the ajax call to children, just to be able to edit a page.

**Comment by adrianbj** [comment]
Just noticed a small inconvenience with the new hover functionality. If you use move > trash it opens up the trash and before the empty action was automatically available because trash was open. Now it's not and you have to mouseover "Trash" to get it to be visible.

**Comment by mike-anthony** [comment]
Hi Ryan - this doesn't appear to be working for me. Perhaps I'm doing something wrong. I upgraded my local-install from .25 to .26, added in the config array, refreshed modules, but no luck. I see that the config array is being passed to the JS config and that the most-recent ProcessPageList script is being run, but when I hover over a title in the Page List, only the tooltip appears...

What have I missed?
