### ISSUE TITLE
Should Lister column labels use template context field labels?

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1070]
Not sure if there are any complications to this, but would make things cleaner for me. At the moment they show the label from the main settings for the field, rather than from the template context settings which can be confusing for the user.

**Comment by LostKobrakai** [comment]
I often reuse integer fields in various contexts, so I think it would be better to use the context ones if provided.

**Comment by ryancramerdesign** [comment]
A Lister table can contain rows from pages using various different templates. Since the table headings are applicable to all pages in the table, it has to use the field labels rather than template/field context labels. We might be able to make an exception in ListerPro though, assuming the configuration has a single defined template that cannot be changed... but that's a topic for the ListerPro board. I'll look into it.

**Comment by adrianbj** [comment]
Thanks - I would like to see the exception in Lister Pro when limited to a single defined template, which is often the case (I think) with custom listers.
