### ISSUE TITLE
Undefined offset notice in Modules.php (updateModuleFlags)

### ISSUE THREAD

**Issue by kongondo** [ryancramerdesign/ProcessWire#1084]
Example notices I get on a fresh install of PHP dev version 2.5.25 on first login.
Notice: Undefined offset: 160 in F:\xampp\htdocs\k.pw.temp\wire\core\Modules.php on line 2992
Notice: Undefined offset: 161 in F:\xampp\htdocs\k.pw.temp\wire\core\Modules.php on line 2992

**Comment by ryancramerdesign** [comment]
I'm not seeing that error here, and technically can't see how it's occurring since all the flags are populated during boot up. But I'm adding an extra check in there to avoid the error for your case, and that'll be in today's commits. However, I'm still unsure how/why it's occurring, so if any more details become apparent please let me know. Thanks.

**Comment by isellsoap** [comment]
@kongondo Can this issue be closed?

**Comment by kongondo** [comment]
Yes, thanks
