### ISSUE TITLE
Nowrap for filesize

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1099]
It would be nice if the file size would not wrap between number and unit. It should be always clearer, if both flow to the next line together. My typography studies even told me, that between number and unit there should be a thinner non-wrapping space than the default space, but that's the optimal case.

![screenshot 2015-04-15 08 20 33](https://cloud.githubusercontent.com/assets/2489835/7153199/6926c034-e348-11e4-86fc-1b0c82c04ab9.png)

**Comment by ryancramerdesign** [comment]
I haven't seen it wrap like that before, but you are right it should have an `&nbsp;` between the number and unit to prevent that sort of wrap. That's also true about the thinner space here, but since it's got to be non-breaking, we'd end up having to do it with margins/padding and judgment calls... for this case I think the non-breaking space will fit the bill.

**Comment by ryancramerdesign** [comment]
I've updated this so it'll appear in this week's commits (likely today).

**Comment by LostKobrakai** [comment]
Yeah, I'm with you. Subtle typography isn't the strong point of the web and paddings/margins are really overkill most of the times.
