### ISSUE TITLE
Form fields allow dashes in their names

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1101]
Ryan I think we should disallow dashed in field names:
https://processwire.com/talk/topic/9683-wireupload-bug-found/#entry93138

**Comment by ryancramerdesign** [comment]
Currently dashes aren't allowed in field names. Field names support only _a-zA-Z0-9. If given anything other than that, it gets converted to an underscore. In the URL you linked to, he's giving it form-field, but ProcessWire actually uses it as form_field. In that URL you liked to, it looks like he's actually just referring to usage with WireUpload, rather than with PW fields, but the field name requirements are still the same with WireUpload, since it uses the same $sanitizer->fieldName().

**Comment by Da-Fecto** [comment]
Somehow I thought this was in a 'ProcessWire' context, but I see now it's 'custom' code that is making the 'error'. Sorry for posting....

**Comment by isellsoap** [comment]
@Da-Fecto Can you please close this issue? Thank you!
