### ISSUE TITLE
PageTable: Required fields are not checked

### ISSUE THREAD

**Issue by FlipZoomMedia** [ryancramerdesign/ProcessWire#1121]
I have defined in a template all fields as "required", but if I in the modal window and click "publish", the modal window will be closed. It is not checked whether required fields have been filled.

**Comment by ryancramerdesign** [comment]
If the page was unpublished, then it shouldn't let you publish it without filling in the fields. However, the window will still close, but the page should remain unpublished if the requirements weren't met. Without looking at the code directly, I recall that the buttons are basically close window actions, so the saving happens at the same time the window is already closing. Though I can revisit this later in the future to make it wait around for a potential error response before closing the window (which is what we do in FormBuilder's modal edit).

**Comment by LostKobrakai** [comment]
You could also set the pagefield to not close the modal automatically.

**Comment by ryancramerdesign** [comment]
That's a good point, that is a way to ensure any errors are visible. @FlipZoomMedia this is a configurable field setting available with FieldtypePageTable fields on the Input tab.

**Comment by thetuningspoon** [comment]
Ryan, 
What did you mean by this: 

"Though I can revisit this later in the future to make it wait around for a potential error response before closing the window (which is what we do in ListerPro's modal edit)."

When saving a ListerPro modal in PW 2.6.10 dev/Lister 1.0.5 I briefly see the errors appear and then the modal closes anyway. Is this the expected behavior or is it something with my particular install that is causing this?

PW is totally unbelievably awesome and I probably sounding like a whiner saying this, but the unorthodox way validation is handled on edit pages in PW has been a pain point for my clients on recent projects. Is there a way the page editor could be made a bit "smarter" so that instead of saving a page no matter what, it first checks for validation and doesn't actually process the save or do any redirect until everything passes muster? That way you could just repopulate the inputs from $_POST and report errors back to the user, and processSaveRedirect() wouldn't even get called unless everything was valid. Of course the modal would also have to be reworked to close on save and not before.

**Comment by isellsoap** [comment]
Didn’t saw this issue before opening #1378. This issue is a paint point for me, too. Would be awesome to see a fix for this.

**Comment by isellsoap** [comment]
Maybe related to https://github.com/ryancramerdesign/ProcessWire/issues/1743.

**Comment by isellsoap** [comment]
@FlipZoomMedia I think that this issue is gone now. You can now specify the "required field actions" in the "Advanced" tab of a template, and the behavior does also work in PageTable items.
