### ISSUE TITLE
API add image not respecting maxFiles setting

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1122]
I know that using the API often doesn't check various settings, but I wonder if this is one that should be enforced because it can result in subsequent data loss.

If multiple images are added to a single image field (maxFiles = 1), but then later someone goes to add an additional image to this field via the GUI, all the previously added images will be deleted.

I thought that turning on output formatting might have enforced the maxFiles limit, but the only thing that did was make it impossible to use $page->image->add($url), and rather instead have to use $page->image = $url;

You could argue that scripts using the API to upload should check the maxFiles setting and replace the an existing image if the field is empty, but then I think you might also need to check the Overwrite existing files option as well - not sure, maybe this is enforced, I haven't checked.

A little background reading on why I started noticing and thinking about this:
https://processwire.com/talk/topic/4614-youtube-and-vimeo-thumbnail-grabber/?p=92569 onwards.

**Comment by ryancramerdesign** [comment]
Page objects should not have their values modified when outputFormatting is on. If you do modify/set a page field value with output formatting on, it is considered corrupted. So be careful not to set values to pages that are in an output state. PW can detect and throw an exception for most, but not all cases, where you might attempt to set and save a value in output formatting state. So it's a good idea just to make sure you aren't manipulating pages that are setup for output. 

From the API side, all file fields are multi-file fields. maxFiles is a way to control what the field outputs when in an output formatting state. It is also used by InputfieldFile to impose these at input time. Regardless of Fieldtype, settings assigned from the API side are not considered user input, so you should always validate what you set. In this case, since maxFiles is significant to your use, you'll want to validate for that. 

From the Fieldtype side, all file fields must behave in exactly the same way regardless of what output or input level settings are applied to it. This ensures that the same API file manipulation code works on any file field, regardless of settings. If your needs dictate always limiting to just one file, you may want to call `$page->image->deleteAll();` before adding files to the field to ensure that it is starting in the blank state that you want.

**Comment by adrianbj** [comment]
Thanks for the detailed explanation. I do understand that they are multi-file file fields and MaxFiles is just a way to control this with output formatting on. The issue in this case is that we are talking about a module so I need to check the MaxFiles and Overwrite Existing options because I don't have control over the images field that the dev assigns to be used in the module. I can certainly add these checks, but just thought that because images/files uploaded via the API maybe be lost if the field is later edited via the admin it might be something that the core should check for.

Pete's desired behavior is actually opposite to how the admin would work anyway - he wants existing images to be left alone - essentially resulting in a locked field that can't be added to by the module, but can be via the admin. Bit of a dilemma :)
