### ISSUE TITLE
WireArray explode(array) does not work with "parent" selector

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1129]
Using this returns an array with the value of `null` for the title:
```php
$a = $pagearray->explode(array("parent.title"));
// $a = array( "parent.title" => null );
```

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. I'm getting correctly populated titles. Any other factors you can think of? Here's the test I'm using: 
``````````
$a = $pages->find("template=basic-page");
print_r($a->explode(array('parent.title')));
``````````
Result:
``````````
Array
(
    [0] => Array
        (
            [parent.title] => About Synbio Products
        )
)
````````

**Comment by LostKobrakai** [comment]
Not exactly. I just updated to the latest dev to remove anything I might have messed with in the core files.

```php
$jobs = $pages->find("has_parent=$root, template=bp_job")->slice(0, 2);

var_dump($jobs->explode("parent.title"));
foreach($jobs as $job){
	var_dump($job->get("parent.title"));
	var_dump($job->parent("title") instanceof NullPage);
	var_dump($job->parent()->title);
}
```
This gives me this results
```php
array (size=2)
  0 => null
  1 => null

null
boolean true
string 'Everywear SS 2015' (length=17)

null
boolean true
string 'Everywear SS 2015' (length=17)
```
While the page has lots of modules installed there's not a single hook there, which I would suggest to be responsible for this.

I've also just tried it on a fresh installation, where I just added to new pages. Same code – same results.

**Comment by ryancramerdesign** [comment]
I think you must have output formatting enabled for your $page. You can't do a `$page->get('field.subfield')` when output formatting is on, for security reasons. That's my best guess as to why your explode("parent.title") and get("parent.title") are returning nulls. Should we disable the security that blocks use of directly referencing subfields from get() when output formatting is on? Maybe... it just makes me a little nervous, which is why I made it only work in output formatting=off state. I don't have any examples of something exploitable through here, but just know it opens a lot of doors. I sometimes see people taking something direct from user input and sending it to a $page->get() method, which is not good. They shouldn't do that, but it does make me think that $page->get() shouldn't be an open door to any property of any object. 

As for this:
```````
 var_dump($job->parent("title") instanceof NullPage);
```````
The parent() method expects a page selector, not a field name. Your parent page is not named "title" so it's correctly returning a NullPage().

**Comment by LostKobrakai** [comment]
I'm not sure about the security issues you're talking, but I think not getting values of the parent of a page could possibly lead to confusion of people using the function. Especially as it does not throw any warnings or errors about it.
