### ISSUE TITLE
"Add new" Template only visible to superusers

### ISSUE THREAD

**Issue by phlppschrr** [ryancramerdesign/ProcessWire#1144]
I want two different templates listed in the "Add new" dropdown, but only one is shown to users with the editor role. The admin users can see and add both templates in the dropdown. 

The template not showing to editors has a parent with access restrictions, but the editor role has all needed rights. Adding pages with this template in the pagetree works also for "editor" users without problems.

I tested this only in the latest dev.

**Comment by ryancramerdesign** [comment]
The 'add new' dropdown can't detect all possible scenarios (at least not quickly), so in some cases you'll have to help it along if you want it to show something specific. Double check that your family settings on both the template and the parent are clear about what is allowed. With regard to access control, you may need to specifically enable access control for the template since the 'add new' box doesn't traverse the page tree to determine this.

**Comment by phlppschrr** [comment]
Thanks, enabling access control for the template helped. 

Maybe this should be mentioned in the "Conditions required for this to work" field? 
Btw, I think condition "3. There may only be one instance of a page using the parent template in your system." is no longer true.
