### ISSUE TITLE
2.6 master haccess and index

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1155]
...deliver outdated info:
 @version 2.5
 @indexVersion 250
Is this intended?

**Comment by Da-Fecto** [comment]
Yep, 2.6 needs at least those 2.5 files. I don't think they're changed since 2.5.

**Comment by tbba** [comment]
At least the index.php had very recent changes, according to the history here on GIT, correct?

**Comment by ryancramerdesign** [comment]
That's correct, there have been updates to index.php, but not to .htaccess.
I don't like to bump the version number in the .htaccess unless there's
been an actual change, since PW uses a separate .htaccess version number
(currently 250, which corresponds with the version it was introduced with:
2.5.0). If I bump that version number in the .htaccess, PW will tell people
to upgrade it when they don't need to.
