### ISSUE TITLE
Page::matches can't handle or-groups

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1162]
While pagefields can use or-groups in selectors for getting selectable pages, it then throws an error if one tries to save the selected page, as the validation fails.

**Comment by ryancramerdesign** [comment]
OR-groups (and sub-selectors) are only supported by PageFinder
($pages->find()). Several things that PageFinder does involve joining and
comparing large sets that simply aren't accessible to in-memory selectors.

**Comment by LostKobrakai** [comment]
Then it would be nice if the pagefield would at least warn the user, as this looks like it would work just until you try to save a page. Shouldn't be to difficult to just look for parenthesis in the selector value.

**Comment by ryancramerdesign** [comment]
It's more complicated than just looking for parenthesis. They are different selector types, so there's plenty of things you can do with DB driven selectors that you can't with memory selectors, which are differentiated in the Selectors doc page. Ideally everything supported by DB selectors would also be supported by memory selectors, but in reality the DB selectors have access to absolutely everything in the site, while the memory selectors only have access to what's in the group of pages present in the WireArray… or in the case of Page::matches(), only what's present on that page. But I understand what you are saying, and it would be nice to have a warning system when you attempt to use a full featured DB selector in a context where it can't be used. I'm not sure how best to go about that but will keep thinking about it.

**Comment by LostKobrakai** [comment]
Yeah, but warning for parentheses would at least catch the obvious ones. Or we'd need more extensive docs on the topic. It's the same issue for pagination, where people often fall over the difference between Pages::find, Page::find and PageArray::find.

**Comment by ryancramerdesign** [comment]
There are other legitimate uses for parenthesis in selectors, like for a value you may want to match. But regardless, I don't want the overhead of having the system check all aspects of the usage every time a selector is parsed. If it's looking for OR-groups when you can't use them, then there's going to be an expectation that it's also looking for anything else you might not be able to use, and I don't want to go there. Not only is it overhead, but it's getting classes that know nothing about these things involved in something that's exclusive to the PageFinder class. I'd rather let this stuff be covered by the documentation, where it already is. One isn't going to even know how to use OR-groups if they don't read the documentation on it, and the documentation has a disclaimer stating where they can be used. Likewise for all of the selector features exclusive to PageFinder.

**Comment by LostKobrakai** [comment]
I just found an example that certainly isn't documented as explicitly as OR groups. In-memory selectors don't handle strtotime values when the selector includes a datefield.

**Comment by ryancramerdesign** [comment]
That's correct, because that conversion of date strings to timestamps is
part of a Fieldtype module (FieldtypeDatetime). Fieldtypes provide the
logic for pulling stuff out of the database–they construct the query
specific to their own tables. Part of that SQL query construction involves
sanitizing and sometimes manipulating the value that gets sent to the
database SELECT query. In the case of FieldtypeDatetime that means
converting a timestamp or date string to a MySQL recognized iso-8601
string.

Fieldtypes play no part in other selector filtering that you may do on your
own outside of DB operations. In-memory selectors work the same everywhere,
regardless of what kind of data types you are dealing with, and they have
no knowledge of things like Fieldtypes. However, you really shouldn't be
doing much in the way of in-memory find/filtering for pages, because it
indicates that you've pulled stuff out of the database that you didn't need
to. I almost never use in-memory selector operations with pages because
it's far more efficient to let the database perform these operations so
that you aren't loading pages unnecessarily. In memory find/filtering is
useful on other types like fields and modules because they are always
loaded into memory ahead of time.

**Comment by LostKobrakai** [comment]
I did find this out, too, by looking a the files, because I wanted to know why it doesn't work. I don't use in memory selectors very often as well, which is why I didn't fall over this before. In this case I actually need the whole bunch of pages that I get from the db, but show them in different tables depending on if they are in the past or in the future (and some other criteria).

I think the in-memory things do not need more functionality, but I'd really like a few lines in the selector docs about the differences to database queries. With some fancy grouping (or groups / subselectors) one does quite easily suspect that they could be not supported, but the date part really though me off at first.
