### ISSUE TITLE
InputfieldFloat not working with html 5 number input and non US locale

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1175]
I don't know why exactly, but no matter which format I set the value of an InputfieldFloat (I use it in a custom inputfield, but it's the same for native fields) it's always converted back to a float. Inputs of type number cannot handle localized floats, therefore I needed to add this to /wire/core/Inputfield.php. 

```php
	public function getAttributesString(array $attributes = null) {

		…
		foreach($attributes as $attr => $value) {

			…

			// convert floats for numberfields to right format
			if(is_float($value) && $this->type == "number"){
				$precision = $this->precision; 
				if(is_null($precision)) $precision = FieldtypeFloat::getPrecision($value); 
				$value = number_format($value, $precision, '.', '');
			}

			$str .= "$attr=\"" . htmlspecialchars($value, ENT_QUOTES, "UTF-8") . '" ';
		}

		return trim($str); 
	}
```

**Comment by LostKobrakai** [comment]
This is still an issue. A more flexible alternative without the need for a precision is this:
```php
  // the number inputtype does handle localization in the browser
  if($this->attr('type') == "number" && is_float($value)){
    $decimal = localeconv()["decimal_point"];
    if(strpos("$value", $decimal) !== false){
      $broken_number = explode($decimal, $value, 2);
      if(count($broken_number) == 2)
        $value = number_format($broken_number[0], 0, '.', '').".".number_format($broken_number[1], 0, '.', '');
    }
  }
```

**Comment by LostKobrakai** [comment]
@ryancramerdesign This is still not working in the current dev. This makes usage of html5 number fields impossible on a fresh installation with an language pack, where the decimal point is not a period.

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've applied something similar to your fix. Though want to avoid type-specific stuff like this in the main Inputfield class, so put it in InputfieldFloat instead where it's applicable. It seems to resolve the issue from here, but I'm not sure I can adequately test it either because I can't get the HTML5 number type to recognize anything other than "." as a decimal, despite using the German language pack and locale. Must be something I have to change in Chrome instead, but I haven't been able to figure that out yet. Hopefully it works in a German version of Chrome too, but let me know if you find it doesn't.

**Comment by LostKobrakai** [comment]
Seems to work from here, too.
