### ISSUE TITLE
When subselector fails to match anything, the main selector looks for empty results - totally different thing what was wanted

### ISSUE THREAD

**Issue by apeisa** [ryancramerdesign/ProcessWire#1188]
Easy way to reproduce:

- install blog profile
- create new post without any tags
- run selector: template=post, tags=[title=foobar]

What you would except: zero results, since there isn't any tags with title foobar.

What you get instead: all the posts that don't have any tags at all.

Possible solution: if any subquery fails to find any results, then the whole selector should also return zero results. I have not yet find any use case where you would actually want to find empty results when subquery fails, but I am not 100% sure if solution can be this straightforward?

Important note: everything works fine if you add .id after the field you are running subselector against. So this template=post, tags.id=[title=foobar] returns zero results as expected.

I have also good test case created at lightning.pw, if access is needed (although this is pretty trivial to reproduce in any site).

**Comment by apeisa** [comment]
Running latest and greatest (2.6.0).

**Comment by LostKobrakai** [comment]
Good to know. I've rewritten a few selectors from subselectors to @ selectors because of this a few days ago.

**Comment by ryancramerdesign** [comment]
If the result of "title=foobar" is nothing, then it's asking the "tags=" part to match pages that have nothing for that field. I am probably just too close to it, but the current result is the behavior I would expect it to produce because there's no subfield specified, the result of "title=foobar" is nothing, and it's in turn asking the "tags=" part to match pages with nothing. Without a subfield specified, that leaves the Fieldtype to determine what "nothing" matches. In the case of FieldtypePage, "nothing" is equivalent to "field.count=0". 

I think the behavior change you are suggesting likely makes sense here, but not 100% confident that we should change it. I also can't yet think of a case where I'd use the existing behavior. But I also can't envision all possible use cases, and who's to say sometime out there isn't relying on the current behavior. I think this is something we'll experiment with on the dev branch and let it marinate there to make sure it doesn't cause any unintended side effects. 

Btw, I'm assuming the "tags=[title=foobar]" was just a simplified example? Because this wouldn't be a good use for a subselector, when you could just do "tags.title=foobar" much more efficiently. But you already know this. :)

**Comment by LostKobrakai** [comment]
I've a little more obvious example:
`template=job, @trainers.trainer=$user, @trainers.status<10` and 
`template=job, @trainers.trainer=$user, @trainers.status=12`

could be:
`template=job, trainers=[trainer=$user, (status<10), (status=12)]`

In this case the status's IDs are automatically generated by the options fieldtype (which doesn't let me reassign id's on my own even if it was never used :triumph:), but I can certainly see this happening without a situation like mine.

**Comment by teppokoivula** [comment]
Assuming that "abc=[xyz=123]" in it's entirety is the "subquery" here, not just the "[...]" part, "if any subquery fails to find any results, then the whole selector should also return zero results" makes sense. If subquery is only the part between square brackets, that sounds like it could break negation operator, unless I'm overthinking this somehow :)

Anyway, what @apeisa described above is exactly what I was expecting too; "template=post, tags=[title=foobar]" is clearly asking for all posts with a tag that matches "title=foobar", and this returning all posts with no tags would be a total surprise to me. I'm not too familiar with subqueries in this context, though, so perhaps it does makes sense from a strictly technical point of view.

In terms of (rather weird pseudo-)SQL, I'd imagine subqueries working (logically, of course not literally) a bit like this: `SELECT * FROM pages WHERE template = "post" AND tags HAS (SELECT id FROM tags WHERE title = "foobar")`. Current behaviour is more like this: `SELECT * FROM pages WHERE template = "post" AND tags HAS (SELECT id FROM tags WHERE title = "foobar") OR tags IS NULL.`

Or, in other words, I was expecting INNER JOIN and got LEFT JOIN, if that makes any more sense :)

**Comment by ryancramerdesign** [comment]
Thanks for the comments. I agree with what you are saying, but also have to dwell on this a bit more because it's changing a selector behavior that's not technically incorrect relative to what a subselector actually is. I can see from this conversation that a subselector is thought to be something a little different from what it is. It is not a subquery or a join, nor does it use either. A selector is a string, and a subselector is string operation that merges the results of one selector into another. It's not a database operation. It simply replaces the result of the subselector with string value of the result. It's the same thing as if you did this:
```````
$tags = $pages->find("title=foobar");
$posts = $pages->find("template=post, tags=$tags"); 
```````
Whether using the code above or the equivalent subselector, you would want to use a "tags.id" rather than "tags" to force a non-match if the first selector failed to match anything. So while I do agree that the feature requested in this issue report makes a lot of sense, it does change the meaning of what a subselector is, which makes unintended side effects a concern. Hopefully not the case here, but something that needs to marinate and tested on the dev branch to be certain.

**Comment by apeisa** [comment]
Yep, it was simplified example. But I think we have already three different developers hitting head on the wall because of this - it's very confusing behavior currently and should be documented clearly. (.id notation is mentioned here https://processwire.com/blog/posts/processwire-2.5-changelog/, but missing from here: https://processwire.com/api/selectors/#sub-selectors Actually that example selector in documentation is actually a great example of dangers of current behavior: 

$items = $pages->find("template=product, company=[locations>5, locations.title%=Finland]");

If subselectors would find 0 results, then the actual selector would return all the products, where there isn't any company chosen for the product...

Subselectors can only be used against page fields (and likes), since subselectors are selectors also and return id:s. So in my (simplified) thinking if subselector fails to find anything, then the whole selector should also return 0 results.

I understand Ryan's concern, but the danger is that it most of the time works without .id and it's natural to do. Also when developing and testing, you tend to test with subselectors that you know will match, so the problem will probably occur later.

So if .id will be required in subselectors, let's fix the documentation in that case :)

**Comment by ryancramerdesign** [comment]
After dwelling on it a bit, I still can't think of a good use case for keeping the current behavior, so I've updated the PageFinder to automatically append a ".id" to the field name(s) when 0 results are returned from the subselector. This will appear in this week's commits to the dev branch. If it turns out to create issues with any intended behavior (which doesn't seem likely) I'm sure we'll hear about it, but to be safe I'll let this one marinate on the dev branch for a bit before migrating to master.

**Comment by apeisa** [comment]
Great news, thanks Ryan. I'll update if this has any undesired side effects!
