### ISSUE TITLE
Priority setting in hooks not respected

### ISSUE THREAD

**Issue by wanze** [ryancramerdesign/ProcessWire#1218]
I'm trying to use ProCache together with my TemplateEngineFactory module. My module hooks after `Page::render()` and sets `$event->return` to the rendered output of a template engine. The problem: ProCache's hook after `Page::render()` is called before my hook resulting in blank cached pages. I tried to solve it with setting priorites but I had no luck so far. Here's what I noticed:

* Setting a priority of a hook after `Page::render()` to lower than 100 (default value) has strange effects. It seems like the hooked method is executed before `Page::render()` gets executed.
* Setting a higher priority does not have any effect on the order of the executed hooks

For example: I tried to increase the priority of the ProCache hook like this:
```php 
$this->addHookAfter('Page::render', $this, 'hookPageRender', array('priority' => 120)); 
```
But `ProCache::hookPageRender()` is still executed before my hook

**Comment by ryancramerdesign** [comment]
@wanze you are right the priority system does not work, at least when there are a combination of local hooks and static hooks. I actually have had a @todo in the Wire.php getHooks() method about this since the beginning, because the priority gets lost after array_merge() of local and static hooks. But the priority issue has just never cropped up before now. I'll focus on getting this working properly next week. Thanks.

**Comment by netcarver** [comment]
Ah, that would be great Ryan. I was hit by this with one of my modules too though I can't remember reporting it.

**Comment by wanze** [comment]
@ryancramerdesign Thanks for the fix, priorities are working! :) There's still one issue though. If you hook `Page::render()` with a priority lower than `100`, it's not working. I think the issue is that `Page::render()` itself is added with a hook (priority = 100?). Maybe added methods with hooks must always be executed prior to before/after hooks.
I've solved my problem by increasing the priority of the hook added by ProCache, like shown in my first post. Could you maybe add this addition to ProCache to make sure that the module kicks in at the very last of all hooks attached to `Page::render()`?

Thanks!

**Comment by ryancramerdesign** [comment]
For a method added by a hook (such as Page::render) there really isn't any possible distinction between before and after, because it is nothing but one or more hooks in a chain. There is no original method to hook before or after … (but actually there is in this case, which I'll explain below). So I understand what you are saying, in that there's no way to insert something between two hooks that both have the same priority (100). I will bump up the priority level that ProCache uses (to something like 200) so that it's easy to hook in-between Page::render and ProCache. But there actually is another way that you can do it: hook after PageRender::renderPage (which is the handler for Page::render). That method call comes between Page::render and anything hooking after it. So you could do this:
`````````
wire()->addHookAfter('PageRender::renderPage', function($event) {
  $event = $event->arguments(0); // pull event given to renderPage…
  $event->return .= "Hello World"; // …and use or modify it. 
  // anything hooking after Page::render will get called after this
});
````````

**Comment by wanze** [comment]
Thanks for your explanation ryan, that's fine for me. I'll close this issue, it's fixed :+1:
