### ISSUE TITLE
Changing language page names in saveReady hook doesn't get saved

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1219]
I have a hook on Pages::saveReady where I change page names of alternative languages. It doesn't save them in alternatives languages. It works only for the default page name.

```
$page->setLanguageValue($lang, "name", $langPageName . $fileExt);
```

Even $page->isChanged("name$lang->id") is returning true but it's doesn't get saved.

**Comment by somatonic** [comment]
Just found that when I use the extra data array on Pages::saveReady it works. 

```
$changes["name$langID"] = $langPageName . $fileExt;
...
$event->return = $changes; 
```

**Comment by ryancramerdesign** [comment]
The function that performs this (in LanguageSupportPageNames) also hooks saveReady, just like you are. So your hook is catching it after it's already bundled the names into the data array. You could set the priority of your hook to number lower than 100, so that it gets executed before the one in LanguageSupportPageNames. But what I would recommend instead is just hooking before Pages::save instead, so that you can catch it before any transformations have taken place. Of course, manipulating the data array like you discovered works just fine too.

**Comment by isellsoap** [comment]
@somatonic This issue doesn’t seem to be a bug, thus I close it. If you think the issue requires additional work to do, please consider reopening it.
