### ISSUE TITLE
Sorting screwed position because of modal.js adding overflow

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1224]
I noticed that the sorting on PageTable entries is bugged with position of the dragged element.

Once you add or edit a entry, then there's a overflow: hidden added, that's ok but after closing the modal, there's overflow: auto, which introduced the problem. I was able to fix it by removing "auto".

parent.jQuery('body').css('overflow', '');

**Comment by ryancramerdesign** [comment]
Thanks, that's a good find. I've been seeing the same thing but wasn't sure how to fix it. Just to confirm, you are talking about this `overflow: auto` ? https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Jquery/JqueryUI/modal.js#L117

I tried changing it as you suggested, and it does indeed seem to fix the problem here too. But wanted to make sure we're talking about the same file.

**Comment by somatonic** [comment]
Yep that's it.

**Comment by isellsoap** [comment]
@somatonic Can this issue be closed?
