### ISSUE TITLE
Allow wireRenderFile() to receive an WireData object of $vars 

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1243]
It really bugs me that I've to isset all those optional variables in wireRenderFile. Now, kinda like the NullPage object, handing a WireData object instead of an array to the function would remove this necessity. The object would then be available through a variable 'injection' or what ever will fit.

**Comment by ryancramerdesign** [comment]
I'm not sure I understand. You should be able to pass whatever kind of data you want to wireRenderFile, including a WireData object. Since you are using it in a context where you may have variables that might not be passed in (making you use isset) you could instead just pass in a [$vars => SomeWireDataObject] and access $vars->someProperty from your file instead.

As for passing in just a WireData object (rather than an array of whatever you choose), and having its properties/values extracted to locally scoped variables, even that would not prevent you from having to isset() to see if the properties were in scope. The result would be no different than if you started with an array.

**Comment by LostKobrakai** [comment]
The idea was just to be able to shorten `wireRenderFile("file", array("injected" => $wireData));` to `wireRenderFile("file", $wireData)`. Accessing `$injected->fieldname` is more hasslefree than `$fieldname`. But maybe the few chars saved isn't worth changing something to the core.
