### ISSUE TITLE
Some precisions needed for 2.6.1 translation

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1249]
Some of my translation notes for 2.6.1. Would appreciate your help. Cheers!

**wire/core/Fields.php**

Not sure if these should be translated:
- 489:page-by-page
- 509:single-query

**wire/modules/Fieldtype/FieldtypeComments/CommentForm.php**

Not sure if these should be translated:
- 140:h3

**wire/modules/Process/ProcessPageList/ProcessPageList.module**

Don't understand what this means or is supposed to do, might be rephrased
- No templates specified so 'include=hidden' is max allowed include mode

**Comment by ryancramerdesign** [comment]
> 489:page-by-page
> 509:single-query

These are just used for a $this->message() call output, so they can be translated. 

> 140:h3

Admittedly this is using the translation engine for something different than usual, but this just lets you specify a different headline level if you want to. For the purposes of creating a public translation, this should just be left as 'h3'. I have a case where I needed a different headline level, and this was just the quickest way to accomplish it. 

> No templates specified so 'include=hidden' is max allowed include mode

This is actually in ProcessPageLister.module (rather than ProcessPageList.module). It's informing the user that a limitation is being placed on the results, and some pages may be excluded. You are right it's not particularly clear, so I'll think if there's a way to rephrase it better.

**Comment by plauclair** [comment]
Closing this!
