### ISSUE TITLE
$page->add(...) with values array and multilanguage fields

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1263]
I'm trying $page->add() for the first time.

I can't get language values getting saved though status$langID works, but not for values like the "autor" or "auflage"

Array entry

```
        (
            [title] => Altermatt, Urs: Katholizismus und Antisemitismus. Mentalitäten, Kontinuitäten, Ambivalenzen.
            [autor] => Altermatt, Urs
            [autor1023] => 
            [autor1024] => 
            [body] => Zur Kulturgeschichte der
Schweiz 1918 - 1945
            [verlag] => Huber Verlag, Frauenfeld/Stuttgart
            [verlag1023] => 
            [verlag1024] => 
            [year] => 1999
            [auflage] => 1. Auflage
            [auflage1023] => 1ère édition
            [auflage1024] => 1st edition
            [select_buch_category] => 2423
            [status1023] => 1
            [status1024] => 1
        )
```

**Comment by somatonic** [comment]
Ah, "fieldname$langID" doesn't work anyway but would be nice to do something like this.

Maybe "fieldname.data$langID", cause now I need to build a "complex" script where this would be a one-liner. Or is it somehow possible?

**Comment by ryancramerdesign** [comment]
For true multi-language text fields, they are supposed to be an object value of type LanguagesPageFieldValue, So the "name1234" syntax that you can use with 'name' and 'status' doesn't apply to anything other than name and status. The reason you can do that with name and status is because they are system fields that map directly to DB columns of the same name. 

You could set them by passing the following to the $pages->add $values argument:

`````````
$auflage = new LanguagesPageFieldValue();
$auflage->setLanguageValue('default', '1. Auflage');
$auflage->setLanguageValue('de', '1ère édition');
$auflage->setLanguageValue('en', '1st edition');

$values = array(
  'auflage' => $auflage,
);

$newPage = $pages->add($template, $parent, $name, $values);
``````````
