### ISSUE TITLE
do you want to leave page - alert

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1265]
The "do you want to leave page" alert now appears on every page, including the login page.
Anyone else seeing this? -  I have it on all pw domains out of the sudden. (latest pw 2.6.6.)

**Comment by tbba** [comment]
this is only in SAFARI (Yosemite)

**Comment by ryancramerdesign** [comment]
Thanks, I was able to duplicate that too. It looks like Safari throws the confirm box even if we return a blank value telling it not to. I found I was able to get around it by not returning anything at all, i.e. `return;` rather than `return '';` and that seemed to fix it, while still working in other browsers. Should is now on the dev branch.

**Comment by tbba** [comment]
Yes, this fixed it - thank you very much!!
