### ISSUE TITLE
$config->pageEdit['confirm'] = false Doesn't disable Form Save Reminder

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1289]
I am experiencing some issues with the new form save reminder in the core (false positives on some third party fields, and some odd cases I haven't been able to pin down when using ListerPro with modal windows), so I wanted to turn it off. I added $config->pageEdit['confirm'] = false; to my /site/config.php, but am still getting the pop-up reminders.

**Comment by ryancramerdesign** [comment]
The issue with ListerPro modals and confirm boxes should be fixed in the most recent version of ListerPro and PW dev. 

As for disabling it, I think the issue might be the way you are turning it off, because what you mentioned there is indirect assignment, which doesn't get populated to $config. Was that one of my examples? If so sorry, as it's incorrect. You would need to do this:
``````
$config->pageEdit = array('confirm' => false);
```````
or this might be better, as it retains any other settings, if present, in $config->pageEdit:
```````
$pageEdit = $config->pageEdit;
$pageEdit['confirm'] = false;
$config->pageEdit = $pageEdit;
```````

**Comment by thetuningspoon** [comment]
Thanks Ryan. $config->pageEdit['confirm'] = false was the example you gave on the blog entry that announced the new reminder functionality.
