### ISSUE TITLE
addable, createable, addableTemplate, isAllowedTemplate confusion

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1303]
Hi Ryan,

I am struggling to get the checks I want and not sure if there is a bug or not. When adding new pages via the API, the addable() method only checks template->noChildren and not template->noParents. The createable method doesn't seem to be available publicly (nor does it seem to be used elsewhere in the core). Looking at ProcessPageAdd.module I see that it uses isAllowedTemplate() but this is also not available publicly. 

I also see that addableTemplate is used in the addable method, but only after the check for superuser, so for superusers this is ignored.

Is there a recommended way to check to see if a page is allowed to be created based on its template family settings that considers noParents and enforces the rules for superusers?

**Comment by ryancramerdesign** [comment]
Adrian, the best method is to analyze the template properties. PW considers different ones depending on the scenario and user (specifically superuser, who is allowed to do some things other users aren't). So there isn't a common API function for this since the different parts of the core that consider it are handling different kinds of scenarios. The template properties I think you'll find useful here are these:

$template->noChildren
$template->childTemplates
$template->noParents
$template->parentTemplates

**Comment by adrianbj** [comment]
Thanks - I have used all those template properties before - I just figured that addable and createable (if it was available) would check all these, but I understand the issue that there are different scenarios that must be considered.
