### ISSUE TITLE
fatal error when updating to the latest 2.6.12 commit.

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1323]
I had this problem: I hope that info helps:

Fatal error: Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'templates_id' (in /Users/…/wire/core/WireDatabasePDO.php line 191) #0 /Users/…/wire/core/WireDatabasePDO.php(191): PDO->exec('ALTER TABLE pro...') #1 /Users/…/site/modules/ProcessChangelog/ProcessChangelogHooks.module(422): WireDatabasePDO->exec('ALTER TABLE pro...') #2 /Users/…/site/modules/ProcessChangelog/ProcessChangelogHooks.module(164): ProcessChangelogHooks->updateDatabaseSchema() #3 /Users/…/wire/core/Modules.php(462): ProcessChangelogHooks->init() #4 /Users/…/wire/core/Modules.php(373): Modules->initModule(Object(ProcessChangelogHooks)) #5 /Users/…/wire/core/ProcessWire.php(338): Modules->triggerInit() #6 [internal function]: Process in /Users/…/index.php on line 253

**Comment by cstevensjr** [comment]
Received the same error

**Comment by adrianbj** [comment]
I just found the same issue - obviously that error is from teppo's Changelog module. As a quick fix, simply comment out lines 422 to 428 of ProcessChangelogHooks.module, reload PW and then you can uncomment those lines again and everything seems to work as expected from then on. 

The same issue also occurs with his LoginHistory module and the same fix takes care of things.

**Comment by ryancramerdesign** [comment]
I can't duplicate the issue here on a fresh install of ProcessChangelog, so whatever the issue is must be with the transition between PW core versions, and the shuffling around of some module info properties in 2.6.12. It looks like ProcessChangelogHook's getting loaded once without being considered 'configurable' and so it's not receiving its schema_version variable (my best guess after looking at the code), so it's attempting to re-apply some DB changes. I've just pushed a potential fix for it, though unable to confirm that this corrects the issue since I can't reproduce locally yet. If one of you is still seeing this issue, could you let me know if the latest commit fixes the issue? (only the /wire/core/Modules.php file changed, if you  don't want to grab the whole core).

**Comment by tbba** [comment]
I can confirm for my installations that the problem is gone (Localhost/MAMP and Live). 
Thank you!!!

**Comment by ryancramerdesign** [comment]
Great! Thanks for testing it out.

**Comment by cstevensjr** [comment]
Additional confirmation that this issue has been fixed, with the latest commit. Thanks
