### ISSUE TITLE
Field visibility dependency "template=" warning

### ISSUE THREAD

**Issue by Rayden** [ryancramerdesign/ProcessWire#1325]
I'm using one template for lists and one for items, both templates contain all the necessary fields.

Then i created news_list, agenda_list, products_list templates using the fieldgroup from list template, and news_item, agenda_item, products_item templates using the fieldgroup from the item template.

In the list template i made a visibility dependecy for my summary field which should not be shown on the product_list template.

So i added "template!=products_list". This seems to work fine, editing the page "Products" using the products_list template it hides te summary field, while at the other two pages ("News" and "Agenda") using the news_list and agenda_list templates the summary field is visible as expected.

As soon i save the page "Products", using the products_list template i get the following warning

Session: Warning: dependency field 'template' is not present in this form. (ProcessPageEdit)

I have advanced and debug mode both set to true in the config.

**Comment by ryancramerdesign** [comment]
I think the issue may be that the "template" field isn't always present in the PageEdit form, like in situations where the Template can't be changed. In order for a dependency to work, the field must be present in the form. The other thing to mention is that you'd want to use the template ID rather than the template name, as template IDs are used for the selectable values.
