### ISSUE TITLE
Breadcrumbs in admin behaves different on latest dev

### ISSUE THREAD

**Issue by kalmarlansmuseum** [ryancramerdesign/ProcessWire#1350]
Clicking on the closest parent when on the last child in the breadcrumbs brings you to the parent page, not the page tree. Clicking on a parent higher up takes you to the tree view. 
ProcessWire 2.6.13 dev

**Comment by ryancramerdesign** [comment]
This is actually an intentional behavior that occurs when one of the parents has more children than the pagination limit for PageList. Basically, it's not going to take you to the PageList (in the breadcrumbs) unless it knows for sure that it'll be able to open that parent in the PageList. When a given parent has a lot of sibling pages (more than your PageList pagination limit), it has no way of knowing what pagination that parent will fall within. So it doesn't attempt to open the PageList, and instead directs the breadcrumb link to the page editor for that parent.

**Comment by kalmarlansmuseum** [comment]
Thanks for clarifying!
