### ISSUE TITLE
editor user can't save pages after update to ProcessWire 2.6.13

### ISSUE THREAD

**Issue by nurkka** [ryancramerdesign/ProcessWire#1356]
After upgrading to 2.6.13 an editor user couldn't save pages anymore. 

Our editor role has the following rights: 

page-delete
page-edit
page-lister
page-move
page-sort
page-view
profile-edit

Every time, the editor user tries to save a page, he gets an "Internal Server Error" (tested in PHP 5.4 and PHP 5.5). The logfile says: 
[...] /page/edit/	Error: Call to a member function attr() on a non-object (line 245 of [...]/wire/core/InputfieldWrapper.php)

This is the function remove($item), with the following code in line 245:
} if($this->getChildByName($item->attr('name')) && $item->parent) {

I rolled the ProcessWire installation back to 2.6.1 and now it works fine again.

BTW: Thanks a lot for the great update/backup feature!

**Comment by ryancramerdesign** [comment]
Thanks for the report @nurkka. I can't seem to duplicate this one here
after setting up the same scenario. I was wondering if you have any 3rd
party modules installed (Modules > Site)? Something is apparently calling
the remove() method with a non-Inputfield. I'm adding some code to that
method so that it'll exit more gracefully if it receives an invalid
argument, and that'll appear in today's commits. But I'd still be curious
what the source was, if you see it turn up again. If you do, try enabling
debug mode ($config->debug=true; in your /site/config.php file) and
copy/paste the full debug backtrace into here. That should reveal what's
calling the remove() method. While I think it could possibly be a 3rd party
module, it's also possible that it's the core (and thus something I could
repair).

**Comment by nurkka** [comment]
Thanks for your reply ryan. You are right – it was one of my own modules, which was supposed to hide some infos and settings from editor users. The following code caused the error:
```
public function init() {
    $this->addHookAfter('ProcessPageEdit::buildFormSettings', $this, 'removeProcessPageEditInfo');
}
function removeProcessPageEditInfo (HookEvent $event) {
    $wrapper = $event->return;
    $wrapper->remove($wrapper->getChildByName('ProcessPageEditInfo'));
}
```
