### ISSUE TITLE
Module Settings Checkbox not showing correct value

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1374]
I'm just creating a module on a newest dev installation and the checkbox does not show it's checked state even though its value is correctly saved in the db.

```php
class MultisiteExtendedConfig extends ModuleConfig {
	public function getDefaults() {
		return array(
			"debugger" => 0
		);
	}

	public function getInputfields() {
		$inputfields = parent::getInputfields();

		$c = $this->modules->get('InputfieldCheckbox'); 
		$c->attr('name', 'debugger'); 
		$c->label = "Debug Logs";
		$c->collapsed = Inputfield::collapsedBlank;
		$inputfields->add($c); 

		return $inputfields; 
	}
}
```

**Comment by ryancramerdesign** [comment]
Add a  `$c->autocheck = true;` to your checkbox definition. That makes the checkbox assume it is "checked" whenever a non-zero value attribute is set to it. This is necessary because (like with HTML checkboxes) the "value" and the checked state are two different things. The "autocheck" option makes the checkbox field behave as if it were a text field, which is what you'd want for something like module configuration.
