### ISSUE TITLE
FieldtypeConcat error on dev

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1375]
When saving a FieldtypeConcat field on the current dev I'm getting this error: 
`Session: Warning: dependency field 'collapsed' is not present in this form. (InputfieldName)`

The visibility field is also really missing.

**Comment by ryancramerdesign** [comment]
Can you tell me more about your configuration for this concat field? Do you have a field named "collapsed" that you are using in a dependency somewhere? Do you have any dependencies in use that involve the concat field? There is no "visibility" possible for a concat field since it is a runtime generated field, not something that appears in the form or is saved in the db.

**Comment by LostKobrakai** [comment]
Ahh didn't even think of that there may be some own script trying to access it. Will check this tomorrow.
