### ISSUE TITLE
PageTable: pages should not get saved if required fields are empty

### ISSUE THREAD

**Issue by isellsoap** [ryancramerdesign/ProcessWire#1378]
**Problem description**

Required fields of pages that are accessed via a PageTable field in a modal window are being treated as if they aren’t required. Clicking on "Save" on such a page with a required field left blank triggers the expected error message "Required field is missing", but after closing the modal window (that happens either automatically or manually, depending on the setting) the AJAX-driven saving of the PageTable entry kicks in and the new state of the page is being saved.

**Expected behaviour**

The AJAX-driven saving of a PageTable entry should not get triggered, if the page was missing required fields.

**Setup**

* ProcessWire 2.6.16
* FieldtypePageTable 0.1.2

**Comment by isellsoap** [comment]
Just now I saw that this issue #1121 is already being opened discussing this problem.

**Comment by ryancramerdesign** [comment]
PageTable will not automatically close the window if there are errors present, at least it doesn't here. If you are seeing that behavior, I might need more info on how to duplicate. You can choose to close it yourself by clicking the little X in the top right corner, but it's not going to let you publish an unpublished page that contains errors. This is an intended behavior. ProcessWire considers fields as individual components when it comes to saving. If one fails to fill in a required field, it's not going to skip over saving the other valid fields. I think some may like the option of having a JS-validation that would prevent it from even submitting the form until a required field is filled in, so that's something I'm planning to revisit soon, but as a configurable option that you can turn on, not a default.

**Comment by isellsoap** [comment]
You are right in that PW doesn’t let you publish an unpublished page that contains errors. I should have clarified that in the opening description.

But *after* a page is published, the problem of this issue kicks in. And that to me is a bug, because PageTable pages get normally saved albeit required fields being empty, e.g. the user changes his mind, removes a required body text and hits save. In that scenario the modal window should not get closed (independent from the chosen closing setting) and I would expect that the AJAX-driven saving of that PageTable entry never gets triggered.

**Comment by ryancramerdesign** [comment]
In the scenario you described, the modal window does not close for me, does it for you? I tested by editing a PageTable page in a modal that's already published. I removed the value from a required field and hit save. I got an error and the modal stayed open. It wasn't until I populated the field and saved that the modal closed. Granted you can close the window yourself by clicking the [X]. 

With regard to required fields in general (whether in PageTable or anywhere that uses the page editor), ProcessWire doesn't ever prevent the save of a page. If a page is already published, you can blank out a required field if that is your intention. PW is going to complain if you do that and tell you what's missing, but it doesn't enforce it, like you might in a front-end form (i.e. FormBuilder or some other front-end form). The only time it enforces it is on publish. The admin has been designed within the context of trusted editors, which is a different context from front-end forms and untrusted users. As such, the "required" state is designed as something to guide editors, rather than as a roadblock. 

A reason for this is PW's flexible content modal, which enables you to add new fields to templates at any time. When you add a new field, and make it required, you might have many existing pages with that newly added field that is empty. So the reality of this content model is that you can't assume that something will always be populated, and the required behavior is intentionally designed to be consistent with this. One should always code their templates within the reality of this model. I know not everyone agrees with that behavior, but I think it's an important one when it comes to the big picture of how PW works. However, for people that want more "required" enforcement on the editor, I do think that adding front-end JS and/or required input attributes as an option is something we will support, as it wouldn't be at odds with the underlying intention of the system.

**Comment by isellsoap** [comment]
Thanks for the thorough explanation!

> Granted you can close the window yourself by clicking the [X].

Exactly. :-)

> However, for people that want more "required" enforcement on the editor, I do think that adding front-end JS and/or required input attributes as an option is something we will support, as it wouldn't be at odds with the underlying intention of the system.

That sounds pretty good.

**Comment by teppokoivula** [comment]
> I know not everyone agrees with that behavior, but I think it's an important one when it comes to the big picture of how PW works. However, for people that want more "required" enforcement on the editor, I do think that adding front-end JS and/or required input attributes as an option is something we will support, as it wouldn't be at odds with the underlying intention of the system.

You can count me in the category of people who don't agree with this :)

I for one would like to see the option of actually treating required as *required*, not just some variation of *recommended*. JavaScript validation is a partial solution, but it can (and will) also create more confusion: by disabling JavaScript one can submit the form anyway.

What you've explained as the reason makes sense, except that there's another way to approach this that to me seems to make at least as much sense: enforce required values the next time said pages are saved. Don't allow saving any additional changes unless all required fields are filled in.

Just my two cents.

**Comment by isellsoap** [comment]
Maybe related to https://github.com/ryancramerdesign/ProcessWire/issues/1743.

**Comment by somatonic** [comment]
PW must not allow emptying of a required field on a already published page. It should save page and save other fields, but not save an empty value to a required field. Never ever.

**Comment by isellsoap** [comment]
Fixed with https://github.com/ryancramerdesign/ProcessWire/commit/395ed6f57fc9fcb7d68fa846ff12d5aecb50ea1d.
