### ISSUE TITLE
New `published` field not visible in "Sort settings for children" dropdown

### ISSUE THREAD

**Issue by isellsoap** [ryancramerdesign/ProcessWire#1379]
I have version 2.6.16 installed but I can’t see the new `published` field in certain UIs, e.g. in the sort settings for children in a template (see image). 

![bildschirmfoto 2015-09-05 um 12 04 01](https://cloud.githubusercontent.com/assets/477474/9698790/403054e4-53c6-11e5-91b1-89eea83ba01d.png)

Shouldn’t it be visible in the "Native fields"?

**Comment by LostKobrakai** [comment]
Sorting by template is also still not available. https://github.com/ryancramerdesign/ProcessWire/pull/1190

**Comment by ryancramerdesign** [comment]
There are several places the new published property still needs to go, and it's a work in progress but plan to have it fully covered by PW 2.7 final. The published property isn't so useful for existing sites since it didn't exist before, so doesn't provide new data except for newly published pages. But I wanted to at least get the property in there recording data sooner rather than later, so that it will have future value in the places you've mentioned, and others. It may be a couple more minor versions before it starts showing up as a selectable option, but it'll be fully covered by 2.7.

**Comment by isellsoap** [comment]
Ok, that sounds pretty good. Thanks for the clarification!
