### ISSUE TITLE
Module download

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1387]
I just wanted to install Pages2Pdf from the modules directory, but I can't do so, because it's requiring WirePDF, which is part of the module. Maybe offering a "Just download" option in this case would be really nice, instead of just an option to abort. Therefore one can handle the requirements of the module afterwards.

**Comment by ryancramerdesign** [comment]
That's probably not safe for us to do because the "requires" can also be suggestive of a module that one extends (in the PHP class sense). If we download the module, then as soon as PW attempts to include the file to call its getModuleInfo() method (which most modules use), there would be a fatal PHP error, in this scenario. Using an external ModuleName.info.php or ModuleName.info.json file solves that issue, which is one of the reasons I added it. But I don't think we can require that in the 2.x versions of PW (maybe in the 3.x versions we can). So while I agree it would be nice to offer such an option as "just download", it could definitely cause class inheritance problems, so I think it's better to not provide this option at present.

**Comment by LostKobrakai** [comment]
There's also the option to download a zip directly, which does work and which does what I'm asking for. It's just convenient to not need to go back in the backend, open a new tab to get the github's zip link and paste it the direct download field.

**Comment by LostKobrakai** [comment]
Just revisiting this: How is processwire handling the extention problem you mentioned if one is manually adding a new module and doing a refresh?
