### ISSUE TITLE
Started adding PHPDocs bits, feedback needed

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1388]
Hi Ryan,

I've started working on adding PHPDocs blocks with the @since and other to the source, moving towards improving the documentation and easier code completion.

I'd like your input on the methodology I've been using so far and know if that's something you're comfortable with. I plan on adding PHPDocs comments on all important core files. Eventually I will send you a PR when work has advanced enough, or when completed, depending on which you prefer. I first started building a list of all important commits from GIT history and dating them, then and adding @since and @deprecated tags to the various methods and properties. Also when they did not already exist, I added @params, @return and other common flags.

The goal is to eventually be able to easily auto-generate docs which are more complete and version-aware.

You can see a preview with the WireUpload class I just completed on my PW fork. https://github.com/plauclair/ProcessWire/commit/e5927033d5b0d534dc60dfa2a28ecd18533c144b

**Comment by ryancramerdesign** [comment]
Thanks for your efforts @plauclair, looks good! Your example you linked is a good model for the future. I've been thinking we'd start supporting @since with PW 3.0, so that everything starts with a @since 3.0 and that gets used as the base of our documentation. I also thought we'd only support it for the public API, as that's where it would provide the benefit to others, and be sustainable to maintain. I'd also like to prevent anyone from having to figure out all the @since versions from past commits, as that just sounds like too much busy work–would prefer to just instead work from a common starting point as the base (i.e. 3.0) so that we aren't taking up all of your time or someone else with this. With regard to @deprecated flags, I have tried to make sure we are well covered there. There shouldn't be many (any?) instances of methods that are deprecated that lack @deprecated flags, though please let me know if you've found any.

**Comment by teppokoivula** [comment]
For the record, I would rather have this feature ASAP than in the future (3.0+) as it would make it easier for us to automate documentation generation process. If it's just a question of tracing all the features and the work that requires, I'd be happy to help with that.

Also: having everything as "since 3.0" doesn't in my opinion make sense. Sure, that's one point where we can definitely say the feature *existed*, but strictly speaking saying that it's "since 3.0" is going to be false information in many cases, and a potential source of confusion for devs still working with pre-3.0 versions of ProcessWire :)

**Comment by plauclair** [comment]
Thanks for your answer @ryancramerdesign, it actually isn't that bad to do this in PHPStorm, it basically add all the phpdocs blocks itself (mostly), then you need to review them quickly to see if it makes sense and add the ones it missed and couldn't figure out itself. The @since ones are also kind of easy, since PHPStorm will let you git log a specific method or property and then all I have to do it match the dates against a spreadsheet I made.

I do agree it would be easier to just do the public class elements, but it isn't that much more work to do all the private and protected ones too so I figured what the heck, might as well!

I'm thinking of using @internal flags for stuff that would require attention later on, like missing descriptions or docblocks that might need double checking or improving.

I'm kind of taking the opportunity to review the whole codebase to get accustomed to the hidden parts, which I think will be useful to develop more advanced modules on my end. Either way I see it as a win-win and I'm glad to work on it, slowly but surely!

If anyone is interested to lend a hand (there's 189 php files in wire/ according to cloc, though I doubt they are all strictly ProcessWire's), just say it here and I'll invite you to the repo!

**Comment by plauclair** [comment]
@ryancramerdesign, I was also forgetting, I added 2 @deprecated flags in the WireUpload example (most of the methods just didn't have docblocks to begin with, unlike many of the other classes I quickly glanced at or am used to browse through). Both are related to unzipCommand, one doesn't seem to be called anywhere, the other one is/was called by the deprecated one and didn't seem to appear anywhere else, so by extension I marked it as deprecated.
