### ISSUE TITLE
Clone Home Page - You may not modify 'id'

### ISSUE THREAD

**Issue by hagcin** [ryancramerdesign/ProcessWire#1389]
When I try to clone the home page from api I get this error:
"You may not modify 'id' on page '/' because it is a system page"

Tried:
$config->advanced = true;

And then and unchecking the page from being system page, that is locked. But It just gets rechecked after save.

Use case: drafting based on clone command. 
if you specify a parent in the clone() command you should be able to clone the home page. 

Processwire Version: 2.6.0

**Comment by ryancramerdesign** [comment]
Cloning isn't supported on system pages. There are certain pages in the system that having multiple copies of could cause problems, which is why you are seeing that error. There's also another problem with cloning the homepage, and that's that there can only be one "root" of the tree, which is the homepage. That makes direct cloning impossible for that particular page. Your best bet is to do it manually, create a new page using the same template (home), under a different parent, then copy the field data.

**Comment by hagcin** [comment]
OK, thanks for the explanation. Will close this issue...
