### ISSUE TITLE
CKEditor SHIFT+ENTER

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#1399]
When using Shift+Enter (for a \<br> instead of \<p>) and consequently pressing the SAVE button in the page editor, the standard "There are unsaved changes - are you sure you wan't to leave this page" popup appears.

Also a javascript error is thrown "Uncaught IndexSizeError: Failed to execute 'extend' on 'Selection': 1 is larger than the given node's length." (ckeditor.js:397).

When first focusing on another field and than pressing SAVE, everything works fine, the popup stays away.

I'm on ProcessWire dev 2.6.17

**Comment by ryancramerdesign** [comment]
I can't seem to reproduce the issues you've mentioned here. Though I have seen the "Uncaught IndexSizeError" before, but have attributed it to a CKE glitch and haven't had it interfere with anything else. Though it's been awhile since I've seen it. In testing here, I can do a shift-enter and click directly to save (without a blur on the field) and all seems to work normally. There were some issues here in past versions, so I'm wondering if you might possibly have an older CKE in your browser cache or something?

**Comment by junofornow** [comment]
Hi Ryan, it seems to be only happening when using the inline ckeditor, not the regular one.

**Comment by ryancramerdesign** [comment]
Thanks for the clarification, I can duplicate now. Looks like the CKEditor folks haven't fully fixed the getData() issue on inlines. I've re-applied our temporary fix from 4.5.1/4.5.2 back to InputfieldCKEditor.js.

**Comment by junofornow** [comment]
thanks
