### ISSUE TITLE
Error when creating comments field

### ISSUE THREAD

**Issue by bitmarker** [ryancramerdesign/ProcessWire#1416]
I've install the Comments field type. When I try to create a new field of the type "Comments", the creation fails with following error:

    Session: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxx.field_comments' doesn't exist

**Comment by ryancramerdesign** [comment]
@bitmarker what's your ProcessWire version?

**Comment by bitmarker** [comment]
I'm using 2.6.0-12-gcffb682. I've tested in with xampp and also on a linux
server. The strange thing is, the database table exists. But the message shows
anyway...

**Comment by Majini** [comment]
Hi Ryan

I too have been getting this exact same warning error.
I use MAMP for my local development and so far PW versions 2.6.18 dev and 2.6.19 dev both generate these errors.

MAMP details:

PHP version: 5.6.10

Server type: MySQL
Server version: 5.5.42 - Source distribution
Server charset: UTF-8 Unicode (utf8)

Hope that helps!

Zahari M.

**Comment by ryancramerdesign** [comment]
Thanks guys, I was able to duplicate it. The error message actually is normal and doesn't affect the operation of the field (or at least it shouldn't). It's just part of the schema version checking, and this particular error message can be ignored. I have submitted a fix that suppresses the error message so that you shouldn't see it anymore.

**Comment by isellsoap** [comment]
@bitmarker Can you close this issue please? Thank you!
