### ISSUE TITLE
CKEditor 'insert link' removes äöü ... maybe more?

### ISSUE THREAD

**Issue by blynx** [ryancramerdesign/ProcessWire#1417]
Inserting a Link like `https://de.wikipedia.org/wiki/Linkshänder` results in `https://de.wikipedia.org/wiki/Linkshnder` and breaks.

Which module is probably responsible for that? The InputField? (i could try to fix it by myself if I had a clue where to look) I deactivated the HTML Purifier but that didn't do it. As far as I can tell InputfieldPageName.js doesnt remove umlauts.

**Comment by LostKobrakai** [comment]
The module is ProcessPageEditLink

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this. It turns out that PHP's own URL sanitize/validation functions do not support internationalized domain or path names for URLs. So this one involved a bit of work to get it working while maintaining security, but I think we've got it. Please let me know if it resolves the issue from there too.

**Comment by blynx** [comment]
Fixed here - it also translated manually set escape characters to the original chars. Intention?
Thanks!

**Comment by ryancramerdesign** [comment]
Yes, that's intentional. There's no reason for PW to store encoded URLs when our storage already uses UTF8, and I think it's just easier for people to read in the admin environment if they aren't encoded. Though it looks like HTMLPurifier encodes them regardless, but I guess that's just something we've got to live with. :)

**Comment by isellsoap** [comment]
@blynx Can you close this issue please? Thank you!
