### ISSUE TITLE
Suggestion: Show system notification ghosts behind drop-down menus

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1419]
Would it be possible to adjust the z-index of system notifications so that they appear behind the drop-down menus when positioned in the right hand corner of the page? Sometimes I want to quickly access one of the menus as soon as a page has loaded, but the system notification pop-up temporarily blocks it. If I instead position the notifications on the left side, I lose access to the breadcrumb trail.

An alternative possibility or additional enhancement would be to allow positioning the notifications in the bottom left or right of the page.

**Comment by adrianbj** [comment]
You can already put them on the left - I made this request a while back for exactly that reason
![screen shot 2015-09-30 at 4 51 29 am](https://cloud.githubusercontent.com/assets/871211/10174796/f21fd41a-672e-11e5-97e2-6c5e0ef9d461.png)

**Comment by thetuningspoon** [comment]
Yes, I know I can put them on the left, but then they cover up the breadcrumbs... which is often something I want to get at immediately on page reload.

**Comment by adrianbj** [comment]
Right - sorry - I read quickly and just saw "left", not bottom left :)

Does it help a bit more if you disable the Runtime/single request notices? I haven't been using this module for a while, but that cleans things up a bit. 

I'll leave Ryan to follow up now :)

**Comment by ryancramerdesign** [comment]
I have updated the notification ghosts to show under drop down menu nav in AdminThemeDefault. Not sure if it'll be problematic when overlapping some Inputfield types, so that's something to keep an eye out for, but I haven't seen any issues yet. Lower left/right ghosts also sounds like a good idea, but I think there's a greater chance it's going to overlap with some field you are editing, so thinking we shouldn't go there for now.
