### ISSUE TITLE
hhvm mircotime issue

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1423]
When using hhvm with processwire the Debug.php doesn't work, because hhvm is using the locale decimal point, whereas php does use only full stops. I've added a diff to cater for the difference.

```diff
--- wire/core/Debug.php (current)
+++ wire/core/Debug.php (new)
@@ -44,9 +44,13 @@
 		// returns number of seconds elapsed since first call
 		if($reset && $key) self::removeTimer($key);
 
+		// HHVM does use local decimal point for microtime
+		$env = localeconv();
+		$decimalPoint = $env["decimal_point"];
+		$decpoint = preg_quote($decimalPoint);
+
 		if(!$key || !isset(self::$timers[$key])) {
 			// start new timer
-			preg_match('/(\.[0-9]+) ([0-9]+)/', microtime(), $time);
+			preg_match("/((?:\.|$decpoint)[0-9]+) ([0-9]+)/", microtime(), $time);
 			$startTime = doubleval($time[1]) + doubleval($time[2]);
 			if(!$key) {
 				$key = $startTime; 
@@ -56,7 +60,7 @@
 			$value = $key; 
 		} else {
 			// return timer
-			preg_match('/(\.[0-9]*) ([0-9]*)/', microtime(), $time);
+			preg_match("/((?:\.|$decpoint)[0-9]*) ([0-9]*)/", microtime(), $time);
 			$endTime = doubleval($time[1]) + doubleval($time[2]);
 			$startTime = self::$timers[$key]; 
 			$runTime = number_format($endTime - $startTime, 4);
```

**Comment by teppokoivula** [comment]
Note that function array dereferencing requires PHP 5.4. This only requires a minor change to above code, of course, so just a heads-up.

**Comment by LostKobrakai** [comment]
Thanks, I've changed it.

**Comment by ryancramerdesign** [comment]
I'm not familiar with hhvm, but just looked it up–are you saying that hhvm changes the behavior of PHP's microtime() function? I would worry a little about unintended side effects by changing the code here, since that behavior doesn't seem consistent with the PHP docs. I'm wondering if it might be safer to instead use a microtime(true) to force a float return value.

**Comment by LostKobrakai** [comment]
I'm not much more experienced here. Tried it today and found this to be an issue. I'm also not sure if this is really intended driftage from php spec or not. Will see if irc or hhvm does have an answer to that question.

**Comment by ryancramerdesign** [comment]
Rather than try to account for HHVM, I've gone ahead and changed the Debug class to use a different method of calculating timers that uses the microtime(true) which forces it to return a float rather than a string. This is also more efficient. I think older versions of PHP didn't have the return_as_float option for microtime() and this must be some legacy code from PW1.

**Comment by LostKobrakai** [comment]
Improvements are always nice. I doubt this still being incompatible and therefore close this.
