### ISSUE TITLE
Float input fields allow negative precision

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1432]
This seems to be a bug but I'm not sure (would precision -2 be steps of 10?). The precision field allows entering negative values. This screenshot was taken after saving.

<img width="357" alt="capture d ecran 2015-10-03 a 13 52 22" src="https://cloud.githubusercontent.com/assets/171120/10264332/5bcc0e0c-69d6-11e5-94b1-0a32c3d91ef3.png">

**Comment by ryancramerdesign** [comment]
Negative precision values are supposed to enable rounding of values before the decimal, like 1241757 with -3 rounds to 1242000 (at least according to the PHP docs for the round() function). I can't say I've ever had a use for it though, but there does seem to be a use case.

**Comment by plauclair** [comment]
Would't it be better suited to the integer field then?

**Comment by LostKobrakai** [comment]
Maybe this can just be added as note, so people are actually aware of the possibility. E.g. `Use negative values to round to a number of digits before the decimal point.` But Pierre-Luc is right, in that case floats are unnecessary.

**Comment by plauclair** [comment]
I can somewhat understand the logic behind this, especially when you consider that InputfieldFloat extents InputfieldInteger, you're kind of just messing with the precision (and not just the decimal point).

**Comment by ryancramerdesign** [comment]
ProcessWire is just echoing PHP's behavior for the round() function, which only accepts a float value, and allows negative precision. I don't think negative precision is useful enough in our context to call attention to it, but I also don't want to disable a valid argument to the round() function. Sooner or later there will be some math-guru that comes along expecting to be able to do negative precision anywhere they can do positive precision, because maybe that's technically correct if you are really into the subject. But it's worth noting that not even PHP documents it, they just identify the output in their examples. I'm assuming it must be some rounding standard that most never use. I think we should just leave this the way it is.
