### ISSUE TITLE
'Confirm email address' can't be overridden by context on email fields

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1433]
The 'Confirm email address' can't be overridden by context on email fields. If this isn't a bug, please close this for me. Thanks!

**Comment by ryancramerdesign** [comment]
Not sure I follow what you mean, can you describe further? Though note that the the confirmation email box is not considered a separate Inputfield to the system. It's just an option of the existing email field, to confirm that the values match as part of a validation.

**Comment by plauclair** [comment]
My bad, for some reason I was thinking input fields could have their options overridden by context, when it is not the case! Was probably late when I wrote this.

**Comment by ryancramerdesign** [comment]
Ah okay I understand what you mean now. Technically it's true that fields can have any options overridden by context. But what options can be overridden by context have to be defined by the Fieldtype and/or Inputfield, since the core doesn't know what might or might not be safe to override. Adding this as an override to the email field is possible and something that I can do.

**Comment by plauclair** [comment]
Would mark this as 'nice to have'. :)
