### ISSUE TITLE
Float and Integer input fields will allow min > max

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#1436]
Of course I'd be surprised if anyone would ever enter this, but there might be a sanity check before setting the min and max attributes.

**Comment by ryancramerdesign** [comment]
Since these field configuration Inputfields are processed independently by the system rather than by the module, and since it seems like a rare scenario, I'd rather keep the code lightweight here and leave as-is. But if in the future we need additional validations for these Inputfield config values, then we'll certainly add this one too.

**Comment by plauclair** [comment]
Thanks! Closing for now.
