### ISSUE TITLE
Empty trash timeout

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1440]
The trash does very nicely handle timeouts when pages are put individually into the trash. But I'd put a page with thousands of children into the trash and it did timeout again and again without getting rid of any of the children. I used a cli script then, but it would be nice to handle this case as nice as the first one mentioned.

**Comment by ryancramerdesign** [comment]
Emptying the trash is also an issue when the quantities are really large (it may take many times). The issue here is that PW is trying to be 3rd party hook friendly, making sure that all those pages go through the proper channels in terms of potential hooks and such. As a result, it doesn't go directly to a DB query and trash (or empty) them all in one shot, because that would be completely missed by any other hooks monitoring the movement of pages. I'm thinking in 2.8 we'll add a "force trash" and "force empty" options that let it go directly to the DB and file system to force the trash or empty operation, bypassing any hooks that may be setup. Though for the Trash page option, an alternative would be for it to force the status change directly in the DB for the branch of pages, and then spread the actual movement-to-trash operation over several requests in a LazyCron, perhaps handling a hundred or so at a time. In either case, this is on my to-do list for PW 2.8 (and 3.0) but probably won't make it's way into 2.7 since it'll no doubt involve a lot of new code.

**Comment by LostKobrakai** [comment]
Sure. I'm not asking for a speedier one-take clear in any way. It's rather that thousands of pages without children are deleted nicely (step by step) and as soon as one does only trash a single parent of thousands of pages it's blocking the whole trash process, because it's not able to get rid of all children and the parent in one take and therefore does nothing.

**Comment by ryancramerdesign** [comment]
I've refactored the empty trash code here so that theoretically it should handle large quantities without error. Though I've only tested with hundreds (rather than thousands) of pages so far, so am looking for more good test cases to confirm. Please let me know if you run into any trouble with it.
