### ISSUE TITLE
FieldtypeComments.module Implementation Notes contains errors.

### ISSUE THREAD

**Issue by Majini** [ryancramerdesign/ProcessWire#1444]
Hi Ryan!

When we wish to create our first ever comments field, we will be relying on the included implementation notes ( as seen in the comment fields details tab ) in a big way to help us implement our comments. 

The notes that contain the instructions to link the needed css and js files are, I believe wrong and may lead to some beginners getting frustrated to say the least. Not what we want for PW!

The instruction currently displayed to link the css file is:
link rel='stylesheet' type='text/css' href='<?=$config->urls->FieldtypeComments?>comments.css' />

The instruction currently displayed to link the js file:
script type='text/javascript' src='<?=$config->urls->FieldtypeComments?>comments.js'></script>

In both cases I believe the $config->urls part is incorrect and is missing the $this and really should be $this->config->urls ...

And so lines 860 and 870 in FieldtypeComments.module need to be edited to reflect this.

Also to be considered Ryan is the situation of differing styles of PHP's opening and closing tags. At the top of these implementation notes we see this:

<?php echo $page->comments->renderAll(); ?>

Later on we see the short tag styles ( the css and js examples above )

I would humbly suggest that instead of the implementation notes mixing regular tag styles ( for displaying the comments ) and then short tag styles ( for the css and js ), just one style be implemented for nice consistency. Since most examples shown in ProcessWires docs use regular tag styles, my recommendation is that the implementation notes here use the regular style tags such that we see something newbie friendly like:

script type='text/javascript' src='<?php echo $this->config->urls->FieldtypeComments; ?>comments.js'></script>

Hope that helps Ryan.

Just trying to make everything PW look awesome thru the lens of all newbies / newcomers!

Cheers

Zahari M.

**Comment by ryancramerdesign** [comment]
Actually it would be correct to use `$config->urls` rather than `$this->config->urls`, though it's true that using $this will work in some circumstances, but it's better to just use $config->urls or wire('config')->urls. Where you would want to use $this->config is if you are in a PHP class that extends one of ProcessWire's. 

Regarding the PHP tags, the standard I usually apply is short `<?=` tags for outputting values of variables, and long tags `<?php` if there is any kind of function call involved in the statement. Though in this case our renderAll() function call actually could utilize the short tags approach too, so I'll look into changing that. Even if it's a little different from what I've standardized on, shorter and simpler is better when it comes to this stuff.

**Comment by isellsoap** [comment]
@Majini Can this issue be closed?

**Comment by isellsoap** [comment]
@Majini I close this issue as it seems fixed or hasn’t had any reaction from you for months. If you think the issue requires additional work to do, please add a comment to this issue and I re-open it. Thank you.

**Comment by Majini** [comment]
Hi Francesco. Sorry was away but i believe i closed it ages ago. Thanks
anyway sir!
