### ISSUE TITLE
Show this field only if... parent selector issue

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1446]
This is kind of an odd one, and I have not worked out the root cause. However I have a field that in 'Show this field only if...' has the selector parent=/home/

Is this supported in admin?

**Comment by cb2004** [comment]
JS error:

Uncaught Error: Syntax error, unrecognized expression: #Inputfield_has_parent_/home/

Is this even supported in admin?

**Comment by ryancramerdesign** [comment]
A couple things to mention. The field you want to specify is instead
"parent_id" rather than parent, and you can only use the ID here, not the
path. Also, you'll need to disable the ajax-loaded state of your parent
field, so you'd need to add this to your /site/config.php
``````
$pageEdit = $config->pageEdit;
$pageEdit['ajaxParent'] = false;
$config->pageEdit = $pageEdit;
```````

**Comment by cb2004** [comment]
Cheers Ryan, closing this now.
