### ISSUE TITLE
Renaming template (without file) to a name starting with a number results in error

### ISSUE THREAD

**Issue by tomfrit** [ryancramerdesign/ProcessWire#1451]
I tried to rename my templates to reflect the names on my client's sheets: 1.1 something, 1.2 something else, etc. I tried "1_1_something" and "1-1-something" but always got the error 
The name "1" is already in use
Creating a new template with the name "1_1_something" works fine.
Using PW dev 2.6.19

Edit: The problem seems to be that the value "1-1_something" for Inputfield_confirm_rename ends up being "1" when assigned to the checkbox field:
ProcessTemplate.module, Line 2496 // $name= "1-1_something" but in the actual form the value is "1"

Edit 2: InputfieldCheckbox.module, Line 100:
if($value != self::checkedValueDefault) {}
For $value = "1-1_something" this is false but should be true. Changing it to !== fixes the problem but might cause issues ...

**Comment by ryancramerdesign** [comment]
Thanks @tomfrit I have pushed a fix for this to the dev branch. In general, we recommend using varname format for templates and/or fields, meaning digits are fine, but just not as the first character (kind of like how PHP or JS variables can't have a digit as the first character). We don't enforce it at present, but I'm wondering if maybe we should because there are likely more scenarios where this could come up–though hopefully not. Please let me know if you find any others, and we can always fix them as they turn up too.

**Comment by tomfrit** [comment]
Thanks @ryancramerdesign , I know this is bad practice and now I know why.
