### ISSUE TITLE
Sending errors from front-end

### ISSUE THREAD

**Issue by Da-Fecto** [ryancramerdesign/ProcessWire#1456]
I thought we could write error messages on the front-end with session.
```php
// Does work
wire("pages")->error('yippy ky yay', Notice::log); 

// And this doesn't
wire("session")->error('Oops', Notice::log);
```
Is this a bug or am I wrong?

**Comment by ryancramerdesign** [comment]
When you send an error(), message() or warning() call to $session it just queues it for screen output on the next request. On the front-end, there is no screen output unless you have implemented it in your own templates. Since your intention is instead to send it to the log, you could call `wire()->error('Oops', Notice::log);` but I would instead recommend just using the $log API variable for this purpose instead, i.e. `$log->error('Oops');` or `wire('log')->error('Oops');`.

**Comment by Da-Fecto** [comment]
It's for a 'service page' so there's no real front-end there. Gonna go for wire('log'), makes sense, thanks for your fast reply.
