### ISSUE TITLE
2.6.20 getParentPermission error

### ISSUE THREAD

**Issue by maba** [ryancramerdesign/ProcessWire#1458]
With 2.6.20 if I go to Roles menu I got notification error: 

    Method NullPage::getParentPermission does not exist or is not callable in this context 

and "The process returned no content." on the page.

**Comment by Da-Fecto** [comment]
@maba, could you please verify one thing for me?
Go to /processwire/access/permissions/ and see if there are unpublished permissions ?

**Comment by ryancramerdesign** [comment]
@maba I can't duplicate the issue here, but have attempted a fix by adding an extra check at one part in ProcessRole. This is now pushed to the dev branch (only need to update the ProcessRole.module file). If you find this doesn't fix the issue, can you enable debug mode and let me know what line number the error is occurring on? Thanks.

**Comment by Da-Fecto** [comment]
Actually i've seen this before. For me it was a Permission that was in a unpublished state.

**Comment by maba** [comment]
In attach my permissions page.
I would try debug mode but site (frontend) goes offline. Other problem: debug on and site off. :(
Debug off and updated with fixed branch and now it works. I have to clear alla cache (core and procache) obviously.

![mon oct 19 12 35 25 cest 2015](https://cloud.githubusercontent.com/assets/281785/10575686/81c7d354-765e-11e5-8c4d-26e595823a3d.png)

**Comment by maba** [comment]
Seems fixed.
Now I have to investigate on debug mode on problem.
