### ISSUE TITLE
css and translation string in admin profile

### ISSUE THREAD

**Issue by Manfred62** [ryancramerdesign/ProcessWire#1471]
in the admin user profile the content tab is missing ```#content .WireTabs a.on``` in the css (white background and border).

![pw-root-tab](https://cloud.githubusercontent.com/assets/5367033/10669432/0b0b9c3e-78e1-11e5-9c59-a6aacd02cdc1.jpg)

The phrase "Set Password" isn't translatable (found it in the install.sql)
Seems to be the last gap in translated backend ;-)

**Comment by ryancramerdesign** [comment]
Regarding the tab, this is just what PW does when there's only one possible tab. Probably better to have it highlighted I agree, but I think I'll come back to that one when some other updates are being made to the tabs system. 

For the Set Password translation, I've updated InputfieldPassword.module so that hopefully it should now work with the translation–thanks!

**Comment by isellsoap** [comment]
@Manfred62 Can you close this issue please? Thank you!

**Comment by Manfred62** [comment]
fixed
