### ISSUE TITLE
The modal window still jumps sometimes

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1475]
Not a big deal but I wanted to mention it...
The modal window can jump down half out of view if:
1. there is an alert "Page is already edited in another window"
  (If I correct it by resizing the window, the above mentioned alert would be covered/invisible)
or:
2. Select by dragging -  Example: From a CK editor, I open the links modal window, which has a link in it. I want to select a word  by dragging the cursor from right to left (and up - 10 a clock direction) (i am a left-handed) over a word from the link. - modal moves down. (Mac Safari Capitan, dragging by mousepad)

**Comment by ryancramerdesign** [comment]
I can duplicate 1, but not 2. Maybe it's because I'm not in El Capitan yet (the upgrade bricked my wife's Macbook Pro so decided to wait), but did try in the latest Safari and Chrome. I'm not too concerned about 1 since it's an optional alert it's supposed to get in your face, but 2 sounds more concerning, I just can't find a way to duplicate yet. Of course if I can figure out how to adjust for 1 I will as well, but can see getting stuck for half a day with that one. :) Maybe once I can duplicate 2 I can solve it for both though.

**Comment by tbba** [comment]
1 is probably only a question of a very high z-index?
2 I can try to make a video if you can't duplicate it :-)

**Comment by tbba** [comment]
short demo of jumping (same with Safari 9.0.1 extensions on or off):
https://dl.dropboxusercontent.com/u/357632/processwire-issue-demo.mp4

**Comment by tbba** [comment]
This is still the case here - Am I the only one?

**Comment by tbba** [comment]
I can confirm this is a broser issue (Safari). I had the same thing today when using the PW-forum in "preview message"-mode. Since the php software is not related I can rule out PW as the problem. The issue is more general.

**Comment by tbba** [comment]
https://discussions.apple.com/thread/6776139?start=0&tstart=0
