### ISSUE TITLE
CKeditor -Doubleclick opens modal instead of selecting word

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1476]
Not sure this is a real bug - it is only unusual behavior...
- CKEditor: Double click on word in link - does not select the word but open the link editor (unexpected)
  (I would prefer to have a single click + modifier key for opening the link editor instead - and would expect that the system does what is always does on a doubleclick on a word: selecting it.)

**Comment by teppokoivula** [comment]
Perhaps it's because of my past experience with FCKEditor and CKEditor, but to me the current behavior feels completely natural and intuitive. Seems to me that this is very much a question of preference, really :)

**Comment by ryancramerdesign** [comment]
This is an intentional behavior from CKE. Double clicking on actionable/plugin markup items opens a dialog to edit those items. It does the same thing if you double click on an image, anchor, etc. There's likely some way to disable it somehow or another, but I'm with Teppo on this one in that the double clicking of these things is definitely something I use a lot (though like he said, maybe that's because we grew up on these RTE's).

**Comment by tbba** [comment]
ok :-)
