### ISSUE TITLE
Creating custom Image field error (again)

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1481]
Field "images" is not yet ready to use and needs to be configured. Had to save twice.

https://github.com/ryancramerdesign/ProcessWire/issues/582

PW 2.6.21

**Comment by ryancramerdesign** [comment]
This is correct because when you create a field (the first save), the settings are not yet known and are rendered in the next screen when you have details, input, etc., tabs. Some fieldtypes need those settings to be reviewed and saved before the field can be used. Examples include images, files, page references and others. There should be a warning in the field editor telling you that you need to save the settings before the field can be used, and that was added as a result of #582.

**Comment by matjazpotocnik** [comment]
I know it was fixed, checked the source, that's why I expected different message. Strange, I just created another image field and this time I was politely told that I should resave (as expected). Hm? Ok, closing, thank you.
