### ISSUE TITLE
Support non-asci characters in uploaded file name in IE

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1487]
(Similar to #421)

In /wire/modules/Inputfield/InputfieldFile/InputfieldFile.js line 285:

xhr.setRequestHeader("X-FILENAME", unescape(encodeURIComponent(file.name)));

should be

xhr.setRequestHeader("X-FILENAME", encodeURIComponent(file.name));

In /wire/core/WireUpload.php line 134:

if(!$filename = $_SERVER['HTTP_X_FILENAME']) return false; 

should be replaced with 

if(!$filename = rawurldecode($_SERVER['HTTP_X_FILENAME'])) return false;

Also in /wire/core/WireUpload.php line 216:

if($this->lowercase) $value = strtolower($value); 

maybe it should be (not sure)

if($this->lowercase) $value = mb_strtolower($value, "UTF-8");  

See https://processwire.com/talk/topic/11343-file-upload-in-ie/ for more info.

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I have added this as a @todo for the next dev branch because this seems like it might need more thorough testing in the dev branch and we are only a few days away from putting out 2.7. When something like this affects only one browser I always have to worry about the implications to other browsers, so would like to come back to this one shortly. It's been awhile since we originally developed InputfieldFile.js but if I recall correctly there was a reason why the unescape() was necessary, though it escapes me now–I will do more research. Great detective work by the way, thanks for tracking this down.

**Comment by matjazpotocnik** [comment]
Thank you, it works!
