### ISSUE TITLE
Unable to save cyrillic symbols in URL input filed.

### ISSUE THREAD

**Issue by whitebyte** [ryancramerdesign/ProcessWire#1506]
I'm trying to save "http://трикотаж-леко.рф" string in the URL inputfield. This is valid URL, but PW refuses to save it. After quick investigation it seems that URL field isn't UTF-compatible and only accepts ASCII. Any plans on fixing this?

For now I'm using punycoded URLs, but they are sooo ugly (e.g. "xn----7sbqcimegxgmxe.xn--p1ai").

**Comment by ryancramerdesign** [comment]
The trouble is that PHP's own URL validation functions don't support internationalized domain names (IDNs). However, since we now support utf-8 paths, we should support the same in domains. And I agree, nobody wants to deal with punycoded URLs. :) I've gone ahead and added the code necessary to support IDNs on the dev branch. 

Since IDNs don't count as valid URLs in a lot of places (including PHP's own wrappers/streams) they are something that I think wasn't good to have enabled by default. But you can enable it by editing any URL field, clicking on the "details" tab and checking the box to "Allow IDNs". Please let me know how it works for you. 

Note that this requires that your copy of PHP supports the `idn_to_utf8` and `idn_to_ascii` functions, which may require PHP 5.4+ in order to be assumed present, though I think they may also be installed in prior versions via a PECL library.

**Comment by whitebyte** [comment]
Wow, that was quick! And works like a charm, many thanks!
