### ISSUE TITLE
Orphaned data in DB when removing field from a template.

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#1510]
This is using latest PW. But also seems to happen on other older.

I can add any field to basic-page. Then enter some data in some pages in this field. Then remove this field from basic-page. After confirmation, I see the message:

Session: Deleted field "testfield" data in 2 row(s) from 2 page(s). [page-by-page]

But the data in DB is still there! Why is that?

**Comment by somatonic** [comment]
I recognized that I have on one big big project, tons of data orphaned in tables. Not sure how comes, but pretty :(

**Comment by ryancramerdesign** [comment]
Thanks @somatonic, that's a good find – I have pushed a fix for this.

**Comment by ryancramerdesign** [comment]
@somatonic I've also just updated the ProcessField "Check field data" action to support find/removal of orphaned rows due to this particular issue.

**Comment by adrianbj** [comment]
:+1:

**Comment by somatonic** [comment]
Thanks Ryan. Will this be in 2.7?

**Comment by ryancramerdesign** [comment]
Everything on the dev branch right now will go into this week's 2.7.1 version, which will be merged to master.

**Comment by tbba** [comment]
Does that mean that reminders from the past get automatically fixed or do I need to clean up manually field by field? I also found orphans in some of my databases...

**Comment by ryancramerdesign** [comment]
You would need to do it manually. PW doesn't do any kind of mass data deletion automatically. Keep in mind it's not hurting anything just by leaving it there, other than that it's taking up space unnecessarily. Anytime you run a check, it'll tell you what other fields it thinks also need to be checked (see the notices at the top). You could just click (new tab) each of them, so you don't need to manually check every field. 

As always, be sure to back-up your database before doing any kind of mass data deletion. Especially since the code was just added today and has only been tested by me so far.

**Comment by somatonic** [comment]
We actually found out about it cause it did matter. SchedulePages actually runs DB queries on the datetime field to publish/unpublish pages.
