### ISSUE TITLE
Date time picker

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#1528]
Since Jquery datetime picker update on devns (PW 3) you can only delete one number, then the field loose focus.

**Comment by ryancramerdesign** [comment]
I see what you mean, I can duplicate that too. I'm not really sure how to correct that one, as it seems to be the new timepicker version that's doing it, and it seems to assume that the date/time picker is the only input method. Switching to the datepicker trigger on button click should solve that. This might be one that we need to submit an issue report to the author of the timepicker plugin, though it's unclear to me if the current behavior is intentional or not. I will keep an eye on this.

**Comment by matjazpotocnik** [comment]
Switching to the datepicker trigger on button click does not solve the problem. Will wait the developers to fix that.

**Comment by matjazpotocnik** [comment]
I tried dev version of timepicker, no luck.

BTW, if you set devmode = true in /wire/modules/Jquery/JqueryCore.module then /wire/core/ModuleJS.php throws an error in line 138:

$mtime = filemtime($config->paths->$class . $url);

I think it should be 

$mtime = filemtime($config->paths->$class . $this->components[$name]);

**Comment by matjazpotocnik** [comment]
To overcome this issue, simply this line in jquery-ui-timepicker-addon.js :

this.$timeObj[0].setSelectionRange(sPos, ePos) (L893)

Source: https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/848#issuecomment-170860480

**Comment by ryancramerdesign** [comment]
Thanks, your proposed fixes have been added to devns.

**Comment by matjazpotocnik** [comment]
Cool, thanks.

Commenting out setSelectionRange also fixes the following issues:
1. "Unspecified error" in IE when changing time in date/time ranges (reproduces in IE11)
2. Date time picker steals the focus from "autofocus" input on page load (reproduces in Chrome 47.0.2526.111 m)

Source: https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/848#issuecomment-170860480
