### ISSUE TITLE
Wish: if image in CKE is linked to original version, add class to a-tag

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1549]
Wishlist: if an image in CKE is linked to it's original version, is it possible to have some class added to the surrounding a-tag automatically, so I can catch that and change the default behavior easier with some Javascript?

**Comment by teppokoivula** [comment]
Unless this is a common need, it sounds to me like this would be a good use case for a separate Textformatter module, don't you agree? One could also easily achieve this by a preg_replace() on template file, so this doesn't strictly speaking even need a Textformatter :)

**Comment by ryancramerdesign** [comment]
I'm reluctant to have PW add specific classes to stuff in markup, unless absolutely necessary. It's necessary when it comes to alignment classes, but I've tried not to stray outside that. Teppo is right that this is more the purview of a Textformatter. Or you could just add something like this to your /site/ready.php file:
```````
wire()->addHookAfter('FieldtypeTextarea::formatValue', function($event) {
  $value = $event->return;
  if(!strpos($value, '<img') || !strpos($value, '<a ')) return; // quick exit when possible
  $event->return = preg_replace('/<a(\s[^>]+>\s*<img)/s', '<a class="your-class"$1', $value);
}); 
`````````

**Comment by trk** [comment]
On the front-end you can catch links with js easily. Just put the output in a custom classed element and use it for make search inside this element. On my side i am adding lightbox to linked images with this method.

For example :
```html
<div class='my-custom-output'>
<?php echo $page->body; ?>
</div>
<script>
jQuery(function($) {
     var linkedImages = $('.my-custom-output a img');
     if(linkedImages.length) {
        linkedImages.each(function(){
            if($(this).parent('a').length) {
                /// Do what you want with linked images
            }
        });
    }
});
</script>
```

**Comment by tbba** [comment]
Thank you for your interesting solutions.
@trk - I tried that, but it also catches other images that are wrapped with a-tag, not only the created ones showing the enlarged version.
@ryan - this has the same problem, I think, false positives in the selection. It catches too much, correct?

Why I was asking in the first place: I understand that the idea is that PW leaves alone markup if possible. But the exception from the rule is CKE already: All in there is markup. And I think that one class for the few specific thinks that PW modules add to CKE is less trouble and more reliable than Modules and hacking the field output. And easier to reuse.

The idea behind this is that CKE is about the only thing in PW were frameworks like uikit/bootstrap have no way of targeting and controlling elements. I ink uikit classes in with jQuery as TKR shows in his example - but it is tricky to catch that specific image behavior precisely without false positives, as I said.

Images in CKE (as it is delivered with PW and with no hacks applied) link to the original image and the browser jumps away from the page on click. That is so old school. I wanted to use one of uikit's presentation features for those enlarged images instead.

Also the purifier is very aggressive. Certain hand set IDs and classes (or group of classes) are just filtered out as soon as I hit "save".

Or is my thinking wrong? Did I overlook something  :-)

**Comment by BitPoet** [comment]
You can specify additional classes for links in the configuration of the ProcessPageEdit module. Those classes can then be checked in the link properties in CKE and persist through ACF and Purifier. Just tested it with 2.7.2 and there it works without problems.

**Comment by tbba** [comment]
@BitPoet - This is a very good workaround, you mentioned. - But complicated for clients and error prone: Try to explain to a client that, in case he wants to show the bigger version of an image in a lightbox, he needs to click the "show bigger" checkbox and later needs to re-configure the image, now with the link tool, to set the class. This is the opposite of easiness. And I "sold" them PW for it's easiness (compared to WordPress).

**Comment by ryancramerdesign** [comment]
@tbba Adding something like custom uikit classes stored in your CKEditor markup means your content is no longer portable. You want to keep your DB-stored content as clean and portable as possible, devoid of any CSS/JS framework classes as much as possible. Otherwise your content will only be good for output in your current context, and not for other output scenarios or future upgrades that might use a different CSS framework, for example. Purifier and ACF do a good job of ensuring this, and while it may not seem like the most convenient thing for a short term need, it's actually a very good thing for the long term integrity of your content. 

Despite that, you can also use a mystyles.js file in your /site/modules/InputfieldCKEditor/ directory, where we've got an example setup there ready for you to modify. When you add stuff there, and enable a "Styles" toolbar item in your CKEditor, the client can apply classes as they see fit, very easily. Though I'd recommend sticking to general purpose classes that would help your content remain portable, rather than framework-specific stuff. 

But I understand you are wanting something more automated, where it just happens when a client inserts an image. I still think the hook method (or JS) is a good way to go because it completely bypasses purifier since it applies them at runtime.

The only false positive I can envision here is if you are having a mixture of linked images that you do want to add a class to, and linked images that you don't. For instance, a linked image that opens a link to something that is not an image. Is this your need? If so, the hook could easily be adjusted to just apply to only links pointing to image files:
``````
wire()->addHookAfter('FieldtypeTextarea::formatValue', function($event) {
  $value = $event->return;
  if(!strpos($value, '<img') || !strpos($value, '<a ')) return; // quick exit when possible
  $regex = '!<a(\s[^>]+?\.(?:jpe?g|png|gif)[^>]*>\s*<img)!s';
  $event->return = preg_replace($regex, '<a class="your-class"$1', $value);
}); 
``````
For something like I lightbox, I actually think that @trk's method may be better because JS is already required, and in Javascript or jQuery you've got the DOM, which makes the code simpler. You could make the same update to that code:
``````
$('.bodycopy').find('a[href$=jpg] img, a[href$=png] img').each(function() {
  $(this).parent().addClass('your-class');
});
``````

**Comment by tbba** [comment]
@ryan: The Javascipt you provide here (i mean the jQuery-selector: not asking *where* the code is but *what* it does) is very clever and probably solves my question about connecting a UIKIT lightbox 100%. I was completely on the wrong track. Can't wait to try this out.

Thank you all for your help. - This friendly, helpful community makes working with PW so much fun.
