### ISSUE TITLE
ProcessWire 3.0.1 alpha-4, potential issue with translation method __()

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1552]
Running latest alpha version of 3.0, I'm getting error messages from FormBuilder's email administrator feature. The issue is caused by __(), which is not recognized. Can't remember the exact error message, but I can dig that up if it helps.

Not sure if this is related to FormBuilder, or a more generic issue. So far I've seen no issues with any other modules, and everything else (that I've tested) within FormBuilder seems to work just fine too.

**Comment by tbba** [comment]
No issues? Congrats! I had issues with at least some modules: I remember, they were more exotic (but nice) ones: FieldtypeSecureFile and TextformatterSuperSmartypants. They had one thing in common: The loaded scripts with require_once("example_file.php"), which throw an exception for not finding anything. Changing that code to ("./example_file.php") fixed it but I think the code was valid and this is a bug. Tested locally with MAMP. And I can not rule out MAMP being part of the issue, so I did not write a proper report yet. I reverted back to PW 2.x because the Compiler was too much drama for me (example: The Ajax uploading of images also did not work as before: The images were physically uploaded but the page did not show them on save). Reverting back cured everything.

**Comment by teppokoivula** [comment]
Thanks for the input, @tbba. I've been using 3.0 for only one site, and I don't have that many 3rd party modules installed there.

I'll keep an eye out for any other weirdnesses, but that ajax upload issue (for an example) doesn't seem to happen in my installation. Perhaps this has already been fixed in one of the alpha releases.

**Comment by ryancramerdesign** [comment]
@teppokoivula can you tell me what actions you did in FormBuilder to produce the error message? I'm using FormBuilder here with 3.0 but haven't yet seen the error. FileCompiler does account for __() calls, but chances are there is some usage of it in FormBuilder that it's not recognizing. I just need to determine where that is. 

@tbba thanks, knowing what example caused it to not work will be helpful, I will test with that. Though a require_once("example_file.php"); isn't a good thing to do because it can potentially search the entire php include path. But it's definitely something FileCompiler should recognize and support so I will test and update here. I'm also using MAMP here, so don't hold back on reporting due to that. :)

I've not seen any issues with image uploads, and can't think of any reason why that would occur in any of the alpha 3.x versions. I'm guessing maybe it was unrelated, or is it possible you were using one of the other 3rd party image modules? If so, let me know which one so I can test. What you describe also potentially just sounds like an older cached JS file that a hard refresh might fix.

**Comment by teppokoivula** [comment]
@ryancramerdesign this happens when submitting a form embedded with the iframe method. Said form is configured to send an email to administrators, and the error is this:

> Error: 	Call to undefined function __() (line 49 of /path/to/example.com/site/modules/FormBuilder/email-administrator.php

I took a closer look at FileCompiler cache, and there the __() method remains as-is. Is this how it's supposed to work, or should that be somehow altered by the compiler? Not sure how exactly FileCompiler accounts for this, so just guessing here :)

**Comment by ryancramerdesign** [comment]
I was able to find and fix the issue that @tbba ran into, so that appears in today's 3.0.2. However, I wasn't able to duplicate the email-administrator.php error you mentioned. It seems to be getting compiled correctly here. If you are running the latest 3.0.2, try removing your /site/assets/cache/FileCompiler/ directory completely and let it re-create everything. Maybe there's an old file sticking around from a previous 3.x version with an issue. If that doesn't do it, let me know. Thanks.

**Comment by tbba** [comment]
(Sorry for having hijacked this thread instead of writing my bug report in it's own thread. My issues listed above are soved with the latest update. Thank you very much.)

**Comment by maniqui** [comment]
`Error: Call to undefined function __() `

In case anyone googling this error arrives here, I've been also bitten by it. In my case, the issue was that I was including a template (`<?php include $view ?>`, where `$view = './views/product.php'`), but I was missing a `<?php namespace ProcessWire;?>` at the very top of that template. Adding it, of course, fixed it.

**Comment by teppokoivula** [comment]
This issue doesn't seem to exist anymore. Closing.
