### ISSUE TITLE
PageTable ajax update does not honor markupValue hooks

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1555]
I've a hook which does limit a number field to only 2 decimals, but as soon as I save the page in the pagetable and the row being updated the full decimals are back. The hook is in the ready.php.

```php
$wire->addHookAfter("FieldtypeDecimal::markupValue", function(HookEvent $event){
	$event->return = bcmul($event->return, "1", 2);
});
```

**Comment by ryancramerdesign** [comment]
You'll need to put that particular hook in an /site/init.php file rather than a ready.php file. The ready.php file is called after the ready() has been called for all autoload modules. Since PageTable fulfills the ajax request during ready(), the hooks in your ready.php file would get called after that, meaning they aren't getting attached. But simply moving your hook to an the init.php file should fix it–please let me know.

**Comment by LostKobrakai** [comment]
You're right. Moving the hook fixed the issue.
