### ISSUE TITLE
PW 302 Compiler issues

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1556]
ON MAMP - Compiler (localhost) tried to do something with an internal (reserved) APPLE file (.DS_Store)?

*Warning: copy(/Users/carl/.../site/assets/cache/FileCompiler/site/templates/.DS_Store): failed to open stream: Permission denied in /Users/carl/...t/wire/core/FileCompiler.php on line 643*

It appeared only at my first login after the update PW2->3.
Deleting all the /cache/FileCompiler/ also helped cleaning things up.

**Comment by tbba** [comment]
Also the compiler is not so nice with larger sites (tested Localhost/MAMP):

*INTERNAL SERVER ERROR*

(timeout?)
I have to reload the page several time and eventually everything works.

**Comment by tbba** [comment]
Question: 
I normally update live sites by GIT-syncing files, then syncing the database.
The compiler has a cache as files AND in the database. Can this mean problems with syncing?
Is there an easy was to clear all Compiler caches in the Admin area (like the proCache has it)?

**Comment by ryancramerdesign** [comment]
> ON MAMP - Compiler (localhost) tried to do something with an internal (reserved) APPLE file (.DS_Store)?

It simply copies all the files, just in case any need to be in the same dir as the compiled file. Though it doesn't attempt to compile anything but PHP files. 

> Also the compiler is not so nice with larger sites (tested Localhost/MAMP): INTERNAL SERVER ERROR

I don't think it's a timeout, because FileCompiler resets the timeout clock on every file. Though I'll double check to see if we need to increase the allowed timeout, but I think it's currently at something like 10 minutes. Glad that reloading did the trick. How many bytes are consumed by your /site/templates/ directory and how many by your /site/modules/ directory? Just wondering what you mean by larger site? The site database size doesn't matter to the FileCompiler, but if there are gigabytes of files in in your /site/templates/ dir, that might be something I'd need to look at closer to see if we need optimization there.

> The compiler has a cache as files AND in the database. Can this mean problems with syncing?

I don't think so. The cached DB info only comes into play for files that are actually present. You could exclude syncing your /site/assets/cache/ dir (or at least /site/assets/cache/FileCompiler/ dir), letting the files be recompiled on the live server. Though I don't think it should matter. FileCompiler keeps hashes of everything, so if there's any differences it simply recompiles the file. The cached DB info is there purely to perform comparisons. 

> Is there an easy was to clear all Compiler caches in the Admin area (like the proCache has it)?

I think I should add such a tool. Currently you can clear the cache just by deleting the /site/assets/cache/FileCompiler directory.

**Comment by tbba** [comment]
>ON MAMP - Compiler (localhost) tried to do something with an internal (reserved) APPLE file (.DS_Store)?
>It simply copies all the files, just in case any need to be in the same dir as the compiled file. Though it doesn't attempt to compile anything but PHP files.

It had thrown an error about non sufficient rights to store the .DS_Store. That's what I was mentioning it. The warning was the problem for me.

>How many bytes are consumed by your /site/templates/ directory and how many by your /site/modules/ directory? Just wondering what you mean by larger site? 

Nothing that should matter. The "larger" site just ment one of MY larger sites: say 20 templates, lots of modules (this is what I think is might be the problem): I see 90 modules folders in the site/modules folder.) that is a bit much, but this is my general testing site for trying out things.

> Currently you can clear the cache just by deleting the FileCompiler directory.
...which proves to cure a lot of problems already. So your tool makes sense to me.

**Comment by ryancramerdesign** [comment]
> It had thrown an error about non sufficient rights to store the .DS_Store. That's what I was mentioning it. The warning was the problem for me.

PW does need read access to all the files it manages. I'm not sure we should be suppressing warnings about cases where it can't access a file that it's supposed to be able to. Though obviously .DS_Store is one that doesn't matter to PW. I'm not having issues with copying of .DS_Store under MAMP here, but will keep an eye out. We can always just have it skip over specific file names like that. 

> I see 90 modules folders in the site/modules/ - that is a bit much, but this is my general testing site for trying out things.

20 template is no problem, and templates are relatively simple and fast to compile compared to modules. But 90 modules... now that is a lot. :) Speaking totally outside the context of PW3: That's a lot of potential overhead, things to keep track of (for you), and places for things to go wrong. If you've got modules that you don't need there, I'd definitely suggest removing them, regardless of PW version. I'm not sure we can do better than having to reload a few times to get them all compiled, as that really is a lot of work to be done from a compilation perspective. Though I'm guessing it was a matter of running out of memory rather than a time limit. Hitting reload a few times till it can cover them all should be safe, even if it isn't pretty.

**Comment by tbba** [comment]
You are right about to many modules. More and more the core updates makes them obsolete. But looking closer, it is not that much overhead. 15 modules were inative, many modules are very specialized, like WIreMail, Backup, some Backend-Tweaks and a very rarely fired on a normal website use, I think. - But I agree, now that the potential problem is known to you, we can close the thread.
