### ISSUE TITLE
ImageMaintenance and VersionControl

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1584]
A not so new bug is there again in 2 of my current web projects (PW 2.x and also 3.x): 
I recently got some red error notices on images for which I know I had deleted them and had also deleted any references in the CKE fields:
> "Image file on page /xxxxx/ no longer exists (image.gif)"

I searched the database and found that the non-existing image is still referenced in the field version_control_data which belongs to a 3rd party module.

Is it possible to suppress the error for references that are not currently used but only exist as reminders in some special storage fields?
Or do I need to report this to the module author?

**Comment by teppokoivula** [comment]
Just checking, but are you talking about my VersionControl module, or something entirely different?

Names seem to match, but VersionControl doesn't use any fields at all (and the data table is version_control__data, not version_control_data) so not entirely sure if the two are related :)

**Comment by tbba** [comment]
Hi Teppo, this is your module... are there other ones?... I didn't know.
Your module is one of my favorite modules, and still working great, by the way.

**Comment by ryancramerdesign** [comment]
PW reports those messages because the content-type of the text field is set to "Markup/HTML with image management". Meaning, it's keeping track of the images and reporting when one goes missing. If you change it to just "Markup/HTML", that should suppress that particular error message. I'm guessing you are seeing it with Version Control because it's populating an older version of the text back to the page (as part of its version features), and an image referenced from the text is no longer there.

**Comment by tbba** [comment]
First of all: A happy new year!!!!
...what you describe is what happened. I like the image management and would like to use it. I just thought there might be a way to suppress a warning for images that exist only for a litte longer while in the version control backups. - Since the warning did not give any information in what field it detected the outdated link it was a long guess to find out what was going on and that actually this was a false alert (not in the technical sense - but no user action was needed).

**Comment by tbba** [comment]
I close this for now. So much changed with the images in PW3dev this issue maybe obsolete.
