### ISSUE TITLE
WireHttp send methods

### ISSUE THREAD

**Issue by pwFoo** [ryancramerdesign/ProcessWire#1589]
WireHttp implements multiple send methods, but is it (still) needed?
- curl
- fopen
- ...

I started with only file_get_contents() because that should be available in every (today used) php version available.
Maybe WireHttp class could be much shorter and simplified? Would it be a benefit or just no improvement (for example performance, simplified code).

**Comment by ryancramerdesign** [comment]
file_get_contents actually can't be used in many environments. It depends
on how PHP is configured, especially with regard to security settings. This
is why WireHttp contains fallbacks to sockets (which comes into play
often). We don't currently use curl as a fallback for send operations, but
do use it for download operations, where it has significant advantages. It
can download large files directly to a file rather than having the data
temporarily stored in memory, making it able to handle some situations that
regular PHP can't.
