### ISSUE TITLE
ProcessLanguageTranslator doesn't detect translatable string 

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1598]
ProcessLanguageTranslator detects translatable string like '$this>_('
but NOT string like '$event->object->_('
for example in hooks.
Files containing this won't appear in the translatable file list.
Solution could be to change line 534
from
		$find1 = array('$this->_(',  '$this->_n(',  '$this->_x(');
to
		$find1 = array('->_(',  '->_n(',  '->_x(');
Am I missing something?

**Comment by ryancramerdesign** [comment]
While we could change that, I don't think that text would be translatable because it would be translating it from the context of the $object. And since that text wouldn't appear in the same file as the $object definition, it would might be translatable from the translation tools, but would never be translated at runtime. Within a hook (if in an object), you'd want to either use `$this->_('text')`. If your hook function is a closure, you may have to use `__('text')`, at least for compatibility with all the PHP versions PW supports.

**Comment by kixe** [comment]
got it. closed.
