### ISSUE TITLE
3.0.3 devns FileCompiler issue with new TemplateFile()

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1604]
```PHP
Parse Error: syntax error, unexpected ',' (line 120 of /site/templates/chat.php)
```

This I get when trying to instantiate a new TemplateFile from within a template like so
```PHP
$view = $this->wire(new TemplateFile());
```

And this
```PHP
Notice: Uninitialized string offset: 0 in /wire/core/FileCompiler.php on line 343
Parse Error: syntax error, unexpected '/' (line 119 of /site/templates/chat.php)
```
when instantiating without `$this->wire``

all files got a `namespace ProcessWire` at the top.

__EDIT__
I disabled template file compiling in config.php `$config->templateCompile = false;`
Now it works for me.

**Comment by ryancramerdesign** [comment]
It looks like the issue is that FileCompiler expects you are providing a filename to TemplateFile(), i.e. `new TemplateFile($filename)`. Looking at TemplateFile, it looks like providing a filename to the constructor is optional, so FileCompiler shouldn't make that assumption. I have updated it here and it'll be  committed shortly. Thanks.

**Comment by CanRau** [comment]
Sounds good, thank you :)
