### ISSUE TITLE
Save current url somewhere

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1605]
I often want to redirect to the same page I'm currently on to get rid of GET or POST data, especially when working with process modules. It always feels a bit unnecessary to reconstruct the url somehow, if it's the same, which called the current page.

**Comment by ryancramerdesign** [comment]
Assuming you are trying to get rid of GET and POST vars, you should just be able to do this `$session->redirect('./');`. As for redirecting to a query string, you can always access it from $_SERVER['REQUEST_URI'], but the trouble is that it contains user input, so you don't want to just use it as-is. Of course, PW doesn't  know how your own URLs should be sanitized and validated, that's for your code that uses the URL to determine. You can also retrieve the full URL with query string via `$input->httpUrl(true);` but again be careful because a query string that you don't generate yourself will have unvalidated user input.

**Comment by LostKobrakai** [comment]
Thanks for those hints, exactly what I looked for.
