### ISSUE TITLE
3.0.3 devns PageFrontEdit inline editing line break

### ISSUE THREAD

**Issue by CanRau** [ryancramerdesign/ProcessWire#1607]
Really like the new front end editing feature so far, great work!

The page is still in development so I'm trying different pathways. While looking at `$page->edit("username")` for example I noticed that I can press enter and therefor input a line break.
For saving it doesn't matter as it gets stripped out. But optically it looks strange to have the username move down as it's supposed to be on one line. 
Then when entering inline edit mode again, after saving the name with line break, I get the line break again, so it's kind of saving it..

Guess it should be disabled.

Tried to copy the PageFrontEdit module to /site/modules/ but after `/processwire/module/?reset=1` no hint about module copies, than I realised that PW automatically took my version from /site/modules/
guess that's okay, because if I copy one over there it's probable that I want to use it..

Anyway, know I managed to add this on line 115 of my copy of PageFrontEdit.js
```js
if (t.hasClass('pw-edit-InputfieldText')) {
	copy.keydown(function(e) {
         if(e.keyCode == 13){
              e.preventDefault();
         }
    });
}
```
this could probably be more elegant / dynamic, just tested on the one field where it's preventing line breaks..

This comment
````		
// check if orig has clickable links within it
// if so, differentiate between single and double clicks
// so that we can enable those links to still work while also supporting dblclick
````
and the following code imply that, if the editable area doesn't contain any link, it should be possible to edit the content with a single click, right?
Would be nice to allow single click, too. Maybe manually :)

**Comment by TomS-** [comment]
Single click isn't a great idea. For one all of the ways to get into edit mode should remain consistent. We shouldn't have one being single click and others being double. 

Also a double click is a much more defined movement than a single. That way we know exactly what they are intending to do. What if they just want to highlight some text?

**Comment by CanRau** [comment]
Guess you're right. Right now I changed user profile settings to be on a seperate page without inline edit.

But still, the main purpose of this issue is single text field shouldn't allow line breaks.. ;-)

**Comment by ryancramerdesign** [comment]
I think this is kind of the nature of browser `contenteditable` attribute support. Your solution to catch CR seems like a good one, so I'll add that–thanks. As for the output that you were getting, it seems to indicate you might not have the "entity encoder" textformatter enabled for your text field, and you should. While you are there, check the box to disable HTML in the field, and that should prevent the CRs from getting saved in your value. 

Single click vs. double click– I've been planning to add an attribute where one can configure this, because there may be cases where single click makes sense... like if you've defined your own edit button/link. I'll plan to add this when the next round of updates goes into PageFrontEdit.

**Comment by CanRau** [comment]
Great :-)
