### ISSUE TITLE
3.0.5: Repeater item labels not showing

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWire#1612]
The default is shown for me even when this is filled in.

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Maybe I need to use the same custom label format as you – what's the label format you are using?

**Comment by cb2004** [comment]
I can put anything in and it wont show. Even a simple 'Hello'. I have updated to 3.0.5 and its still the same.

**Comment by ryancramerdesign** [comment]
You would need to either have just a single field name like "title", or
have some "{field}" reference in there, like "{title}" or "Event {n}:
{title}". I don't think just a single "Hello" would work because it would
think you are referring to a field name, and I'm assuming there's no field
named "Hello". You might have already tried this, but wanted to mention
just in case?

**Comment by cb2004** [comment]
I put this in 'Slide #n {fake}' and it works, but that seems a bit silly, just Slide #n should work dont you think?

**Comment by ryancramerdesign** [comment]
Okay, I understand what you mean now. I have pushed a fix for this. Thanks.

**Comment by cb2004** [comment]
Confirmed fixed!
