### ISSUE TITLE
Images in repeaters are not editable (crop, resize, variations)

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/ProcessWire#1616]
There are 2 issue about this: but didn't see any answers for both, i think maybe it missed. I will close my old issue report.

Here are issue reports about image fields inside repeaters :

https://github.com/ryancramerdesign/ProcessWire/issues/1551
https://github.com/ryancramerdesign/ProcessWire/issues/1567

**Comment by ryancramerdesign** [comment]
Support for editing functions of images in repeaters wasn't intended. There's a lot more variables for this case, due to parent window JS updates and other factors. With repeaters fresh on the mind, I'll take a closer look at this over the next week to see if it might be possible somehow or another.

**Comment by LostKobrakai** [comment]
With the option of editing single field in a modal (frontend editing) this could be an option for such cases as well. Maybe one could even select which fields of a repeater item should be only editable in a modal.

**Comment by adrianbj** [comment]
I would agree that image editing repeaters is critical functionality. Same goes for when Profields Table supports images - I think the modal option suggested by @LostKobrakai is not ideal, but definitely a lot better than no support at all so I support that for now.

**Comment by adrianbj** [comment]
Just an addition to this and something I hadn't noticed because I haven't used repeaters in a while. 

https://processwire.com/talk/topic/11315-repeater-cant-edit-image-after-saving/
"I have a peculiar issue: I am using a repeater which contains an image field. I can upload and then edit (crop, resize...) an image, but after saving the page once the editing function is no longer available. The crop icon completely disappears."

I didn't realize that cropping etc worked on initial upload - I think that makes it particularly confusing when it doesn't work later on when editing.

**Comment by trk** [comment]
On my side with last devns updates this function is working. Repeaters loading via AJAX.

![ekran resmi 2016-01-27 13 14 31](https://cloud.githubusercontent.com/assets/455983/12611918/fdced7f8-c4f7-11e5-807a-e1f51b911676.png)

**Comment by ryancramerdesign** [comment]
Yes this is something I've been working on, but it's not fully functional
just yet. Well it is, but you'll have to save the page before you see the
changes populated in the field. The part that's not working is the
javascript updating of the field when the modal window closes... and I
couldn't figure that part out, so will have to return to it later.

**Comment by esl51** [comment]
3.0.98 - only superuser can make crop/focus/variants of images in repeater fields. Is there any workaround for other users?

**Comment by Nukro** [comment]
Same problem as @esl51 and also using v. 3.0.98. Is there still no workaround or fix?

**Comment by somatonic** [comment]
A workaround is to open up the repeater template (filter system templates), and set the permissions for the editor, after that repeater and repeater matrix image editing works again. At least in my short test.
