### ISSUE TITLE
Change file extension for modules from .module to .php

### ISSUE THREAD

**Issue by skidr0w** [ryancramerdesign/ProcessWire#1638]
Why do modules have a special file extension after all. When using the proper file extension for PHP files text editors can chose the correct syntax highlighting automatically. There are more good reasons, why the correct file extension should be used, but I don't know any reason, why the file extension should be .module.

**Comment by wanze** [comment]
I may be wrong, but you should be also to use `yourModule.module.php`. `.module` is used by ProcessWire to recognize module files.

**Comment by mikerockett** [comment]
I switched to `module.php` so GH would pick up on syntax highlighting. I prefer having `.module.` as modules with lots of files can often have similarly-named files, and so this sets it apart. If we switch over to Composer auto-loading modules, then this won't be required, in my opinion.

**Comment by ryancramerdesign** [comment]
PW needs ".module" in the filename to recognize it as a module file rather
than some other kind of PHP file. However, it doesn't care if you append
".php" to it as well. I usually prefer just ".module" because it's shorter,
and everywhere I use syntax highlighting, it's recognized by presence of
`<?php` tags rather than by file extension. But some prefer ".module.php"
and that's fully supported.
