### ISSUE TITLE
3.0.5 Reno Theme Custom Styles

### ISSUE THREAD

**Issue by Notanotherdotcom** [ryancramerdesign/ProcessWire#1640]
For some reason, custom styles that I add in my site/modules/AdminTheme/AdminThemeReno/styles directory no longer show up as options in 3.x

These things: https://processwire.com/blog/posts/processwire-2.6.8-brings-new-version-of-reno-admin-theme-and-more/#custom-color-schemes

Since they're literally just CSS files I don't think it's a namespace issue :)

**Comment by ryancramerdesign** [comment]
Thanks Pete, I have pushed a fix. It actually was a namespace issue, as the code in there used `__CLASS__` as part of the directory name where it looks for css files. In a namespaced environment that constant includes the namespace and the class name (rather than just the class name). I changed it to `$this->className()` and that seems to have fixed it.

**Comment by isellsoap** [comment]
@Notanotherdotcom Can you close this issue please? Thank you!

**Comment by isellsoap** [comment]
@ryancramerdesign Since @Notanotherdotcom doesn’t close this issue, could you do it please? Thank you!
