### ISSUE TITLE
tried the new abstract link... error

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1647]
I tried the abstract link, I checked 1,2 and 4 of the new options on a field and hit Apply:

On one of the (multi language text area) fields, I hot this error:
 SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name1505' in where clause is ambiguous

**Comment by tbba** [comment]
If the reason is nonworking links within the field, this is maybe why:
I had just recently changed the default language url from "/" to "/de/" - which is better for my SEO setup.
There are still old links in that fields that do not carry the updated language information yet.
I would be happy if that error is catched instead of blocking the saving or pages.

**Comment by ryancramerdesign** [comment]
I've been trying to reproduce this error for a good half hour on my 3-language site, but just not able to yet.  I did the same as you, changing the default language url, and trying to get it to fail on outdated links. Do you have a good idea of what link it might be failing on? I guess I need more instruction on how to reproduce it, since I've struck out so far. I'm running my site off a subdirectory "/test/" is my web root, if it matters (it's possible that's preventing me from seeing the error, hard to say). 

One thing I did do is go looking for potential ambiguous columns in the new $pages methods (per the error message you mentioned), and I found a spot that's might be a worth an experiment, if you are still able to reproduce the error. If you want to try it, try changing /wire/core/PagesLoader.php line 825 from this:
`````
$wheres[] = "$colName=$bindKey";
`````
to this:
`````
$wheres[] = "pages.$colName=$bindKey";
````

**Comment by tbba** [comment]
No this did not help,, unfortunately:
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pages.pages.name' in 'where clause' 

Meanwhile the error from the one field is gone. Maybe I have caught all links already and corrected them.
But there is a buggy field left, so we can try there.

**Comment by ryancramerdesign** [comment]
Ah, but sounds like progress. Try removing the line right before the one I
had you update, that's where the pages.pages.name is coming from I think...
That line can be removed now.

**Comment by tbba** [comment]
OK - no errors any more!!!
Just to clarify, I did this, according to the instructions:

`			$wheres = array();
			foreach($langKeys as $bindKey => $colName) {
	///			if($colName === 'name') $colName = 'pages.name';
	///			$wheres[] = "$colName=$bindKey";
				$wheres[] = "pages.$colName=$bindKey";
				
				$binds[$bindKey] = $lastPart;
			}`

Since I cannot be 100% sure whether the fix worked, or I had eliminated the problem by having replaced tons of hardcode links by the AutoLink Pro Module in the meantime, I try now installing and testing on another website.

**Comment by tbba** [comment]
The other domain had normal links (many!) but no language textarea fields.
Anyway: No errors, everything run smoothly. Looks like the problem is gone.

**Comment by tbba** [comment]
How do I see that it works? I thought I would now have new data-something attributes with the links?

**Comment by ryancramerdesign** [comment]
Great thanks for testing it out @tbba, glad that it works. Truly a remote debugging session! It actually makes sense now that I see it all there. Though still not sure why I couldn't reproduce it, so glad that you were able to.

> How do I see that it works? I thought I would now have new data-something attributes with the links?

The best way to tell that it's working is to put it to the test. Change a linked page name or move it, then go and edit a page linking to it. Double click the link in CKEditor to confirm that it's pointing to the new location. 

An alternative is to edit the /wire/core/MarkupQA.php file and change the `const debug = false;` to `true` at the top of the file. Then it will tell you very verbosely everything it is doing whenever it loads or saves the page. That's primarily for core development purposes so I can confirm it's doing all it should.

**Comment by ryancramerdesign** [comment]
Btw, the data attributes are added when the page is saved (via Fieldtype::sleepValue) a removed when the page is loaded (via Fieldtype::wakeupValue). **So you won't ever see the data attributes**, unless you look in PhpMyAdmin or a DB dump file or something. I opted for the data attribute so that it would remain HTML compatible if someone ever needed to export the data for usage elsewhere, so that it wasn't creating proprietary/non-compliant HTML.

**Comment by tbba** [comment]
Very cool. That explains it. Very clever!
