### ISSUE TITLE
FileCompiler error with variables $require_once, $include - 3.0.6

### ISSUE THREAD

**Issue by rolandtoth** [ryancramerdesign/ProcessWire#1649]
Using "$include = 1" in a template file causes this error:

> Parse error: syntax error, unexpected 'include' (T_INCLUDE), expecting variable (T_VARIABLE) or '$' in /my_path/site/assets/cache/FileCompiler/site/templates/search.php on line 21

The compiled file part looks like this:

`$ include(\ProcessWire\wire('files')->compile(=/my_path/site/templates/ 1,array('includes'=>true,'namespace'=>true,'modules'=>true)));`

Same with $require, $require_once, $include_once.

I found the $include variable in a non-PW component used in my PW project so I have no influence on the variable naming - and probably such variables exist elsewhere too.

**Comment by ryancramerdesign** [comment]
Thanks @rolandtoth I've pushed a fix for this issue.

**Comment by rolandtoth** [comment]
Works fine now, thanks!

Btw, is there a way to tell an included file not to be processed by the file compiler?
(that is, to use it as it is, without modifications)

**Comment by LostKobrakai** [comment]
I think setting a namespace would have that result.

**Comment by adrianbj** [comment]
> Btw, is there a way to tell an included file not to be processed by the file compiler?
> (that is, to use it as it is, without modifications)

You could change the "Use Compiled File" setting on the template's "Files" tab.

Or do you want/need to do it from the included file itself? In that case I am guess setting a namespace like @LostKobrakai suggested would work.

**Comment by rolandtoth** [comment]
My template file has namespace "ProcessWire", and it loads a custom class also namespaced as "ProcessWire". This class includes a third party file where namespace is also set (not PW, obviously).

I also tried setting the namespace of my custom class other than "ProcessWire" but no success.

I tried setting "Use Compiled File" to None at template level and globally in config.php, "$config->templateCompile = false".

In all cases above PW created a modified copy to the FileCompiler folder.

My fear is that if PW's filecompiler processes every included files (even if coming from third party) that's very error-prone. Of course I may be overlooking something as my OOP knowledge is limited.

**Comment by ryancramerdesign** [comment]
Setting a namespace in your file automatically disables compilation for modules, but not for template files. That's because the only reason to compile a module is for PW3 compatibility, whereas there may be many reasons why you'd want to compile a template file. 

To disable compilation of template file(s), do one of the following. After doing it, go to Modules > Site > Clear compiled files (or if you prefer, remove the /site/assets/cache/FileCompiler/ directory). 

- To disable compiled template files entirely, in your /site/config.php set `$config->templateCompile = false;`
- To disable compilation for a single template file, see the settings while editing your template in Setup > Templates > Files. 
- You can also disable compilation of any file just by adding the string `FileCompiler=0` anywhere in it, typically in some PHP comment. For example, if you had a phpdoc comment at the top, you might do it like this:

``````
/**
 * Some file description
 *
 * FileCompiler=0 (this disables PW compilation of this file)
 */
``````

It sounds like you might have tried a couple of these options above and still seen it use the compiled files? Let me know if that's still the case after doing a Modules > Site > Clear compiled files (this button is at the bottom).

**Comment by rolandtoth** [comment]
Setting "FileCompiler=0" in my custom class made the trick, thanks. I read about this setting before but couldn't find anywhere.

Now I use namespace ProcessWire in my class but the class and its included files do not appear in the FileCompiler cache directory.

**Comment by isellsoap** [comment]
@rolandtoth Can you close this issue please? Thank you!
