### ISSUE TITLE
Enabling link abstraction and checking "apply HTML options now" results in an error

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1651]
This is what I got after enabling link abstraction on my body field, checking "apply HTML options now", and saving field settings:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pages.include' in 'where clause' now

This happens every time I try to leave the "apply now" setting on. I'm running this as the superuser, but please let me know if there's anything else you need to know.

Additionally I can't seem to get the abstraction feature to work at all. Might be an unrelated issue, so just mentioning this; it doesn't add the data-attributes on page save and changing internal URLs results in 404's.

**Comment by teppokoivula** [comment]
Update to the "link abstraction not working at all" part: for some reason converting the field to regular textarea and then re-enabling CKEditor fixed this issue for me. Not sure what that was about, but it seems to be working now.

**Comment by ryancramerdesign** [comment]
@teppokoivula any idea what the "pages.include" is? I don't think that's coming from the PW core (though can't say for certain, but it doesn't look familiar). So I'm wondering if it might be coming from another module or something. If it's possible to see a debug backtrace of the SQL error, that might point to where we should look next. 

Do you see an SQL error if you go and edit a page with internal links on it, make some change in the textarea field (can be anything, like adding a "hello world" at the end), and then save?

You might also try editing the /wire/core/MarkupQA.php file and changing the `debug=false;` to `true`, temporarily. That will make it be very verbose about everything it is doing. 

> ...it doesn't add the data-attributes on page save...

The data attributes are added when the page is saved (via Fieldtype::sleepValue) a removed when the page is loaded (via Fieldtype::wakeupValue). So you won't ever see the data attributes, unless you look in PhpMyAdmin or a DB dump file or something. I opted for the data attribute so that it would remain HTML compatible if someone ever needed to export the data for usage elsewhere, so that it wasn't creating proprietary/non-compliant HTML.

**Comment by ryancramerdesign** [comment]
Ah what do you know, I think I just found it. Just committed something that I think will fix it. When you have more than 300 pages to apply the change to, it appends a "limit" to the selector, and I was missing a comma in that selector. My test case had fewer than 300 pages to apply at once. Can yo confirm if this fixes it on your end? Thanks.

**Comment by teppokoivula** [comment]
Fixed, not seeing the error anymore. Thanks!

On a related note the notice I'm seeing now feels a bit uninformative; what exactly does "Updated 0 out of 568 pages for HTML options" mean? Was there a reason it couldn't update any of these pages, or does it simply mean that they didn't have anything to update? I'm guessing it's the latter case, but not positive.

It would also be cool to see some kind of indicator about how many times I might need to re-check the setting and save. On this site it's not such a big deal, but it could get a bit awkward on sites with at least a few thousands of pages. Perhaps not the most common use case, though, so feel free to ignore this.

> The data attributes are added when the page is saved (via Fieldtype::sleepValue) a removed when the page is loaded (via Fieldtype::wakeupValue). So you won't ever see the data attributes, unless you look in PhpMyAdmin or a DB dump file or something.

Checked directly via DB, so this doesn't seem to explain it. Taking a closer look at MarkupQA, it seems to add tabs before and after the data attribute; the weird thing is that I was actually seeing those, just not the data-part. Could of course be that they were a leftover from somewhere else, can't be 100% certain.

Here's an excerpt from the field_body table (tab replaced by four spaces, the GitHub editor keeps converting it to single space):

```
<p><em>If you know of a great resource we haven't mentioned yet, <a    href="/feedback/" target="_blank">let us know</a>.
```

My first thought was that perhaps the HTML Purifier didn't like the data-attribute, that's why I tried disabling it (with CKEditor) in the first place. Anyway, that issue is gone now, so perhaps it was just some random glitch.

**Comment by ryancramerdesign** [comment]
The tabs are intentional, and also part of the sleep/wakeup for the fieldtype. It's what enables it to quickly determine what the href attribute is relative to. The tabs before an attribute are just MarkupQA's way of identifying attributes that are likely its own. Of course, tab is just whitespace to HTML, so it remains valid to HTML (if you export it from PhpMyAdmin). Though you'll never see the tabs anywhere but in the database, since they are converted to normal space by wakeupValue(). 

CKEditor won't mind the data-pwid attribute, since it'll never see it. Like the tab, that attribute only appears in the database, not in any runtime values. 

The "Updated 0 out of 568 pages" means that no pages needed to be changed in order to apply the link abstraction. You would see that if you had already applied the link abstraction to everything, or if the 568 pages literally had no links to abstract. 

The 568 pages are those where it found a possible "href" or "src" attribute in the textarea field and it hasn't already had the HTML updated for it. Meaning, pages that *might* still need the HTML updated for link abstraction. But it can't really tell for sure until it takes a close look at them. Since you are seeing "0", that means those pages had an href|src attribute, but didn't end up needing further updates. The 0 means you are done with the Apply, and there's nothing more to do. 

In a link abstraction that takes multiple times, you'd see "Updated 300 out of 568 pages", and you'd keep running the apply until it showed "0 out of [n] pages". Since it only does 300 pages at a time, that means you'd likely have to run it twice before you saw that. I chose 300 just to limit any possibility of running out of memory on sites with lots of pages. 

> It would also be cool to see some kind of indicator about how many times I might need to re-check the setting and save.

The "updated [n] out of [total] page" is that indicator. Though that's as much information as it knows. It doesn't have a way of knowing for sure how many times you might need to run it, since it depends on factors that are only known once those pages it found are loaded an analyzed. Though if it finds fewer than 300 pages that "might" need updates, it's not going to need to run more than once. Btw, there's no harm in running at multiple times.

**Comment by teppokoivula** [comment]
Thanks.

I get that the tabs are intentional, was just pointing that for some reason there were tabs in the db, but no data-attributes, which seemed quite strange. This was fixed after I converted field from Purifier-enabled CKEditor to textarea and back again, which led me to wonder if it could be related to one of those.

Purifier has caused me various weird issues in the past, so it seemed like a probable culprit, but if the data-attributes never go through it then it's probably not that :)

It's also obvious that running the markup check multiple times is not a problem. My point was that it's not obvious when it's going to be done, and if you've got, say, tens of thousands of pages, it gets a bit silly when you have to keep checking the option and saving the field and there's no way to know how long you still have to keep doing it. Anyway, like I said before, this probably isn't a very common use case.

> The 0 means you are done with the Apply, and there's nothing more to do.

I would suggest adding this to the message, in some form. In my opinion current message is ambiguous in this regard: it's not obvious whether 0 is intended result, or a result of some sort of problem.

**Comment by ryancramerdesign** [comment]
Teppo, I've updated it to be more verbose with the reporting about what its
doing, as well as telling you when you do or don't need to continue running
apply. I don't yet have any guesses on why you had to remove CKEditor and
add it back, but it doesn't sound like expected behavior. I've not been
able to duplicate that one yet, but will keep an eye out to see if anyone
else runs into the same thing.

**Comment by teppokoivula** [comment]
Thanks, Ryan :)
