### ISSUE TITLE
File compiler not handling class_exists

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1658]
Not sure if this is an omission or expected behavior. It's quite possible I am missing something. I would have expected that:
```
if(class_exists('ProcessModuleInstall')) {
```
would get compiled to:
```
if(class_exists('\ProcessWire\ProcessModuleInstall')) {
```

As it stands it seems like I need to check both to make compatible with PW 2.x and 3.x

PS - this is in a module

**Comment by ryancramerdesign** [comment]
I think that class_exists() will always fail, unless ProcessModule is loaded. The ProcessModuleInstall class is one that is just used by ProcessModule, so it's not one that FileCompiler is looking for. The same goes for any other classes that are just single purpose helper classes used by modules. 

Because I think your class_exists() will likely always fail regardless of how you do it (unless you are hooking into something in ProcessModule), I would suggest a different approach. For instance, if you are wanting to know of the ProcessModuleInstall class might be available, check if the file exists:
```````
$file = $config->paths->ProcessModule . 'ProcessModuleInstall.php';
if(file_exists($file)) {
  // ... 
}
```````
If your need really is to see if the class is present (rather than something like the above) then you would want to check both, as you indicated above.

**Comment by adrianbj** [comment]
Thanks Ryan,

It's not really a problem to check both.
