### ISSUE TITLE
3.0.7 vs. 2.7.2: $input saved in $session does not work anymore

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#1678]
I would like to collect form data in a session and do a redirect afterwards. After the redirect happens, I would like to read the form data back from the session. In 2.7.2, this worked flawlessly. In 3.0.7, I can't get it to work anymore.

Here's my simple test case (save as php file). Any hints?
```php
<?php

include './index.php';

if ($input->post->submit) {
    $session->input = $input;
    $session->redirect(basename(__FILE__));
}

if ($session->input && $session->input->post) {
    // 2.7.2: echoes "1"
    // 3.0.7: echoes nothing!
    foreach ($session->input->post as $value) {
        echo $value;
    }
    $session->remove('input');
}

?>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

<form action="" method="post">
    <button type="submit" name="submit" value="1">send</button>
</form>

</body>
</html>
```

**Comment by ryancramerdesign** [comment]
I think the issue might be that you are trying to store the entire $input API var in session, and PW's $input  is not designed to be stored in a session (regardless of version). What you might want to do is instead store the individual vars from $input that you want into $session, rather than the entire thing. Also be sure you are storing sanitized data in $session. Lastly, I'd avoid using the session key of $session->input since that overlaps with PW's $input API var as is likely to cause confusion. If you literally need to use 'input' as your session key, then use a session namespace, like $session->setFor('my_namespace', 'input', $value);
