### ISSUE TITLE
handling of uploaded files and their variants

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1686]
I am running into trouble with some uploads that do not show in backend and frontend after uploading.
The error must have been introduced with some later 3.x version, because I know it worked.

1. I upload a fresh image to a field that has those settings: type:image/max. files:12/array of items/default fallback set/no tags/inputfield type: image
Thumbnail in page editor/overwrite existing:no/show rows/image-min-max dimensions are set (plugin)/no access ctr/ 
result: OK - image uploaded and shown in frontend and backend

2. I replace the image with a file with the same name, uploaded thumb shows. Hit save.
result: 
- uploading works: new image +  thumb is in the online directory (OK)
- Backend shows no image any more
- Frontend shows fallback image instead

3. Change field settings to overwrite existing:yes and upload the image again:
result:
- error: _Refused file stendal-blast-alles-liebe.jpg because it is already on the file system and owned by a different field._ (wrong! - not owned by any other field)

As a consequence I cannot upload an image any more.
If I duplicate the page with the problem, the clone page shows that images shows as thumb in the backend .

A cleanup problem? I see no errors in the safari console apart from the pesky _cke editor css.map missing_

(PW: 3.08)

**Comment by tbba** [comment]
probably related:
https://github.com/ryancramerdesign/ProcessWire/issues/1493

**Comment by tbba** [comment]
ok, this seems to be something very specific. The upload does not work (any more) only for certain pages. Uploads on other pages using the same setup (template) within the same project (website) work.

**Comment by tbba** [comment]
The problem has nothing to do with this image field directly.
It happens, if a (multilanguage) textarea field within the same template has a size-reduced image in the CKE (same image in all languages, per copy/paste inside embedded in other language withing CKE)... that thing somehow seems to screw up the image handling of other fields. (That multilanguage textarea field was set up in PW3 to handle images: fix broken images and image access control - if that matters.)

**Comment by ryancramerdesign** [comment]
I was initially looking at the issue you mentioned in #4 and #5 as that sounded like the biggest problem, but I can't duplicate that. If I upload an image with the same name as an existing one, it uploads it and appends "-1" to the file's basename. If I turn on the "overwrite" option, then it just replaces it. Note that when the "overwrite" option is on, it's going to replace the file immediately, whereas if it's off, then the file is not going to be committed to the page until you "save". Meaning, if you don't save the page, then the file hasn't technically been committed to the page yet, and the file will get deleted the next time it is loaded in the page editor. Please let me know if you are still able to duplicate this one, or if maybe I've misunderstood how to duplicate it. 

For #7, it sounds like there are multiple potentially incompatible conditions coming together there that are necessary to reproduce.  The filename of an uploaded file appears in multiple textareas (languages) and also might represent one that MarkupQA is attempting to fix, and further, the upload is directly replacing it due to the overwrite option. I think for this case, you may need to disable the "fix broken images" option, or better yet, avoid use of the "overwrite" option for the files field. The overwrite option skips over the usual save process, overwriting things immediately, so it's one of those things you've got to be careful with to make sure it doesn't interfere with other things running during the usual save process. This is the reason why the overwrite option isn't recommended. It sounds like you've found a case where overwrite would be problematic. For your case, I think it may be best to disable it.

**Comment by tbba** [comment]
I close this for now. So much changed with the images in PW3dev this issue maybe obsolete.
