### ISSUE TITLE
PageTable doesn’t store re-ordering of items in certain (weird) constellation

### ISSUE THREAD

**Issue by isellsoap** [ryancramerdesign/ProcessWire#1688]
Problem description and reproduction can be found in [this forum thread](https://processwire.com/talk/topic/12215-pagetable-doesn%E2%80%99t-store-re-ordering-of-items/).

**Comment by ryancramerdesign** [comment]
@isellsoap is it possible this issue might come down to the same thing as #1689? In the forum thread, you mentioned in one of the steps that one has to select the current page, which [if I understood correctly] creates a circular reference. PW has some measures built in at various spots to prevent a fatal error that can occur from a circular reference. The problem comes down to when a page is loading, if the data references itself, then it can create an infinite load cycle. For example, while page123 is loading it encounters a reference to page123 in the data, which in turn triggers another load of page123, which goes on to become an infinite loop. So PW detects that condition and then aborts. 

Though it may be possible that we can accommodate it with things like PageTable and Repeater, because they are technically separate pages, but I suspect PW's circular reference detection might be coming into play here somehow or another. Though if you are still able to duplicate the issue even without the circular reference, then that's not it. But was just curious if you thought these two issues might have the same roots. Thanks for outlining the steps to reproduce in the forums, I will follow your instructions to try and duplicate it.

**Comment by isellsoap** [comment]
I see the general problem with a possible infinite loop. I suppose that it’s not that easy to programmaticaly detect and prevent such a circular reference?

> Though if you are still able to duplicate the issue even without the circular reference, then that's not it.

No, only if there is (at least one) circular reference, then the re-ordering does not work correctly. If there isn’t a circular reference in any of the repeater items, than everything works as expected.

Thank you for looking into it.

**Comment by isellsoap** [comment]
I think one way to "solve" this issue on your part is to not allow circular references in page fields that are inside of repeater fields. This is, as described above, possible.

**Comment by ryancramerdesign** [comment]
Well, it's not really a circular reference if it's in a repeater field (at
least it's a very different one), because repeaters are pages themselves,
and the reference isn't the repeater referencing itself. So we actually may
be able to support that kind of reference here. But I think that the
current circular reference detection just doesn't know how to tell that,
because the page it's comparing to is the one being edited (the one the
repeater field lives on) rather than the repeater page itself. It may be a
little too complex scenario to support without getting a lot of code
involved, but I'll definitely be looking into it here.

On Mon, Feb 15, 2016 at 6:24 AM, Francesco Schwarz <notifications@github.com

**Comment by isellsoap** [comment]
I see. Than it would be really interesting to know why such a "page field inside a repeater field with selection of current page" scenario does have such a weird effect as to not allowing PageTable items to be re-ordered. 

Thank you for looking into it, it is very much appreciated.

**Comment by isellsoap** [comment]
Not reproducible anymore with latest ProcessWire version (3.0.34).
