### ISSUE TITLE
content tab is not in active state under "modules" tree

### ISSUE THREAD

**Issue by sunlix** [ryancramerdesign/ProcessWire#1694]
Hi,

I've notices on 2.7.3 dev that the content tab (first tab on page) is not in active state.
This behavior is on every page under "modules" tree. (permissions, roles etc.)

![screen-tab-not-active](https://cloud.githubusercontent.com/assets/301885/13120807/b4378e8c-d5af-11e5-960d-d39459b390b9.png)

regards,
Sven

**Comment by adrianbj** [comment]
Just a quick note to say that everything seems fine for me on the 3.x branch of PW, so if this is an issue on 2.7.3, then it has been fixed on 3.x. 

I know you say it's every page under the - I assume you mean "Access" rather than "Modules" menu, but remember that it is intentional for the guest user because this can't be renamed. Same goes for the superuser role, and any of the built-in user permissions. I can still rename my custom user permissions just fine.

**Comment by isellsoap** [comment]
@sunlix Can you close this issue please? Thank you!

**Comment by sunlix** [comment]
okay it seems to be fixed at branch **devns** (3.x)
