### ISSUE TITLE
Feature request: Adding execute methods to Process modules through hooks

### ISSUE THREAD

**Issue by BitPoet** [ryancramerdesign/ProcessWire#1721]
Currently it isn't possible to add custom executeXXX methods to Process modules through addHook, as getProcessMethodName checks if an aptly named method can be found through method_exists. Relevant code:
`if(method_exists($process, $method) || method_exists($process, $hookedMethod)) return $method;`
This could easily be fixed by also checking for a hook with that name:
`if(method_exists($process, $method) || method_exists($process, $hookedMethod) || $process->isHooked("{$method}()")) return $method;`
I hope I haven't missed the obvious.

**Comment by ryancramerdesign** [comment]
Good idea @BitPoet I will go ahead and add this. Though we'll want to use the `hasHook()` rather than `isHooked()` method. The isHooked() method is basically a quick optimization check that indicates something might have a hook... by that I mean, some method with the name has that hook somewhere, but not necessarily in the current class. Whereas hasHook() says something definitely has a hook in the current class.

**Comment by BitPoet** [comment]
Cool, thank you, Ryan! This will make some of the modules I'm working on a lot more concise. And thanks too for the explanation, I've encountered both methods but the differences flew past me.
