### ISSUE TITLE
Lister click actions

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1730]
I'm not sure if javascript can detect this, but I'm often using middle-mouse button to open links in a new tab (or cmd+click). When used on lister items this just does open the same lister again in another tab, which is not only not my intend, but can also be a quite resource heavy request. Could this default to editing the clicked page?

**Comment by yckart** [comment]
The javascript part is a simple `event.button === 1` check. Some old browser (IE < 9) uses `event.which` instead and other values to compare against...

```js
// W3C-Standard
event.button === 0 // left
event.button === 1 // middle
event.button === 2 // right

// Microsoft
event.which === 1 // left
event.which === 4 // middle
event.which === 2 // right
```
https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/events.html#Events-eventgroupings-mouseevents

**Comment by ryancramerdesign** [comment]
Not sure that I follow. What is it exactly what you are clicking on? I don't have a middle mouse button, but cmd+click on the "edit" link for any page opens in a new tab for me. I tried cmd+click of the page label (rather than action), just in case that's what you mean, but it just opens the "edit, view, move" actions.

**Comment by LostKobrakai** [comment]
You were correct in your assumption that I might be clicking the page label, but middle mouse button clicks actually open a new tab with the same lister instead of toggling the actions.
