### ISSUE TITLE
Pages::add() and PagesType::add() alignment

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1732]
It would be nice if both Pages::add() and PagesType::add() would align more in terms of functionality. Currently the latter does miss the option to set values by a data array and it does return a NullPage instead of throwing an exception. While it's internally not the case I see both classes as the same kind of pages repository only different by how restricted they are, which is why I think this should be aligned.

**Comment by LostKobrakai** [comment]
This can be used by custom PagesType classes.

```php
	public function ___add ($name = '', array $values = array(), $throw = false)
	{
		// the $values may optionally be the 1rd argument
		if(is_array($name)) {
			$values = $name;
			$name = isset($values['name']) ? $values['name'] : '';
		}

		if(empty($values['title'])) {
			// no title provided in $values, so we assume $name is $title
			// but if no name is provided, then we default to: Untitled Page
			if(!strlen($name)) $name = $this->_('Untitled Page');
			// the setupNew method will convert $page->title to a unique $page->name
			$page->title = $name;

		} else {
			// title was provided
			$page->title = $values['title'];
			// if name is provided we use it
			// otherwise setupNew will take care of assign it from title
			if(strlen($name)) $page->name = $name;
			unset($values['title']);
		}

		$p = parent::___add($name);

		$exceptionMessage = "Unable to add pagestype new using parent '{$page->parent->path}'.";

		if($p instanceof NullPage && $throw) throw new WireException($exceptionMessage);

		// set field values, if provided
		if(!empty($values)) {
			unset($values['id'], $values['parent'], $values['template']); // fields that may not be set from this array
			foreach($values as $key => $value) $page->set($key, $value);
			$this->save($page);
		}

		return $page;
	}
```

**Comment by ryancramerdesign** [comment]
These aren't really meant to be functionally the same as that in the Pages class, and you'll see that the same is true of most methods. (PW uses the similar method names in a lot of classes). PagesType classes are really specific and thus more limited, whereas the Pages class is where all the action and additional options are meant to take place. But if there's a need for the add() method to work the same here, I also don't see any harm in it so long as it's not introducing any new issues or breaking compatibility. It doesn't look like it does, so that's good, I'd be fine with updating this. One question though, why not just have this in the PagesType class? It looks like you are suggesting this for something like the Users class? (due to the parent::___add() call)? I'm thinking it would be better to just put it in PagesType.php so that similar code isn't being duplicated among the core's other PagesType classes, but I might also have misunderstood what you meant.

**Comment by LostKobrakai** [comment]
The code sample above was rather a "fix the thing not available in the core". At best it's surely part of the PagesType class.
