### ISSUE TITLE
Missing array_merge in PageFinder::getQuery??

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1734]
Not sure on this, but I wonder if:
```
$options = array_merge($this->defaultOptions, $options);
```
should be added to the top of the getQuery function. I noticed that without it, if you try do the following:
```
$selectors = new Selectors("template=basic-page, limit=1000000");
$pagefinder = new PageFinder();
$sql = $pagefinder->getQuery($selectors->getArray(), array())->getQuery();
```
you get an "Undefined index: returnVerbose" notice. 

Obviously you could do this instead:
```
$sql = $pagefinder->getQuery($selectors->getArray(), array("returnVerbose" => true))->getQuery();
```
but wonder if the defaults should be populated to this function?

**Comment by ryancramerdesign** [comment]
Adrian, the getQuery() method is a protected method, not meant to be called from outside of the PageFinder class. That's why it relies on the find() method to initialize the $options. Because it's hookable, it still has to be callable by the hooks system, but it's not meant to be used as a public method.
