### ISSUE TITLE
InputfieldCKEditor not found in AdminTheme.php

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1746]
While testing with the latest version of the devns branch, I couldn't get page editor to open. The issue was this:

> Error: 	Class 'ProcessWire\InputfieldCKEditor' not found (line 175 of /some-path/wire/core/AdminTheme.php)

Said row is here:

```
                'ckeditor-' . InputfieldCKEditor::CKEDITOR_VERSION . "/';</script>";
```

After changing it to this, everything started working again:

```
                'ckeditor-' . \InputfieldCKEditor::CKEDITOR_VERSION . "/';</script>";
```

Any idea what's going on here?

For the record, this environment is running PHP version is 5.3.10 (with security patches from Ubuntu), which could be a factor here, in case some namespace-related bugs have been fixed from PHP in 5.4 or 5.5.

Another thing to note is that in this case the wire directory is actually a symlink. So far I've experienced no issues related to this in any earlier version, just mentioning it since in case this matters.

So far everything else seems to function as expected.

**Comment by ryancramerdesign** [comment]
That's odd because InputfieldCKEditor is in the ProcessWire namespace, not
the root namespace. The line where you added the "\" before it should cause
a fatal error, since it's referring to a class that doesn't exist in PW3
(root namespace InputfieldCKEditor).

I think there's a good chance you've got another copy of InputfieldCKEditor
floating around somewhere? Check your /site/modules/ just in case, and also
double check that you don't have a merged /wire/ directory from 2.7 + 3.0.

**Comment by teppokoivula** [comment]
@ryancramerdesign Thanks! Actually I had multiple versions of CKEditor, one under the /site/modules/ directory and another one under the /wire/modules/ directory. After switching to the one in the wire dir, this issue is fixed.

Looks like this kind of setup is no longer supported – thanks for the swift reply! :)

**Comment by ryancramerdesign** [comment]
That setup is supported, but–at least in the case of CKEditor–the modules
would have to share the same namespace (i.e. \ProcessWire) since the
AdminTheme references it directly. The one in your /site/modules/ directory
sounds like it was in the root namespace, which is why you had to update
that AdminTheme file to reference it rather than the core one.

**Comment by teppokoivula** [comment]
@ryancramerdesign right, "not supported" was bad choice of words. "Supported, at least as long as the modules are in the same namespace" is closer to the truth :)
