### ISSUE TITLE
Uncaught exception while loading image from remote host

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/ProcessWire#1754]
I am rinning a cli php import script, that creates pages with imagefields, getting images directly from Amazon S3. The script runs for some time (and creates a bunch of pages as expected) and fails with an error:
```
2016-03-16 18:41:14     guest   /http404/       Error:  Uncaught exception 'WireException' with message 'Unable to copy: http://s3-eu-west-1.amazonaws.com/***/full/486656a84e592162a6ce80a5e7a9716803afd825.jpg => /home/s/***/***.ru/public_html/site/assets/files/11490/486656a84e592162a6ce80a5e7a9716803afd825.jpg' in /home/s/***/***.ru/public_html/wire/core/Pagefile.php:117 
Stack trace: 
#0 /home/s/***/***.ru/public_html/wire/core/Pageimage.php(1012): Pagefile->___install('http://s3-eu-we...') 
#1 [internal function]: Pageimage->___install('http://s3-eu-we...') 
#2 /home/s/***/***.ru/public_html/wire/core/Wire.php(397): call_user_func_array(Array, Array) 
#3 /home/s/***/***.ru/public_html/wire/core/Wire.php(332): Wire->runHooks('install', Array) 
#4 /home/s/***/***.ru/public_html/wire/core/Pagefile.php(83): Wire->__call('install', Array) 
#5 /home/s/***/***.ru/public_html/wire/core/Pagefile.php(83): Pageimage->install('http://s3-eu-we...') 
#6 /home/s/*** (line 117 of /home/s/***/***.ru/public_html/wire/core/Pagefile.php)
```
As I understand, there is a 404 status error getting that photo (due to some technical issue - the photo is actually there).

Of course I'd rather download images to localhost, but don't have enough space. Anyway, shouldn't PW handle the exception?

Or am I totally misunderstanding what is going on here?

**Comment by wanze** [comment]
The exception is thrown here: https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/core/Pagefile.php#L117

I guess that if you are bootstrapping ProcessWire in a CLI script, this exception isn't caught by the system. You can do it yourself by surrounding the relevant code creating the page image with a `try/catch` block. Btw I didn't know that you could import images this way :)

**Comment by ryancramerdesign** [comment]
Trying to add an image that can't be found is considered a fatal error here, so the exception is intended. When bootstrapping PW, the exceptions are left for you to decide what you consider fatal and what you don't, since there is no PW admin interface to display these things to you. So in the case of your cli script, if you don't consider a 404 for the image to be a fatal error your best bet is to wrap it in a try/catch like @wanze mentioned. For example:
```````
try {
  $page->images->add($url);  
  $page->save();
} catch(Exception $e) {
  // maybe display $e->getMessage();
}
`````````

**Comment by ivangretsky** [comment]
I think it's clear. Let's close it.
