### ISSUE TITLE
Bootstrap backwards compatibility in 3.x ($wire and wire())

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#1764]
Hi @ryancramerdesign!

I'm currently updating some sites to 3.x and having some problems with the way the bootstrap process works. Previously the most reliable way to call the API was via wire() function, but apparently that's no longer available when bootstrapping 3.x.

This breaks all the existing bootstrap scripts I've got, and sadly there are plenty of those in this particular environment. Currently it seems that I'll have to go through each and every one and add some additional checks to figure out whether I should to use $wire or wire() for a specific site. First one is a lot of work I'd prefer to avoid, second one adds complexity to both bootstrap scripts and even some existing modules.

While I get that a global wire() function is a logical problem when bootstrapping multiple instances of ProcessWire, is there any chance this could be made available for backwards compatibility?

For these use cases it would be fine for wire() to refer to the first or last instance bootstrapped in case someone attempts to load more than one of them. Since this would be for backwards compatibility, this won't actually make any difference, considering that multi-instance support wasn't available back then.

Thanks for considering this, and please let me know if I'm misunderstanding the situation and there *is* actually some deeply technical reason why this can't be added :)

**Comment by ryancramerdesign** [comment]
Teppo actually there is still a global wire() function, but it's in the ProcessWire namespace, rather than the root namespace. So the files you mentioned would work if they had a `namespace ProcessWire;` at the top, but otherwise they'd need to reference `\ProcessWire\wire()` rather than `wire()`. I'm not suggesting you change all your files or wire() calls though. We're trying not to put anything in the root namespace in PW3, but it should be fine to do on individual installations. I'm thinking you might put one in your /site/init.php file (or another file include'd from it): 
``````
<?php
function wire($key) {
  return \ProcessWire\wire($key);
}
``````
Just tested this out with a bootstrapped script and it works nicely. Let me know if this also solves the issue there?

**Comment by teppokoivula** [comment]
@ryancramerdesign: thanks for explaining the situation! :)

While I'm not entirely convinced that $wire being in the global namespace is OK while wire() being there would be a problem, I think I'll just modify aforementioned scripts to use $wire. For me consistency is of key importance, and assuming that $wire is always going to be available and wire() isn't, that in itself is a very good reason to do some extra work at this point.

Another use case I have happens to be a module that requires a separate script initiated by cron or exec. Again I think it's better to go with $wire, so that the module will work right out of the box in case someone else finds it useful too. To be honest I've always used wire() in bootstrap scripts and didn't even remember that $wire is also always available :)
