### ISSUE TITLE
MapMarker Module on PW3

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1767]
After updating another Site to PW3 which uses MapMarker with its basic settings the maps do not load any more. _Syntax error: invalid escape in identifier..._

I think the compiler screwed up some JS like so:

**new  \ProcessWire\MarkupGoogleMap()**

I think the namespace code part (?) does not belong to the JS code, correct?

**Comment by ryancramerdesign** [comment]
Just tried to install FieldtypeMapMarker and MarkupGoogleMap in PW3, but not seeing those errors from the FileCompiler. What version of PW3 are you running? Technically that `new \ProcessWire\MarkupGoogleMap()` that you mentioned shouldn't be able to occur since `MarkupGoogleMap` isn't in the ProcessWire namespace, and FileCompiler skips over class instantiations that aren't to classes in the ProcessWire namespace. If you are still able to reproduce it, it might be good for me to get a look at your MarkupGoogleMap.php file. But before that, I'd suggest making sure you've got the latest PW3 and going to Modules > Site > Clear compiled files, just in case something old is stuck in there.

**Comment by tbba** [comment]
Clearing compiled files had worked indeed. Something with the latest PW3 might have fixed it.
At the time of writing I saw this mentioned elsewhere (I think in a PW a blog comment) so I thought I was not alone with the problem. I am so glad this is solved.
