### ISSUE TITLE
File Compiler not getting use statement

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1799]
```php
<?php
// _init.php

use MammutEvents\Notification;

if(!function_exists('responseRedirect')) {
	function responseRedirect ($type, array $messages)
	{
		$colors = array(
			'success' => 'green',
			'error' => 'red'
		);
		Notification::add($messages, $colors[$type]);
		wire('session')->redirect('../', false);
	}
}
```

Will result in: 
> Fatal error: Uncaught Error: Call to undefined method ProcessWire\Notification::add() in /Users/benni/Projekte/Mammut Event Platform/root/html/site/assets/cache/FileCompiler/site/templates/_init.php on line 74

**Comment by ryancramerdesign** [comment]
The issue here is that Notification is the name of a ProcessWire class. So it's one of the symbols that's looked for by FileCompiler. Since you are using a "use" statement, which is part of PHP namespace vocabulary, this is a case where you really don't want the FileCompiler active. Since you are already using namespace features (as in the "use" statement), I'd suggest adding a "namespace ProcessWire;" to the top of your file (or another if preferred) so that FileCompiler doesn't have to get involved here. Either that, or avoid the "use" statement and do a MammutEvents\Notification::add(...). 

While we could update FileCompiler to recognize these "use" statements, I think it would add more complexity than it's worth. FileCompiler is really for the people that don't know what namespaces are and aren't using namespace features. Something to ease the transition between 2.x and 3.x.
