### ISSUE TITLE
setAndSave() issue with saving page status

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1806]
I was using this code, which doesn't work anymore on 3.0.15

``` php
$page->setAndSave('status', Page::statusUnpublished);
```

I also tried

``` php
$page->of(false);
$page->addStatus(Page::statusUnpublished);
$page->save('status');
```

I only started working as soon as I removed the 'status' argument in the save method.

**Comment by ryancramerdesign** [comment]
The `setAndSave()` actually can't be used with properties native to the `pages` table because those properties are only saved with the page as a whole. Meaning, setAndSave() is purely about saving page fields, not native properties. Though I would like to abstract that further so one doesn't have to think about that. But in order to make it worthwhile, $pages->saveField() would need to support them as well, and basically we'd need a whole new $pages->saveProperty() method, since there isn't currently a way to save properties independent of the page as a whole. ...So yeah I think we can support this, but it's not a quick fix. :)
