### ISSUE TITLE
Ability to add custom attributes for radios input

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1820]
Let's say I'm using PW's form API to build a form and I have a set of radio buttons and I want to have custom attributes on each radio input (not the radio's label field, but the input element itself).

Currently, it's not possible to do this due to API limitations.  You can only set name, id, value, checked, disabled.  If I'm using something like Vue.js and want to have an attribute like ```v-model='something'``` then I can't do it (unless I use hooks and modify the HTML itself, which is a little messier.

**Comment by ryancramerdesign** [comment]
You should be able to set more attributes, but those attributes get applied to the label that wraps the checkbox, rather than the checkbox itself. The InputfieldRadios::addOption() method will accept an array of attributes as the 3rd argument. Because the custom attributes get added to the wrapping `<label>` you may need to modify your JS to refer to that direct parent element of the checkbox, rather than the checkbox itself.
