### ISSUE TITLE
Using custom alignment classes in Page Edit Image causes issues in CKEditor

### ISSUE THREAD

**Issue by thetuningspoon** [ryancramerdesign/ProcessWire#1849]
Specifying custom classes in the Page Edit Image module for alignment styles causes issues in the image edit window in CKEditor:
1. The fancy animation that demonstrates how the alignment will appear with dummy text next to the image does not happen.
2. When using a caption with the image, the custom alignment class is not added to the figure element (no class is added at all).

PW 3.0.18

**Comment by ryancramerdesign** [comment]
Unfortunately this is a case where you've got to stick with PW's classes, otherwise it will have no way of showing you a preview of the effect, since it knows nothing about styles from classes in your front-end stylesheets. You might use this configuration option to add a secondary class for front-end use though. For instance, maybe you could specify "align_left uk-align-left". Though in my case, I always just use the PW defaults and define them on my front-end CSS, as that's usually the simplest solution.

**Comment by thetuningspoon** [comment]
Can't the editor get the class from the Page Edit Image module's config, though? Isn't that what that setting on there is for?

I'm sticking with the default classes for now, which are working well. They just don't follow my usual naming convention.

**Comment by schwaaab** [comment]
I cannot change the alignment classes to anything else on 3.0.120. It just will not accept anything else than the standard classes like align_right.

I use UIKit in the admin as well as in the frontend, but changing the class from align_right to uk-align-right brakes the whole thing.

**Comment by teppokoivula** [comment]
@schwaaab, that sounds like a different issue. Please open an issue for it to the new issues repository at https://github.com/processwire/processwire-issues/.

@thetuningspoon, I'm just using this chance to check if this is still a valid concern to you? If so, I'd suggest closing this issue and opening a new one either at the processwire-issues repository, or perhaps at the processwire-requests repository (this might be a better fit for that one).

**Comment by thetuningspoon** [comment]
Yes, this is still an issue. Looks like @schwaaab opened a new one in the new issues repo, so I'll close this.
