### ISSUE TITLE
devns composer.json

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1851]
Is there a reason, why the composer.json does list `"minimum-stability": "dev"`? This way all composer packages installed are dev versions, which is most of the time not preferable.

**Comment by ryancramerdesign** [comment]
I don't know, I'm just using values others have recommended here. Probably dev in this case because this is a dev branch. Though I presume nobody is going to use the stock composer.json exactly as-is. But if you think a different default value would be better just let me know and I'm happy to change it.

**Comment by LostKobrakai** [comment]
If I understand the property correct then minimum-stability is just used for resolving project dependencies, which processwire does not have by now.

> All versions of each package are checked for stability, and those that are less stable than the minimum-stability setting will be ignored when resolving your project dependencies.

**Comment by LostKobrakai** [comment]
Now here: https://github.com/processwire/processwire/pull/10
