### ISSUE TITLE
Possibility to prioritize execution of FileCompiler Modules

### ISSUE THREAD

**Issue by felixwahner** [ryancramerdesign/ProcessWire#1884]
In some cases people might want to use not only one but several FileCompiler Modules (let's say first twig and some minifier afterwards). It would be nice to have the possibility to control in which order the files get modified. Is there already a possibility to do so?

**Comment by ryancramerdesign** [comment]
I've gone ahead and added this. To use it, you'll see a "runtime execution order" in the module config where you can specify a number indicating the order it should run in relative to others. 

If you are making your own FileCompiler modules, and they implement `ConfigurableModule`, then you should just have them do a `parent::getModuleConfigInputfields($inputfields);` call at the beginning of their getModuleConfigInputfields method, so that the `runOrder` property appears in the config too.
