### ISSUE TITLE
Silence / Shutup operator usage

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1887]
I always thought these were considered bad practice in most cases. Isn't it better to write the logic to prevent the error in the first place? I know it's not always possible and I have used `@` myself in the past,  but one obvious place it's not needed (unless I am missing something, which is quite possible), is here:
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/Session.php#L161

```
@session_start
```
Is there any reason to not replace it with:
```
if(session_status() !== PHP_SESSION_ACTIVE) session_start();
```

If nothing else, it helps if you are trying to use `error_get_last()` which unfortunately reports silenced errors, effectively making it useless.

**Comment by teppokoivula** [comment]
Just curious, but why does this make error_get_last() useless? I haven't checked at which point in the execution flow this happens, so this might explain it, but I'd assume that session is started early on, in which case this shouldn't be that big of a problem.

My humble opinion is that a) this seems like the expected behaviour (I would assume that knowing something went wrong here is a good thing, not an issue) and b) session_status() requires PHP >= 5.4, so this would contribute towards raising our minimum requirements.

While latter thing might be OK for most (if not all) users, I do think that upping the requirements should only be done for very good reasons :)

**Comment by adrianbj** [comment]
@teppokoivula - I would have thought the same thing - ie session is started early so it really shouldn't affect error_get_last. Maybe it was just something about my particular use case - I should probably have tested more widely. It's weird to me that PHP doesn't have any option to ignore silenced errors though.

Good point about `session_status` being >= 5.4 - I didn't notice that - looks like this alternate function should work though: http://php.net/manual/en/function.session-status.php#113468

Anyway, given that it's not as simple as just using `session_status`, I'll close this.
