### ISSUE TITLE
[Conversation] Purpose of namespace in template

### ISSUE THREAD

**Issue by harikt** [ryancramerdesign/ProcessWire#1892]
Hi @ryancramerdesign ,

I was looking at these template files https://github.com/ryancramerdesign/ProcessWire/blob/devns/site-default/templates/home.php and wonder whether the namespace is really needed. Is there any special purpose you kept the namespace ?

Thank you

**Comment by blynx** [comment]
They are needed if you don't want your template files to be compiled. So I think the answer you want is 'yes'. 

From the blogpost: https://processwire.com/blog/posts/processwire-3.0-alpha-2-and-2.6.22-rc1/#compiled-template-files

> The template file compiler does the same thing as the module compiler, updating the template file for any references to ProcessWire classes or functions to acknowledge ProcessWire's namespace, where necessary. It also considers any other files included from the template file, as well as any prepend/append files.

**Comment by harikt** [comment]
Thank you @blynx .

**Comment by ryancramerdesign** [comment]
Technically the namespace could be left out, and that's what we did in the
beginner profile. But since this was the intermediate profile, I thought it
would be a good place to introduce using it. Also, I really see the
template compiler as being something to ensure existing sites continue to
work in PW3. For new sites, I prefer to keep the compiler out of it (not
that it matters that much).
