### ISSUE TITLE
 Nested repeater problem with Page field

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ProcessWire#1907]
When using the $page variable to define selectable pages for a Page field ("Custom PHP code to find selectable pages"), the options do not populate the Page inputfield when the field is inside a nested repeater.

In other words...
Repeater field > Repeater field > Page field

The problem seems to be related to the AJAX loading of repeaters. See [this forum thread](https://processwire.com/talk/topic/13677-selectable-pages-for-page-field-inside-a-repeater-inside-a-repeatermatrix/) for more information.

**Comment by ryancramerdesign** [comment]
Nested in a repeater, the $page is going to be the repeater item, not the original page being edited. That's because an ajax request is to the page editor for the item requested, not the original page. Ajax-driven repeater items are not rendered in the original page, so that's why the ajax request has to go to the page editor for the repeater item. At that point, there is no reference to the original page being edited. However, this trick might enable  you to get what you are looking for:

~~~~~
if(strpos($page->template->name, 'repeater_') === 0) {
  while(strpos($page->parent->name, 'for-page-') === 0) {
    $pageID = (int) str_replace('for-page-', '', $page->parent->name); 
    $page = $pages->get($pageID); 
  }
}
~~~~~
After that bit of code above, the $page should then represent the root-level owner of the repeater item (even if repeaters are nested).

**Comment by Toutouwai** [comment]
Thanks Ryan, that works great!
