### ISSUE TITLE
Issue with backend page sort?

### ISSUE THREAD

**Issue by pwFoo** [ryancramerdesign/ProcessWire#1917]
I sort the pages in the backend and it seems to work. Ordner in backend and frontend is wrong.

Added "sort=sort" to the frontend fixed it there, but why the page list in the backend isn't sorted by the custom / manual sort order, too?

(devns branch)

**Comment by ryancramerdesign** [comment]
I've not been able to duplicate this one. Can you give me an example of how things are out of order? Check that you don't already have a sort defined in the template (Family tab) or on the parent page (Children tab). That would be the only reason I can think of that you'd need to add `sort=sort` to achieve a different order. That's because `sort=sort` is the default one that is used when some other sort has not overridden it.

**Comment by pwFoo** [comment]
Hi Ryan,

don't know why, but also can't reproduce at the moment.
So I think we should close that issue...
