### ISSUE TITLE
'Page' field: "Custom selector to find selectable pages" breaks "Save" validation when OR condition is used

### ISSUE THREAD

**Issue by rwetzlmayr** [ryancramerdesign/ProcessWire#1921]
Steps to reproduce:

1. Use a site w/ a recent `devns` commit and the Default Site Profile (Intermediate Edition). I used PW 3.0.25.
1. Verify that debug mode is on (`$config->debug = true;`)
1. Create new field and set its type to 'Page'.
1. In this field's 'Input' tab, enter a custom selector which contains an 'OR' condition for a value. I used `template=user,roles=superuser|editor`.
1. In this field's 'Input' tab, set the 'Label' field to `name`.
1. Other field settings do not matter.
1. Add this field to any template.
1. Add a new or edit an existing page using the template from the previous step.
1. Note that the Page selector shows users matching the selector's conditions. I.e. the custom selector works as intended.
1. Select any user as a value for this field.
1. Hit "Save"

**Expected result:**

Page saves without problems, selected value persists.

**Actual result:**

Error message stating `Page $value is not valid for $field->name (Page $page does not match findPagesSelector: template=user,roles=superuser|editor)`, selected value does not persist.

**Refs:**

* https://github.com/ryancramerdesign/ProcessWire/blob/70b3c3f7a24017f66ea522487b9a1f1da2df4d56/wire/modules/Fieldtype/FieldtypePage.module#L521
* https://github.com/ryancramerdesign/ProcessWire/blob/70b3c3f7a24017f66ea522487b9a1f1da2df4d56/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module#L228

**Comment by ryancramerdesign** [comment]
For this case I think you'd need to use the page IDs rather than the role names. The PageFinder engine maps strings to page names as an added feature, specific to pages. However, general purpose selectors in ProcessWire are independent of pages (since they work on any kind of object) and so it doesn't assume that a string value literally names a page "name". Try changing your `roles=superuser|editor` to `roles=123|456` where 123 would be the ID of the superuser role, and 456 would be the ID of the editor role. Another alternative that may work would be `roles.name=superuser|editor`. However, I generally prefer to use IDs for things like this for a tiny bit less overhead.

**Comment by rwetzlmayr** [comment]
> Try changing your roles=superuser|editor to roles=123|456

Thanks. This variant works.

> Another alternative that may work would be roles.name=superuser|editor.

This variant results in the same error message as mentioned in the original issue when saving the page.
