### ISSUE TITLE
Duplicate execution of added Page hook

### ISSUE THREAD

**Issue by marcostoll** [ryancramerdesign/ProcessWire#1925]
I tried adding a custom module that provides a new Page hook namend "Page::renderChunk" via

`public function init()  
{  
    $this->addHook('Page::renderChunk', $this, 'renderChunk');  
}`

`public function renderChunk(HookEvent $event)
{
    print  $event->arguments[0]; // simplified for demo purposes
}`

This could be used in output template files like this:

`<?php $page->renderChunk('some arg');`

The current behaviour seems to be, that the new Page hook is executed twice. The output ('some arg') is printed two times.

**Comment by ryancramerdesign** [comment]
I just setup something similar in a module but can't duplicate. Very likely your init() method is getting called twice. Make sure that your module is 'singular', so that multiple instances of it can't be created. This can be specified in your getModuleInfo(). Typically autoload modules are assumed singular, but in this case it seems like your hook is getting attached twice somehow or another.

**Comment by isellsoap** [comment]
@marcostoll Have you been able to try out the suggestions made to you? Can this issue be closed?

**Comment by marcostoll** [comment]
@isellsoap Yes, thank you. Marking the module as singular has done the trick.
