### ISSUE TITLE
Allow ability for InputfieldMarkup description field to not be forced into Markdown (also affects MenuBuilder)

### ISSUE THREAD

**Issue by jlahijani** [ryancramerdesign/ProcessWire#1932]
I have a form which I built manually using the PW Form API.  One of the fields, which is a Markup field, has a description which contains HTML (```<span>```'s and such) and when rendering the form, the field description HTML displayed properly.

Sometime after 3.0.21, something was changed whereby the rendering of that Markup field description displayed as HTML entities.

The line that forces this format is here:
https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/modules/Inputfield/InputfieldMarkup.module#L60

If you view the code in the ```entityEncode``` function, it gets forcibly converted to Markdown (it didn't before).

Is there a way for the description field of a Markup field to stay undisturbed?

--

This same issue also affects the MenuBuilder plugin.  Screenshot:
![2016-07-20_10-10-12](https://cloud.githubusercontent.com/assets/4558/16995638/45a9b1da-4e62-11e6-8d1d-5bdcee14447b.png)

**Comment by cstevensjr** [comment]
re: MenuBuilder mention, I don't believe any of Kongondo's modules support the 3.x devns version of ProcessWire.

**Comment by jlahijani** [comment]
@cstevensjr The issue I described doesn't speak to MenuBuilder directly, but strictly to the fact that the description field of a Markup field no longer renders as pure HTML.  So even modules that do support 3.x and that do use HTML in description field of the Markup field will still face this issue.

**Comment by teppokoivula** [comment]
Agreed. This issue is not about a specific module, but rather a break in backwards compatibility. There's no doubt that Ryan has a good reason to make this change, but it's also good to note that it will break some existing implementations. The question is whether that's an acceptable compromise :)

**Comment by cstevensjr** [comment]
I only commented on this issue because it cited, with a screenshot,  an acknowledged non 3.0.x compatible module (MenuBuilder) as proof of a problem in a 3.0.x release.

I fully understood the problem as described originally and also believe it did not affect a specific module.  I just believe the use of that example could potentially cloud what is a very clear issue (problem).  Good luck on getting this issue resolved.

**Comment by ryancramerdesign** [comment]
The field descriptions aren't meant to be anything other than field descriptions. I think for whatever reason the InputfieldMarkup Inputfield must have been allowing markup in the description before, which I don't think was intentional and isn't something any other Inputfields allow. I'm not sure what the case was exactly, but I must have corrected that in one of those commits. With a Markup Inputfield, it does support markup in the actual value though, so this one is easy to overcome just by leaving the description blank and bundling it above the value instead. I've also updated the InputfieldMarkup to honor the `Inputfield::entityEncodeText` and Inputfield::textFormat` properties, so that now you can support markup in the description (or notes) just by setting either of these properties to the $inputfield object. (This works for any Inputfield)

~~~~~
$inputfield->entityEncodeText = false;
~~~~~
Or you can do this:
~~~~~
$inputfield->textFormat = Inputfield::textFormatNone;
~~~~~
