### ISSUE TITLE
Datetime field for time only

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#1960]
Not sure this is intended: I tried to use the Datetime field for Time only.
Did not work: When I set input format DATE to "none" and TIME to "17:10" and saved that, the DATE input format was reset to the default setting (instead of remembering "none").
(3.0.28 devns)

**Comment by ryancramerdesign** [comment]
There isn't an option for time-only in this Fieldtype, though maybe we should add it. MySQL actually needs a date in order to store a time in a DATETIME column type, which is why this Fieldtype doesn't support it (since MySQL doesn't). Of course we could work around it by substituting a date, but then there's the matter of the datepicker, which also requires a date. So supporting time-only in our Datetime Fieldtype has a lot of obstacles against it. But currently there's a good Fieldtype for this made by Netcarver– [FieldtypeTime](http://modules.processwire.com/modules/inputfield-time/). I'd recommend using that.

**Comment by tbba** [comment]
Good idea. I will try that fieldtype. Thank you!!!

If time-only does not work, why can DATE be set to "none? Maybe that option should be removed or is that for something else?
Maybe a short note in the module settings would make that 100% clear, that time-only is not covered by the module and thus not settable.

**Comment by tbba** [comment]
Feature request is to put a little hint in the module, that the field is not suitable for "time only" settings.

Apart from that the issue can be closed, I think.
