### ISSUE TITLE
Fieldtype Image in ProcessProfile since 3.0.17

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ProcessWire#1969]
Since the update of image fields in 3.0.17 <del>it isn't possible anymore to add/ edit imagefields via the User Profile Page (ProcessProfile).</del>

<del>I need this feature in many sites. Users not allowed to edit pages using template 'user', should be able to edit there own profiles.</del>

Update: Its only the preview (ajax) which doesn't work properly.

Maybe related: https://github.com/ryancramerdesign/ProcessWire/issues/989

**Comment by NilsWiere** [comment]
I'm also experiencing problems with the image fieldtype in PW 2.8.29: Since the commit yesterday, that fixed some issues with PW 2.8.29, I'm not able to implement images through the image fieldtype anymore. After choosing an image, the loading icon is showing up for infinite time without the image being processed.

**Comment by ryancramerdesign** [comment]
@kixe Thanks I've pushed a fix for this. We didn't previously support ajax uploads in ProcessProfile, but I've also added support for that.

@NilsWiere I couldn't find any other spots where image uploads aren't working (outside of ProcessProfile). If you are still seeing an error, check to see if you've got any JS errors occurring.

**Comment by NilsWiere** [comment]
Think I found the problem for my case: I used the Image Extra module on that image field. As soon as I uninstall the Image Extra module, the upload is working again.

**Comment by kixe** [comment]
@ryancramerdesign 
thanks. closed.
