### ISSUE TITLE
config.*.php loading

### ISSUE THREAD

**Issue by LostKobrakai** [ryancramerdesign/ProcessWire#1980]
The database info in the config.php should not be added into a git repo, but often other config setting should be. Wouldn't it be possible to load all config.*.php files as well? This way one could exclude only the file with the db data and leave the other settings in another file, which is comitted to git.

**Comment by teppokoivula** [comment]
You could always split your config settings into multiple files by replacing the original settings with an include statement. That's how I've handled things like shared settings in our environment, and it works just fine.

I'm not specifically against supporting multiple config files, but not sure if it makes sense as a core feature either :)

**Comment by LostKobrakai** [comment]
I'm doing that as well, but it would be nice if those extra files would be included automatically, e.g. I've also a extra file for api credentials, which I need to include.

**Comment by teppokoivula** [comment]
> Edit: Also I see this not much different to the auto-included init.php / ready.php files.

The main difference would be that, in order to include all config.*.php files, ProcessWire would have to scan the whole directory in order to find matching files. Not a huge deal, but in terms of performance checking for specific file(s) is much faster.

Anyway, in my opinion this is already very easy to solve, so I would rather not have a built-in feature for it unless it's a very common need (which I kind of doubt) :)
