### ISSUE TITLE
Not able to add field and duplicate a field in the same Save command.

### ISSUE THREAD

**Issue by sirgru** [ryancramerdesign/ProcessWire#2008]
When editing a field, if "Add to templates" and "Duplicate" fields are specified the duplicate step happens, but the template adding doesn't.

PW is 3.0.32 XAMPP Version: 5.5.30, Windows.

**Comment by ryancramerdesign** [comment]
All field actions are exclusive. You can't perform multiple such actions at the same time because they all require follow-up steps. The duplicate one in particular, because that literally changes the template that you are editing. As a result, I'd recommend using the "add to templates" first, and then doing your duplicate. Or if you want to duplicate without the added templates, then do that first and add to templates later.

**Comment by sirgru** [comment]
Thanks, that makes sense. I think it would be good to signal these changes are exclusive somewhere in the interface, either by graying out some fields or popping up a message box. Even better, it seems to me these options should be individual buttons that navigate away from the edit screen with the prompt to save. Just an idea.

**Comment by isellsoap** [comment]
@sirgru Can this issue be closed, or do you think the issue requires additional work to do?

**Comment by sirgru** [comment]
Yes, the issue can be closed.
