### ISSUE TITLE
$page->viewable($language) not always working

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#2027]
In a multilanguage using LanguageSupportPageNames in PW2.7.3 and probably earlier I noticed, that the $page->viewable($user->language) doesn't work seem to work always properly. 

It's that the hook in LanguageSupportPageName is called but returned in the first line as the $event->return seems to be false or null. So the check with the language object isn't even run.

The scenario is a for sidebarelements that are pages and selected through a page select on pages. On a foreach loop those selected pages are rendered. Since it's not a page view but more a partial that is rendered inside a page, we figured we had to add additional checks for published and now for if active in the current viewed language. 

It seems to work fine in the language navigation we have, where we loop the language and check with the said method. 

```
$currentPage = $this->wire("page");
        foreach($this->wire("languages") as $lang) {
            if(!$currentPage->viewable($lang)) continue;
        	$counter++;
            if($lang->isDefault()) $langName = $defaultName;
                else $langName = $lang->name;
            $class = $this->wire("user")->language->id == $lang->id ? " class='$currentClass'" : "";
            $localizedUrl = $currentPage->localUrl($lang);
            $list .= "<li$class><a href='$localizedUrl'>$langName</a></li>";
        }
```

This works fine but not in our sidebar code with similar method wich is located in prepend template _init.php. Which goes like this.

```
...
$sidebarElements = new PageArray();

if($page->select_sidebar && $page->select_sidebar->count) {
    $sidebarElements = $page->select_sidebar;
} else {
    $closestSidebarParent = $page->closest("select_sidebar.count>0");
    if($closestSidebarParent->id) {
        $sidebarElements = $page->closest("select_sidebar.count>0")->select_sidebar;
    }
}

foreach($sidebarElements as $sidebarElement) {

    // skip unpublished elements
    if($sidebarElement->isUnpublished()) continue;

    // if element not published in alternative language, skip it
    if(!$sidebarElement->viewable($user->language)) continue; // always false

    $sidebar .= wireRenderFile("views/sidebar/{$sidebarElement->template->name}", array(
            "page" => $sidebarElement,
        ));
}
```

When using 

```
 if(!$sidebarElement->viewable($user->language->name)) continue; 
```

It works cause the core permission check before the hook in LSPageNames has some implemented language name check (although collisions with fields are given).

**Comment by ryancramerdesign** [comment]
If I understand correctly, a `$sidebarElement->viewable()` call would still return false, without providing a `$user->language` to it? If that's correct, this is why the viewable call with the language object is returning false, because the LanguageSupportPageNames hook just exits when it sees that $event->return is false. So that leaves the question of why the non-hooked viewable() call is returning false. Is it possible the page used by `$sidebarElement` has no template file assigned? You can tell it to skip the template file check in the viewable call by providing a 2nd argument of boolean false. This is also implied when when given a Field or string as the first argument, which is why I think you see it working the way you want when providing a language name. But I'd be curious if this call below would solve it in your case?

~~~~~
if(!$sidebarElement->viewable($user->language, false)) continue; 
~~~~~

**Comment by somatonic** [comment]
Yes, the sidebar element pages don't have a template file. Using the second argument false seems to work with language object. Thanks, good to know.
