### ISSUE TITLE
Can't save page 1549: /trash/1549.1001.6_administración-de-eventos/: Chosen parent '/trash/' already has a page named '1549.1001.6_administración-de-eventos'

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#2030]
Just had this when trying to trash a page. Haven't investigated thoroughly, but wanted to report before I forgot. Obviously emptying the trash fixed things, but still weird, no?

**Comment by ryancramerdesign** [comment]
This can happen if you trash a page, then create a new one with the same exact name, parent and sort order, and then trash that one too. I generally try not to add a lot of code complexity in order to accommodate such unlikely scenarios. For now it's true that you'll need to either empty the trash or rename the existing one before you can trash it.
