### ISSUE TITLE
FileCompiler error

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWire#2032]
I have a template file where I include some other files. Some of the included files must be compiled, and some of them not. If the included file is on /site/templates path it's ok, but if the file is included like with absolute path like this:

inlcude('C:\PHP\adodb5\adodb.inc.php');

then I get the following error:

Exception: Unable to create directory C:/inetpub/wwwroot/site/assets/cache/FileCompiler/C:/PHP/adodb5/ (in C:\inetpub\wwwroot\wire\core\FileCompiler.php line 135) 

Directory path is invalid, on windows there can be only one ":". I also assumed that file compiler would not  try to create a directory structure if I put  //FileCompiler=0 in the included file. Using latest PW 3.0.33RC1.

**Comment by ryancramerdesign** [comment]
That's correct that FileCompiler should ignore it if it contains FileCompiler=0 within it, but this error is occurring before it gets to that point of looking in the file. I believe the problem is right around here https://github.com/ryancramerdesign/ProcessWire/blob/devns/wire/core/FileCompiler.php#L115 but I don't have a Windows test environment to duplicate it. Do you have any ideas on what changes would solve it? Though what I'd like to do is keep FileCompiler out of directories that aren't in the public_html tree, which would also solve it, so will work on that here.

**Comment by matjazpotocnik** [comment]
Yes, the error is thrown because compiler is trying to create a directory before it check for the file. Maybe you should first check the file and then create the directory structure? But that would only help when FileCompiler=0 is contained in the file. The solution for the windows environment would be to remove the second : so the path would become C:/inetpub/wwwroot/site/assets/cache/FileCompiler/C/PHP/adodb5/.

**Comment by ryancramerdesign** [comment]
I had some other FileCompiler updates going in, so attempted also attempted a fix in the latest commit. Can you tell me if this resolves the issue?

**Comment by matjazpotocnik** [comment]
It resolves the issue. Thx. It creates unneeded directory structure though, even if FileCompiler=0 ...

**Comment by ryancramerdesign** [comment]
That's fine–things can change, so it often keeps more stuff than it
actually uses purely for comparison and runtime speed purposes. Setting
FileCompiler=0 basically means it's not going to compile the file, but it's
still going to keep an eye on it in case that changes.

**Comment by matjazpotocnik** [comment]
Thanks for explanation. Closing.
