### ISSUE TITLE
Page tree: trash action

### ISSUE THREAD

**Issue by u0816** [ryancramerdesign/ProcessWire#2041]
- if you __trash__ a page, the trash counter is not updated
- if you __restore__ a page, the parent's children counter is not updated
- if you __move__ a page to trash, the page actions are not updated.  __trash__ action is still selectable, showing an empty alert box

**Comment by ryancramerdesign** [comment]
Thanks for the report, and you are correct on all items. Most of these require a refresh of the page list, and I chose not to implement that in this case because people may be trashing multiple pages, and the refresh is annoying when doing that. There's also the matter of added code complexity relative to benefit. Figured that was more important than the minor cosmetics here. Of course, you can always refresh the PageList manually to see updated counts too. When we're refactoring the PageList at some point in the future will definitely consider updating these if we can do so while still keeping the complexity manageable.
