### ISSUE TITLE
$input does not support arrays

### ISSUE THREAD

**Issue by pieterbeulque** [ryancramerdesign/ProcessWire#240]
In HTML, you can declare arrays in your post object, e.g.

`<input name="array[key][key]" />`

This would store your variable in `$_POST['array']['key']['key']`. However, when doing this and trying to access it with:

```
$array = $input->post->array;
echo $array['key']['key'];
```

It seems not to be supported. A `var_dump` of `$input->post` also shows it does not exist. Performing a `var_dump` on `$_POST` shows it came through because it **is** stored in `$_POST`.

**Comment by LostKobrakai** [comment]
Just bumped into this as well. Maybe just replacing arrays with an error message would at least make it easier to debug instead of just returning removing them.

**Comment by teppokoivula** [comment]
I'm not particularly fond of the idea of returning error messages in such a situation. Partly because it's not an error, but also because such a change could potentially cause unexpected side effects somewhere (even if it's kind of a long shot) :)

I'd suggest making the way that array values are dealt with (or *not* dealt with, really..) obvious in the [documentation for $input](https://processwire.com/api/variables/input/) or adding proper support for multi-level values (preferably with configurable max depth with a sensible default limit), whichever makes more sense.

**Comment by LostKobrakai** [comment]
I would love that, too, but I had to redo my form because multipart encoding doesn't support array notation, at least not for files.
