### ISSUE TITLE
Session cleaning issue (session files are never removed on Ubuntu systems)

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#309]
This is an old issue discussed [here](http://processwire.com/talk/topic/337-session-cleaning/) and [here](http://processwire.com/talk/topic/1142-lots-of-sessions/) (and probably a few other threads, these just came up with very quick search). I'd like to point out that the issue still exists and the solution mentioned in both threads (forcing sensible values to `session.gc_probability` and `session.gc_divisor`, just like Drupal apparently does) seems like the most sensible fix.

This is likely to affect at least all Ubuntu servers with default config, since there `session.gc_probability` is by default set to `0`, because they've got another garbage collection solution in place (a cron job). The issue, at least in my case, was that the script triggered by that cron job only looks for session files under /var/lib/php5/. *This obviously doesn't work for files stored using custom `session.save_path` value.*

Even though some resources (such as [this Stack Overflow thread](http://stackoverflow.com/questions/4534750/does-ini-setsession-save-path-custom-path-effect-the-session-garbage-cle)) suggest that native PHP garbage collection only works for `session.save_path` found from php.ini (not one set by `ini_set()`) and that otherwise you'd have to set up your own garbage collector, at least in my case forcing aforementioned values with `ini_set()` at index.php fixed the issue.

Here's some light reading if you want to check exactly what (and why) is going on:

* http://somethingemporium.com/2007/06/obscure-error-with-php5-on-debian-ubuntu-session-phpini-garbage
* http://vvv.tobiassjosten.net/php/php-session-garbage-collection/
* http://www.laurencegellert.com/2012/08/php-sessions-not-being-deleted-on-ubuntu-server/
* http://stackoverflow.com/questions/2904862/issues-with-php-5-3-and-sessions-folder

**Comment by apeisa** [comment]
This is still missing. 

BTW: Should new installs use db sessions by default?

**Comment by ryancramerdesign** [comment]
I've thought it's best not to override a server's configured session
settings as a default behavior. Most web hosts will have PHP's session
settings configured optimally for their environment, and we want PW to use
that. DB sessions are nice in the right environment, but there are plenty
of environments out there where the host has PHP configured to keep session
files in something even faster, so I think DB sessions should be an option
to turn on rather than a default. In addition, for the title of this
thread, it doesn't matter if sessions are stored in the DB or file system,
because they both use PHP's session garbage collection.

The main issue here is when PW is setup in an environment where the
server/PHP doesn't have properly configured session settings in place.
Perhaps there's some way we can detect that and trigger a warning or
plug-in some sane defaults? Admittedly, I've not come across a server like
this, so not exactly sure what to be looking for.

**Comment by teppokoivula** [comment]
Can't speak for every host out there, but based on my observations so far, this issue applies to every Debian-based distro with default settings. They have a different garbage cleaning method in place, and while that won't be problem when you're using the default session save path, it's going to be problem for systems like ProcessWire that define their own session paths.

The main point is that, from my point of view (and theirs, apparently), this has nothing to do with being "properly configured" -- it's just a different mechanism altogether. Based on everything that's being said here, I'm having some trouble seeing why exactly checking for problematic settings (gc_probability = 0) could be considered harmful? :)

**Comment by ryancramerdesign** [comment]
Is that the setting we're looking for: gc_probability=0? I don't have
access to one of these cases and really don't know what we're even looking
for. But I do know PHP docs are pretty clear about what the defaults are
for these settings. The default session path is blank, which means it's
left to the server, and that usually resolves to something in /tmp/. So
from a security standpoint it's a good idea to set a specific session path.
On the other hand, the defaults for GC settings are specifically defined by
PHP and outlined in the docs. If someone changes them from the defaults,
they likely have a reason for doing so and we should honor that. But if a
debian-based distro is going to override PHP's GC entirely, then shouldn't
also replace the behavior of PHP's GC? Instead it is overriding all of
PHP's GC, but only replacing some of the behavior. This sounds like a major
oversight and bug in the distro to me.

As for how we can work around it: if checking the gc_probability for 0 is
all that's necessary, that does make it easy. But what to do next? Set the
gc_probability to have PHP's default value again, or have they disabled
other parts of PHP's session mechanism? Specifically, I'm wondering if I
should just avoid setting the session_path at all if gc_probability is 0,
letting that linux distro handle the session files as it sees fit (since it
clearly wants to). That won't work for other session storage mechanisms
like DB, but we can disable that from being used if gc_probability is 0.

**Comment by ryancramerdesign** [comment]
Just doing some more research here, it turns out they have disabled other parts of PHP's GC system as well, so setting the gc_probability to our own value won't fix it. It sounds like we need to just disable setting a session path at all (if gc_probability is 0), and prevent any other kind of session storage from being installed.

**Comment by teppokoivula** [comment]
Ryan, I'll take a closer look at this too. I'm pretty sure that I changed the probability setting on one test machine and everything started working -- I'll repeat that test and see how it works for me. My memory might be failing me here.

From what I *can* remember, the main point was that Debian-based systems use a cron job for cleaning default PHP session storage, because their security settings are rather strict, and apparently prevent the built-in mechanism in PHP from accessing /tmp. This cron job can be configured to look elsewhere too, but in our case that's not really feasible (each site having its own session storage).

Assuming that probability alone helps, personally I'd prefer to go either with forcing a sensible value to probability (note: only when it's initially `0`) **or** making it very obvious to the user that this might be required. Latter option would be a safe bet, but the more options like that we have, the more complicated setting up a site with ProcessWire gets. That's probably why it seems that WP and Drupal just override the value, no questions asked :)

(Note: I'm not too fond of /tmp as a session storage either.. it doesn't seem like a safe option, no matter how much the system tries to limit access there.)

**Comment by ryancramerdesign** [comment]
I found a comment somewhere at php.net indicating that GC values set at
runtime (as opposed to php.ini) were ignored... Speaking only of that
debian/distro that overrides PHP's GC without fully implementing it. Who
knows if it's true or not. I'm guessing there may be some other factors too
like apache as fastcgi vs mod or something. But it made me think the only
good option was to let it handle the session path. Plus, if it provides
some extra security for session files, we should let it. Still, given your
experience was different, I'll setup SessionHandlerDatabase to set the
probability value (if not yet) rather than prevent use of it.

**Comment by BernhardBaumrock** [comment]
nice to see some news on that :+1: 

i'm far from an server-expert, but maybe my vagrantbox is helpful for testing: https://github.com/BernhardBaumrock/vagrant-pw-lamp -> you can setup a virtual ubuntu environment in no time, just install vagrant and virtualbox (instructions are there) and play around without messing your host machine.

regarding the session problem: i added these 2 lines to the end of my config.php and that worked
ini_set('session.gc_probability', 1);
ini_set('session.gc_divisor', 100);
Ubuntu 12.04.5 LTS

**Comment by BernhardBaumrock** [comment]
seems this is fixed now?
https://processwire.com/blog/posts/processwire-core-updates-2.5.18/#session-cleanup-on-certain-debian-based-servers

**Comment by teppokoivula** [comment]
Confirmed. At least on my test server (Ubuntu) session files now get stored in the default session path, meaning also that the `/usr/lib/php5/sessionclean` script works as expected. I'm closing this issue.
