### ISSUE TITLE
HTTPS Only not redirecting.

### ISSUE THREAD

**Issue by netcarver** [ryancramerdesign/ProcessWire#715]
Using 2.5.0, all templates setup to use the https Only option but when visiting the homepage via http their is no redirect to the https version. According to the description on the template URL tab, the https only option should cause an automatic redirect.

**Comment by cstevensjr** [comment]
+1 on getting this fixed.  I have quite a few sites that are HTTPS Only now.

**Comment by ryancramerdesign** [comment]
I've pushed an update to support an https redirect on the homepage. However, I'm not sure I recommend using it. If you've got a site that you only want to serve from https, it's much better to do this from your .htaccess file. The http/https redirect option in templates is really more for sites were you have some templates that need https (like a checkout or login page) and some that don't. For sites that are exclusively https, don't bother with this option and instead just enforce it from your .htaccess file.

**Comment by cstevensjr** [comment]
What would be the correct syntax in the .htaccess file?

**Comment by cstevensjr** [comment]
Ok, I figured it out

RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L]

**Comment by processwired** [comment]
Since this commit was made , I have issues now. The scenario is the following: in 2.5.15 (before https change) I have set up a template which allows url segments. This template is set to "https only"; all other templates are set to "http". Before the change, http url was cleanly redirected to https, e. g. http://www.mysite.com/page/segment -> https://www.mysite.com/page/segment. Now (latest dev with https change) the URL is doubled like this: https://www.mysite.com/page/segment/https://www.mysite.com/page/segment

**Comment by ryancramerdesign** [comment]
@cstevensjr that looks about right to me. 

@processwired thanks, looks like I had a small typo where I was concatenating when I shouldn't have been. That should be fixed in the latest commit.

**Comment by isellsoap** [comment]
@netcarver Can this be closed?
