### ISSUE TITLE
Stateless formatting

### ISSUE THREAD

**Issue by chpio** [ryancramerdesign/ProcessWire#717]
Hi,

what are the advantages of the statefull formatting:

```
$oldOf = $page->of();
$page->of(true);
echo $page->myField;
$page->of($oldOf);
```

over a stateless approach: 

```
// myField is in _any_ case formatted
echo $page->myField;
```

in corner cases, where you want it to be unformatted:

```
// myField is in _any_ case unformatted (e.g.)
echo $page->_myField;
```

PS: is there way to set a label of an issue if you'r not the owner of the repo?

**Comment by thetuningspoon** [comment]
I'm not sure that I understand the distinction between "front end" and "back end" in the context of output formatting. My template files (front-end) are controllers that handle all user interaction, calling methods on my models (back end) which handle the more complex processing logic. But since PW thinks I am already in the "front-end" stage of the application flow since it has started processing my template, all of my code must always take the output formatting state into consideration. 

Can you give me an example of a context in PW (aside from core development) where I would be writing code that I could assume output formatting would be off at any time that code would be called? Are we only talking about autoload modules that don't have methods that could be called from a template? 

> Having a state means that we can identify when something has violated that state. Once you violate the state, the page can't be saved and thus data can't be corrupted. In fact, as soon as you modify a field in output formatting mode, PW places the field (or entire page if necessary) in an unsaveable corrupted status. In a stateless approach, you just have to assume that the user hasn't violated the state.

This really confuses me. What state have I violated by trying to save a formatted value to another page field? What if that is precisely what I wanted to do? 

One of the common issues I've run into with output formatting is editing multiple pages at once via the api. If I get one page and start setting values to it, and then pull another page, edit, and save it before saving the first, the output formatting setting of the first page gets reset before I have a chance to save it. If I then set another field on the first page and go to save it, my application terminates with an exception. It is not clear to me why the output formatting state has flipped.

Another example I recently ran into was calling a function to send an email while in the midst of editing a page via the api. In such a case you need to remember to turn off output formatting and back on again before calling the email function (and then back off again before doing your save), or your email will be outputting unformatted fields.

I could list more examples of where this has tripped up me and the other devs I work with.

I wouldn't mind if I could always assume of() was set to true, and then just call getUnformatted() when I needed it, but the current behavior of the save() method forces me to have to keep track of the state anyways, since it prevents setting anything when of() is true. 

So I disagree that the stateless approach requires having to keep track of multiple states. On the contrary, all you have to do is think about which version of the field you want at the time you retrieve it, which requires no tracking. With the stateful approach, you still have to think about what version of the field you want, but you also have to keep track of the state the field is currently in, which is not always clear without first testing it.

Additional shorthand methods for getFormatted() and getUnformatted() would be nice, but I think the real issue here is the behavior of the save() method. setAndSave() is a nice addition, but an alternative save() method that works exactly like save() except that it doesn't second guess me on my intentions would be even better, since the object syntax is much more elegant. Maybe something like saveDefinitely() :)

**Comment by JanRomero** [comment]
Hier eine <strong>Antwort</strong> mit HTML-Markup drinne.

Und Code auch.

```html
<script>alert('lol pwnd')</script>

1<2

eins <drei
```
