### ISSUE TITLE
Some JSON returned as text/html

### ISSUE THREAD

**Issue by tuomassalo** [ryancramerdesign/ProcessWire#768]
Some of Processwire's own url return JSON data but with a Content-Type `text/html; charset=utf-8` instead of `application/json; charset=utf-8`. This might pose a security problem, at least in theory.

At least these urls return `text/html`: `/processwire/page/list/?id=2&render=JSON&start=0&lang=0&open=undefined&mode=actions`

**Comment by apeisa** [comment]
Ryan, just a follow up here. I am not seeing this fix on pw core yet. 2.7.1 and 3.0 both return text/html for api finds when using PW admin. 

![image](https://cloud.githubusercontent.com/assets/131855/15671081/9c32a942-2731-11e6-99b6-d64931c864c8.png)

**Comment by ryancramerdesign** [comment]
Antti,

The one Tuomas mentioned was in PageList, which was fixed long ago. But
looks like you've found another instance here, so thanks for letting me
know. I've added a `header("Content-type: application/json");` and it'll
appear in the next commit. This header is so easy to miss because it seems
that nothing cares, it always just works either way without error from my
experience. I'm not suggesting it doesn't matter of course, but curious how
you found this one? I'm going to hunt a bit to see if I can find any more.

Thanks,
Ryan
