### ISSUE TITLE
404 editable but not visible for non-superusers

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/ProcessWire#809]
So, while instructing a client on how to edit their (default) 404 page, it came up that they can *edit* it, but they still can't *view* it on the page tree. I had a look at this on couple of sites, and the behaviour seems consistent; is this intentional, and if, why?

It's not a very common request, but sometimes our clients (who are *never* superusers, for various reasons) want to edit the 404 page, which is why being able to edit it makes sense. What doesn't make sense is that they have to know the exact ID to do that.

Feels weird that I've managed to overlook this for so long, but I'm almost always logged in as superuser myself, so such things do obviously happen :)

**Comment by gingebaker** [comment]
I also ran in this problem today. It appears to me that this problem only exists because of this "if statement" here:
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Process/ProcessPageList/ProcessPageListRenderJSON.php#L115

Because in this function pages with "systemID´s" get in the $extraPages array. This array will only be added to the pages list if a superuser is logged in.

But if we look up a little bit in this function there is also a "continue statement" for pages that should not be listed. 
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/modules/Process/ProcessPageList/ProcessPageListRenderJSON.php#L104

If i change the code of the if statement on line 115 temporarily to...
```php
if($this->superuser || true) foreach($extraPages as $page) {
	$children[] = $this->renderChild($page);
}
```
...everything seems to work fine here. I can manage edit access to the 404 Page with Template Access. I couldn´t figure out why this IF Statement on L115 is here?

**Comment by teppokoivula** [comment]
This issue has been moved to the processwire-requests repository. Closing.
