### ISSUE TITLE
Locked status disables possibility to add children pages

### ISSUE THREAD

**Issue by apeisa** [ryancramerdesign/ProcessWire#820]
This is probably changed somewhere between 2.3 and 2.5, since at least on one site after update editors couldn't add new pages. UA settings were very simple (only defined on home template) and some family restrictions were in place.

It took me several minutes to figure out why adding new pages (/page/add/?parent_id=1078) just gave "You don't have access to the template required to add pages here", but it is caused of the locked status of page 1078.

This is clearly a bug, since the "new" button is visible in page tree, but adding is not working (well, for superusers it is).

**Comment by adrianbj** [comment]
Not sure if this is the best place to post this, but I just received the same "You don't have access to the template required to add pages here" error that @apeisa mentions in the first post. I am running 2.5.25 and there are no locked status settings and I am getting the error even as a superuser. In my case the issue seems to be family related. The setup is these templates:

Parent (basic-page)
    Child Level One (basic-page-children)
          Try to create Child Level Two - there is a "new" button for the Child Level One page.


* basic-page only allows basic-page-children for child pages
* basic-page-children allows basic-page-children for child pages, but only basic-page for parents, so I don't think there should be a new button at all since it isn't possible to create a child page based on the template family rules. So obviously not a smart setup on my part (it's just a sandbox install), but I do think there is some missing logic regarding generation of the new action button. As soon as I add basic-page-children to the allowed templates for parents I can create the page.

**Comment by somatonic** [comment]
That family setting seems wrong anyway. On one hand you allow child pages for the basic-page-children template, but then parent can only be basic-page.

**Comment by LostKobrakai** [comment]
It may be not the best setup, but the behavior @adrianbj mentioned is just wrong. It's the job of the cms to handle such errors / inconsistencies. PW could even show a warning if "allowed children" includes the template itself and "allowed parent" doesn't.

**Comment by adrianbj** [comment]
@somatonic - I agree, those family settings are wrong and don't make sense, but it's my test install and I was playing around with things and stumbled across this, but I agree with @LostKobrakai - PW should prevent this scenario - there shouldn't be a "new" button if it's not possible to add a new child.

**Comment by apeisa** [comment]
Since the original issue was only happening on one site and no one was able to reproduce, I am closing this. It seemed to be simple one (locked status), but definitely something more site specific.

Please feel free to open another issue(s) for the subtopics that are going on here :)
