### ISSUE TITLE
Default Admin Theme: drop down menus static width

### ISSUE THREAD

**Issue by mike-anthony** [ryancramerdesign/ProcessWire#852]
I think the drop-down menus should grow if an item's length exceeds the default width.

Otherwise, you'd end up with something like this when using navJSON:

![shot1](https://cloud.githubusercontent.com/assets/4586280/5634848/151a073e-95ec-11e4-9459-1e3474a34219.png)

Sure, we should use shorter titles, but what happens if one can't?

**Comment by ryancramerdesign** [comment]
Strange, I'm not seeing that here–the menus grow in width to accommodate whatever is in there. I also notice a wide gap between the menu and submenu in your screenshot, which is something I've also not seen before. So I'm wondering if somehow the intended width ended up as a margin outside of the menu rather than as padding inside the menu. These are just jQuery UI menus, so something where jQuery UI is taking care of those details for us. I've tested in Chrome, Safari and Firefox but not seeing the issue in any of them. You mentioned Opera in another issue report I think, so if that's where this screenshot is from I'm betting jQuery UI has some output issue with Opera?

**Comment by mike-anthony** [comment]
It would be weird if it was Opera - it is using the same engine as Chrome... I'm just wondering if it has something to do with navJSON. I'm not using it in the module anymore, but it seemed quite jagged.
