### ISSUE TITLE
Can not save a page with repeater with table

### ISSUE THREAD

**Issue by gsbelarus** [ryancramerdesign/ProcessWire#870]
Hi,

I have a page with a repeater. Repeater by itself includes a table.

Starting with 2.5.14 I can not save the page. The error message appears:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by ryancramerdesign** [comment]
You might want to check your /site/assets/logs/errors.txt file to see what the error was. Or better yet, test with debug mode enabled (/site/config.php, $config->debug=true). However, I'm not positive you'll be able to stack repeaters with tables. I'm not sure exactly which table you mean (FieldtypeTable, FieldtypePageTable, or one of the others?) but for the most part these multi-value compound types aren't meant to be stacked on top of one another. They are meant to be either-or solutions. Though often when something won't work in a Repeater, it will work in a PageTable, so that may be worth trying too. PageTable can accept other compound types within it much more smoothly than Repeater.

**Comment by gsbelarus** [comment]
errors.txt doesn't contain any information regarding this error. debug and advanced modes also are not helpful.

**Comment by gsbelarus** [comment]
Seems that reason was not in a repeater with table but in the another repater. After deleting that repeater page could be saved without any error.
