### ISSUE TITLE
Float Field doesn't work correctly if language has set the locale to other than default "c"

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#880]
This has been an issue ever since locale in admin is introduced.

Not sure what the current stand is for this, but it's still broken and it only works if the locale is set to "c".

For example if set to "de_DE" (german) a float will render 10,32 and after saving again it will be 10

I enter 

10.32

After saving it shows

10,32

I save it again, then it is 

10

Is this something possible to fix?

Currently I'm just using "c" locale for other languages, which makes it impossible to use that as locale for admin.

**Comment by ryancramerdesign** [comment]
We've been here before, and if I recall there were some roadblocks when it came to the database and we had to revert. But I can duplicate the issue you mention and it's definitely not okay to leave it that way, so we've got to find something that works. I've attempted to do that in the latest commit. If the locale specifies commas as decimal points, it'll use that. In testing here, it all seems to work as desired, switching between German and English. Can you confirm? Thanks. There is still the question of DB side issues, but so far I'm not seeing anything here.

**Comment by Roope** [comment]
I'll put my findings here too, continuing from this forum post:
https://processwire.com/talk/topic/8251-type-float-converts-to-int/#entry81135

This fix worked here and now it uses comma as decimal for finnish language user:
```
1.23 -> 1,23
1,23 -> 1,23
```
This didn't seem to have any effect for float type in Table field though - it converts to integer all the time when there is language pack installed.
```
1.23 -> 1
1,23 -> 1
```
Another issue comes up when you have users with different locale settings - eg. some users has default language while another uses translations.

I switched the user back to default and saved the page:
```
1,23 -> 123
```
So basicly user with default language will break the values that user with finnish language has submitted.

**Comment by ryancramerdesign** [comment]
This won't have any effect for the Table field, as it's a different fieldtype. However, once we find something that works, I'll apply it to that as well. 

> So basicly user with default language will break the values that user with finnish language has submitted.

Numbers are stored as floats, so this shouldn't be able to occur unless you literally switched the user's language/locale in between the time you loaded the page (with the float field on it) and saved it. If your default locale is the same as that of PHP's default, or US or GB, then a comma is considered a thousands separator, not a decimal point. It's not uncommon here to copy/paste or import numbers from a spreadsheet that have commas for thousands separators, so in those locales we need a 99,999 to convert to 99999.00, not 99.999 or 99.00.

If I've misunderstood or you are still able to duplicate, please let me know the exact steps to take in order to get 1,23 to convert to 123 in a locale where commas aren't thousands separators (assuming you have the latest version of dev branch). When I switch to German, the number 99.99 shows as 99,99 in the field. If I save it, it continues to show 99,99. If I go change my language back to default, and edit the same page, I'm seeing 99.99. Basically, the database is saving a raw float number, and nothing about the locale is involved in the storage. The locale only comes into play when generating output or collecting input.

**Comment by Roope** [comment]
OK, just retested with fresh dev and couldn't repeat any more. Looks like there was just some tweaks for this in the latest commit 576a5d30153f045daa94a136a6ba981650632b26

Last time, when I changed language back to default, number was still presented as 1,23 (and then converted to 123 after page save). Now it was 1.23 after change back to default.

**Comment by isellsoap** [comment]
@Roope So this can be closed?
