### ISSUE TITLE
Enable file name translation from page name sanitizer by default

### ISSUE THREAD

**Issue by plauclair** [ryancramerdesign/ProcessWire#883]
I needed to have file names correctly translated.

Looking into Pagefiles.php I see on line 302 a $translate parameter in the cleanBaseName() function, that's set to false, and doesn't seem to have a way to set this to true from in any way.

This function is used on line 468 of Pagefile.php, without being set to true there either (not used at all actually).

I changed it to true in Pagefiles.php, but I'd rather not modify core files, obviously.

So a few questions:
1) Is it safe to enable $translate and is Pagefiles.php the right place?
2) Is there a reason this isn't defaulting to true?
3) If it's safe and there's no reason, could this be changed to default to true in a future version?

Thanks!

**Comment by ryancramerdesign** [comment]
Your line numbers don't match up with mine in Pagefile.php, so I'm thinking you might be running 2.5.3 rather than the current dev branch. But the current dev branch does do translation at file upload/install time, see this line: https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/core/Pagefile.php#L97 
The last argument there is true, which enables the translation when new files are added. As to whether it's translating files in the way you want, I can't say for certain, but it's worth a try–let me know. It should be using the settings as specified in the InputfieldPageName module settings for translation. 

As for enabling the translate option in other calls (outside of the install method) I wouldn't recommend it because the cleanBasename method is often used as a way to compare that one filename is the same was another, so it needs a consistent return value that isn't subject to variations in languages and such.

**Comment by plauclair** [comment]
Thanks for the precision, am indeed on 2.5.3 (in production).
