### ISSUE TITLE
fieldtype image selector inconsistency when attached to "user" template

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/ProcessWire#885]
ProcessWire 2.5.16 (latest dev):
I created a field called "image" of type "Image". The field "image" is configured like this:
Maxium files allowed -> 1
Formatted value -> Single item
Then I attached the field to the "user" template. 

I think the following selectors should deliver the same in frontend, but the don't. Notice the object type:
`$image = $pages->get('template=user,name=myuser')->image; // gives: object(Pageimage)`
`$image = $user->image; // gives: object(Pageimages)`

Why does the second selector return an array? Shouldn't it obey the field's settings and equally return a single item?

**Comment by ryancramerdesign** [comment]
You are seeing the difference between output formatting off and on here. Making a file/image field behave as a single file/image is a type of output formatting. In the example you mention, the $user object has output formatting turned off, which is why it's behaving as an array of times rather than a single item.
