### ISSUE TITLE
2.5.16 can't edit any pages anymore

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#892]
Fatal error: Call to a member function of() on a non-object in /home/www-data/*/wire/core/Page.php on line 664
Error: Call to a member function of() on a non-object (line 664 of /home/www-data/*/wire/core/Page.php) 
This error message was shown because site is in debug mode ($config->debug = true; in /site/config.php). Error has been logged. Administrator has been notified.

**Comment by somatonic** [comment]
I'm using the new alternative user template, location.. I think it has to do with that cause the error is here
$this->createdUser->of($this->of());

**Comment by somatonic** [comment]
Once I remove the config it works again

// $config->userTemplateIDs = array(3, 96);
// $config->usersPageIDs = array(29, 14017);

**Comment by somatonic** [comment]
Rolling this back cause too many bugs yet.

Now I can't remove the pass field from my template and get a fatal error

**Comment by ryancramerdesign** [comment]
Any other factors in this particular installation (modules, etc.?) I'm not
seeing the issue here. Though I will go ahead and add an extra check to the
line you mentioned to prevent it from causing an error.... Now taking a
closer look at that line, I'm guessing the error is occurring on a page
where the created user of that particular page no longer exists? That's the
only thing I can figure so far.

Regarding the pass field, that is a system/permanent field that is not
removable. You'd have to go into the DB for that one (fieldgroups table).

**Comment by somatonic** [comment]
Yep the user that created or modified don't exist anymore. I deleted some user previously.

But when I remove the config it works again, and the user created modified is a "?"

**Comment by ryancramerdesign** [comment]
I did put in a fix for this in Friday's commits, though not positive it's fixed since I've not seen the issue myself yet. But please let me know if you continue to see it.

**Comment by somatonic** [comment]
Still happends. I also experience this same error when using Dynamic Roles module and try to add a page.

Error: Call to a member function of() on a non-object (line 665 of /home/www-data/dev.1815.ch/wire/core/Page.php)
This error message was shown because site is in debug mode ($config->debug = true; in /site/config.php). Error has been logged. Administrator has been notified. 

Your "fix" doesn't change anything.
