### ISSUE TITLE
Notice Pagetable

### ISSUE THREAD

**Issue by junofornow** [ryancramerdesign/ProcessWire#908]
Notice: Undefined variable: customstyle in ***root***/site/modules/FieldtypeTable/InputfieldTable.module on line 197.

ProcessWire 2.5.17 dev / debug on.

**Comment by ryancramerdesign** [comment]
You've mentioned PageTable, but this appears to be for ProFields Table, since PageTable is part of the core, and ProFields Table is not. The location you identified is also the one used by ProFields Table. So I assume that's what were talking about rather than PageTable? But the strange thing is that the word "customstyle" does not appear anywhere in ProFields Table code (nor does it appear in PageTable). Also the line number you mentioned maps to a phpdoc comment. Is it possible you've got a modified version? You might want to grab the latest ProFields Table from the support board, just in case.

**Comment by junofornow** [comment]
You're absolutely right. I meant ProTable. And an update solved it.... Sorry.
