### ISSUE TITLE
old fancybox?

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#910]
Hi, since there is security trouble with fancybox and wordpress right now, i looked into the PW module. Is there a reason, why the super old version 1.2.6 is still in use here? There is a 1.3.4 and a 2.1.5 (commercial) plus tons of alternatives, including an optional module here for PW (Magnific)

**Comment by ryancramerdesign** [comment]
We're not using fancybox in the core anymore and haven't for while, but I got a complaint about removing it because some other module was using it, so decided to leave it there… just deprecated. It's probably okay to remove it from the core by PW 2.6, I'll put this on my list. What's the security issue you are referring to with WordPress and Fancybox? Since Fancybox is just client side, I'm guessing the issue is with some PHP integration portion they are using, but want to double check?

**Comment by tbba** [comment]
Not sure the same security problem exists outside of WP, probably not, I just wanted to mention it.
http://blog.sucuri.net/2015/02/zero-day-in-the-fancybox-for-wordpress-plugin.html
