### ISSUE TITLE
Ensure ProField Table is working

### ISSUE THREAD

**Issue by NicoKnoll** [ryancramerdesign/ProcessWire#920]
To ensure that the ProField Table is working you should add the following lines to the default .htaccess (or set a higher limit):

<pre>
php_value max_input_vars 3000
php_value suhosin.get.max_vars 3000
php_value suhosin.post.max_vars 3000
php_value suhosin.request.max_vars 3000
</pre>

**Comment by ryancramerdesign** [comment]
This would really be server and site specific, and applicable only to situations where one has potentially hundreds or thousands of fields of any sort (repeaters and tables being an easy way to get there). Not all servers will even accept php_value, as I think that requires a specific apache setup to support. I'm going to close this one out because I think this is not specific to ProcessWire, but still a good thing to mention–I will add a note about it in the Table docs. Thanks.

**Comment by NicoKnoll** [comment]
Okay :)
