### ISSUE TITLE
Error When Doing A Numeric Search (PW 2.5.19)

### ISSUE THREAD

**Issue by cstevensjr** [ryancramerdesign/ProcessWire#934]
I created a new page field "crms_tags" and used the InputfieldChosenSelect as the inputfield. I then added the field "crms_tags" to the standard PW search.php template.

Everything works great until I search on a tag that is of a numeric value. I then received the following error:

![search-error1](https://cloud.githubusercontent.com/assets/7488817/6239435/97c2b040-b6b8-11e4-9dfa-da68f981ef61.png)

Once I removed this field "crms_tags" from the search.php template, there was no more problems. I could again search for text or numeric information.

After opening an issue with @LostKobrakai, he correctly informed me that the problem could not be with his inputfield and rightly suggested that I try it on another inputfield.  I tried the SelectMultiple and AsmSelect and got the same error when the "crms_tags" field was in the search.php template.

This seach.php template already had other page fields in the search criteria.  So I added a new numeric page "2015" to one of the existing page fields that is in the search criteria and everything worked alright.  No error at all when searching.

**Comment by ryancramerdesign** [comment]
When you specify a numeric value to a page field, it is assumed to be a page ID. In fact, page IDs are what it expects as the default, as they are the only thing that is truly unique among all other pages. It only supports automatic conversion of non-numeric name/title as a convenience for you, and only when it detects that the value specified contains non-numeric characters. For your case, you'll want to be more specific, since you are wanting to match a name or title. For instance, you would specify crms_tags.name=2015 or crms_tags.title=2015.

**Comment by cstevensjr** [comment]
Thanks. Makes sense to me and I am grateful I got to learn something new.
