### ISSUE TITLE
FontIcon Picker icons too small.

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#941]
I can hardly see the icons they're so small.

Also when hovering the icon there should be a tooltip to see the name. Maybe a title attr will suffice.

**Comment by owzim** [comment]
:+1:

**Comment by ryancramerdesign** [comment]
The icons are designed for 14px as the optimal size, which is what we display them at. I think the issue might be more the spacing–they are pretty close together. I'll add more spacing and add title attributes.

**Comment by somatonic** [comment]
Please think of use older persons. My eyes hurt after short amount of time looking at those, more spacing helps a little. I know the icons are optimized at 14px but also for 28px 42px etc. So maybe use the http://fortawesome.github.io/Font-Awesome/examples/ fa-2x.

**Comment by apeisa** [comment]
I think the icons should be displayed in same size than they are used in
other places (like pagetree and labels).

**Comment by ryancramerdesign** [comment]
I agree, I think that size consistency is important. The latest commit has
them spaced out a lot more, and I think it does make a difference–makes
them seem bigger. We could always make them enlarge on hover or something
too.

Soma, my eyes are also tired elderly bloodshot eyes that struggle on all
kinds of things. Hit the Command and "=" keys, and it makes everything
bigger for those times when you want it. Also, just because those retina
MacBooks will let you output at 3800 pixels by 2100 pixels doesn't mean you
should run at that resolution on a 13" screen. :)

**Comment by Da-Fecto** [comment]
I agree here with Soma, the icons are to small to find the right one. The new inputfield doesn't hold me back from going to fontawesome.io

**Comment by NicoKnoll** [comment]
Maybe Ryan could add a "size" option to the module config so you can enter which font-size you want them. Default could be the current size so you want notice this change until you look in the modules config

**Comment by owzim** [comment]
I like Nico's suggestion. Trade-off, everyone's happy :)
