### ISSUE TITLE
Image crop and replace original, shows previous in lightbox zoom version

### ISSUE THREAD

**Issue by somatonic** [ryancramerdesign/ProcessWire#943]
![image](https://cloud.githubusercontent.com/assets/370148/6256056/3988e6a4-b7b5-11e4-8fac-94cd5b503ff5.png)

When clicking on the thumbnail it still shows the old original uploaded image.

![image](https://cloud.githubusercontent.com/assets/370148/6256079/6b9e29ba-b7b5-11e4-8ce3-330e1e3e5270.png)

**Comment by somatonic** [comment]
Means when I then also go into RTE and insert image it shows the thumb of the new image,

![image](https://cloud.githubusercontent.com/assets/370148/6256105/a47f6104-b7b5-11e4-8244-98baf8630a54.png)

But when selecting it it show the old original uncropped.

![image](https://cloud.githubusercontent.com/assets/370148/6256118/b71d1ad6-b7b5-11e4-80ca-629c28a530f6.png)

**Comment by adrianbj** [comment]
I am also seeing caching issues with the thumbnail view when image is uploaded, modified, deleted and re-uploaded. The thumbnail shows the version from the initial modification/crop, rather than the new one. A hard reload fixes things, but will be confusing to site editors.

**Comment by ryancramerdesign** [comment]
Replace original means literally replace the filename of the original, so that anything pointing to the original still points to it. While I'm not seeing those cache issues here, it's not unexpected that browser cache would interfere, depending on the environment. For now definitely hit reload if you are seeing the wrong image. I'll see what additional cache busting measures we can implement here, but short of always delivering cache busted filenames on both back-and-front end, you'll have to reload in your browser at some point if you want to see the non-cached image. That's the nature of the beast.

**Comment by somatonic** [comment]
I also refreshed and openend/saved the page again, still showing the old original image. Anyway I'm not sure what it was, but it seems it's now working fine in the latest version.

**Comment by adrianbj** [comment]
To take the conversation a little more general - would it be possible to append the modified timestamp to the image url (back and front-end) if the modified and created timestamps don't match?

Actually, just looking at the db, it seems like the modified and created always match for images - shouldn't these be different when an image is replaced, or cropped/resized and "Save & Replace" is clicked? Looks like the modified field is never changed?
