### ISSUE TITLE
Issues with new Send to Templates functionality

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#947]
Firstly, two very minor things

1. The breadcrumb should no longer be: "Add to template(s) since it can be adding and removal
2. Maybe the url should be "setup/field/modify-templates?id" rather than "setup/field/send-templates?id"

Now for something more important :)

If you have a field edit page open in one browser tab and a template edit page open in another tab and you make changes to the fields in the template (via the template edit page), if you save the field in the other tab, you can get some weird behavior - for example it may try to delete the field from a template you've just added it to, or vice versa - add it to a template you just deleted it from. Not sure the best solution - almost need some js detection of changes to the checkboxes on the Actions tab - if there are no changes, then ignore any perceived differences in the status of the fields in the checked templates?

**Comment by ryancramerdesign** [comment]
1. Updated and will appear in this weeks commits–thanks.

2. I still prefer the send-templates naming for this, because we're sending commands to the template (whether adding or removing). 

3. I've gone ahead and updated both ProcessField and ProcessTemplate to monitor change events in JS and avoid processing the field changes unless a change event has been triggered. This will appear in this weeks commits. Thanks.

**Comment by adrianbj** [comment]
Awesome!
