### ISSUE TITLE
Trailing slash issue on Page Tree

### ISSUE THREAD

**Issue by mikerockett** [ryancramerdesign/ProcessWire#961]
So, this is no big deal, but it's a bit inconsistent:

The tooltips for the page tree are ignoring the template-specific trailing slash setting. If I turn off slashes, the tooltip still shows them.

**Comment by mike-anthony** [comment]
Changing line 514 of ProcessPageList.module from

    'path' => $page->path(),

to


    'path' => $page->url,

solves this.

Although I think it would be better to get `path()` to honour the trailing slash setting...

**Comment by mike-anthony** [comment]
Changing the `___path()` function in Page.php to this fixes the issue:

```php
protected function ___path() {
	if($this->id === 1) return '/';
	$path = '';
	$parents = $this->parents();
	foreach($parents as $parent) if($parent->id > 1) $path .= "/{$parent->name}";
	$result = $path . '/' . $this->name;
	if($this->template->slashUrls !== 0) $result .= '/';
	return $result;
}
```

That won't break anything, will it?

**Comment by ryancramerdesign** [comment]
Paths are supposed to be consistent (trailing slash), whereas URLs can be customized with different slash settings. As a result, it's probably not safe to change the path() method in that way, though I can't think of any immediate examples that it would break. But I think for this particular issue, a safer bet here would be to have ProcessPageList use the url rather than the path. Though ProcessPageList may be using the path for a reason, so I'll have to do more research on this. Will revisit after 2.6 is out. Thanks.
