### ISSUE TITLE
Template - show/if does not work for cke-fields any more

### ISSUE THREAD

**Issue by tbba** [ryancramerdesign/ProcessWire#993]
latest dev:

I have a template field set that is only shows if the body field has content (show if: __body!=""__ )
The body is a CKE textarea.

Expected: On loosing focus of the CKE textarea the behavior of the other field is set.
Right now: The behavior of the other field is set only after saving the page.

Additional info: I see this on a pagetable-field "row"-page - but I think that does not matter

**Comment by ryancramerdesign** [comment]
I don't think there's a reliable way for field dependencies to know if a rich text field is populated or not, because the content in the RTE can be contained separately from the markup visible outside of the RTE, and JS change events aren't triggered on the original field for dependencies to monitor. Most RTEs (or really any primarily-javascript widget replacing a field) would likely fall outside of what field dependencies can use. The only reason it works with asmSelect is because asmSelect was intentionally coded to update the original select field and force change events on it.... most JS widgets don't do this.
